Repository flutter/website, pull requests merged in 2018-11, with the labels that each got.

#1639 Augmenting the state management page.
  src/docs/development/data-and-backend/state-mgmt.md
Labels: cla: yes

#1641 Incorporating Wm's feedback.
  src/docs/development/data-and-backend/firebase.md
Labels: cla: yes

#1605 Adding a contributing page.
  CONTRIBUTING.md
Labels: cla: yes

#1646 [dash] Cookbook: a first cut at breadcrumbs; base for next/prev links
  _config.yml
  src/docs/cookbook/_group.md
  src/docs/cookbook/animation/opacity-animation.md
  src/docs/cookbook/design/snackbars.md
  src/docs/cookbook/index.md
  src/docs/development/ui/interactive/index.md
Labels: cla: yes, infrastructure

#1651 [dash] Have some sidenav entries open by default
  src/_data/sidenav.yml
Labels: cla: yes

#1650 Remove invisible characters displayed in linux and windows
  src/index.html
  src/showcase/index.html
Labels: cla: yes

#1652 Update Google Ads logo
  src/_assets/image/showcase/logo-ads.svg
  src/_data/showcases.yml
Labels: cla: yes

#1653 Update Youtube CTA copy
  src/index.html
Labels: cla: yes

#1654 Adding value proposition to first piece of text.
  src/index.html
Labels: cla: yes

#1655 Fix floated site figure layout overflow
  src/_assets/css/_base.scss
Labels: cla: yes

#1656 Style the sidebar nav to be more compact
  src/_assets/css/_sidebar.scss
  src/_assets/css/_variables.scss
Labels: cla: yes

#1661 [dash] Cookbook: adjust styling of all images
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_config.scss
  src/docs/cookbook/animation/opacity-animation.md
  src/docs/cookbook/design/drawer.md
  src/docs/cookbook/design/fonts.md
  src/docs/cookbook/design/orientation.md
  src/docs/cookbook/design/package-fonts.md
  src/docs/cookbook/design/snackbars.md
  src/docs/cookbook/design/tabs.md
  src/docs/cookbook/design/themes.md
  src/docs/cookbook/forms/focus.md
  src/docs/cookbook/forms/retrieve-input.md
  src/docs/cookbook/forms/validation.md
  src/docs/cookbook/gestures/dismissible.md
  src/docs/cookbook/gestures/handling-taps.md
  src/docs/cookbook/gestures/ripples.md
  src/docs/cookbook/images/fading-in-images.md
  src/docs/cookbook/images/network-image.md
  src/docs/cookbook/lists/basic-list.md
  src/docs/cookbook/lists/horizontal-list.md
  src/docs/cookbook/lists/long-lists.md
  src/docs/cookbook/lists/mixed-list.md
  src/docs/cookbook/navigation/hero-animations.md
  src/docs/cookbook/navigation/named-routes.md
  src/docs/cookbook/navigation/navigation-basics.md
  src/docs/cookbook/navigation/passing-data.md
  src/docs/cookbook/navigation/returning-data.md
  src/docs/cookbook/networking/background-parsing.md
  src/docs/cookbook/networking/web-sockets.md
  src/docs/get-started/test-drive/_try-hot-reload.md
Labels: cla: yes

#1658 Support for custom site-level banner
  src/_assets/css/_banner.scss
  src/_assets/css/_base.scss
  src/_assets/css/_landing-page.scss
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
  src/_assets/js/main.js
  src/_includes/banner.html
  src/_layouts/base.html
  src/_layouts/default.html
  src/images/flutter-chevron-bg.svg
  src/index.html
Labels: cla: yes

#1668 Sort state management links roughly by complexity
  src/docs/development/data-and-backend/state-mgmt.md
Labels: cla: yes

#1671 [dash] Upgrade firebase-tools and superstatic to v6
  package.json
Labels: cla: yes, infrastructure

#1673 Update copy for flutter survey CTA.
  src/_includes/banner.html
Labels: cla: yes

#1670 Update _get-sdk-win.md
  src/docs/get-started/install/_get-sdk-win.md
Labels: cla: yes

#1674 [dash] Condensing intro card
  src/_assets/css/_base.scss
  src/_assets/css/_homepage.scss
  src/index.html
Labels: cla: yes

#1669 Fixing typos.
  src/docs/development/data-and-backend/firebase.md
Labels: cla: yes

#1677 Implements community page
  src/_assets/css/_community.scss
  src/_assets/css/_homepage.scss
  src/_assets/css/_landing-page.scss
  src/_assets/css/_showcase.scss
  src/_assets/css/main.scss
  src/_assets/image/community/logo-github.png
  src/_assets/image/community/logo-gitter.svg
  src/_assets/image/community/logo-google-forms.png
  src/_assets/image/community/logo-google.png
  src/_assets/image/community/logo-medium.png
  src/_assets/image/community/logo-meetup.svg
  src/_assets/image/community/logo-reddit.png
  src/_assets/image/community/logo-slack.png
  src/_assets/image/community/logo-stack-overflow.png
  src/_assets/image/community/logo-twitter.png
  src/_assets/image/community/logo-youtube.png
  src/_assets/image/community/screen-github.png
  src/_assets/image/community/screen-meetup.png
  src/_assets/image/showcase/logo-google_adwords.png
  src/_data/community.yml
  src/community/index.html
  src/community/index.md
  src/index.html
  src/showcase/index.html
Labels: cla: yes

#1672 [dash] A few updates to the docs index page.
  src/_data/sidenav.yml
  src/docs/index.md
  src/docs/testing/oem-debuggers.md
Labels: cla: yes

#1683 [dash] Add showcase carousel slides
  src/_assets/css/_showcase.scss
  src/_assets/image/showcase/hero-abbey-road.jpg
  src/_assets/image/showcase/hero-alibaba.jpg
  src/_assets/js/main.js
  src/_data/showcases.yml
  src/index.html
  src/showcase/index.html
Labels: cla: yes

#1684 Make nav background sheet clickable in iOS
  src/_assets/css/_header.scss
Labels: cla: yes

#1685 Adds carousel indicators
  src/_assets/css/_bootstrap_adjust.scss
  src/_data/showcases.yml
  src/showcase/index.html
Labels: cla: yes

#1675 [dash] Dup widget pages under development/ui/widgets
  _config.yml
  firebase.json
  src/_data/docs_cards.yml
  src/_data/sidenav.yml
  src/_includes/catalogpage.html
  src/docs/development/ui/layout/index.md
  src/docs/development/ui/widgets
  src/docs/development/ui/widgets-intro.md
  src/docs/get-started/flutter-for/react-native-devs/index.md
  src/docs/reference/widgets/accessibility.md
  src/docs/reference/widgets/animation.md
  src/docs/reference/widgets/assets.md
  src/docs/reference/widgets/async.md
  src/docs/reference/widgets/basics.md
  src/docs/reference/widgets/catalog.md
  src/docs/reference/widgets/cupertino.md
  src/docs/reference/widgets/index.md
  src/docs/reference/widgets/input.md
  src/docs/reference/widgets/interaction.md
  src/docs/reference/widgets/layout.md
  src/docs/reference/widgets/material.md
  src/docs/reference/widgets/painting.md
  src/docs/reference/widgets/scrolling.md
  src/docs/reference/widgets/styling.md
  src/docs/reference/widgets/text.md
  src/docs/resources/faq.md
  src/index.html
Labels: cla: yes

#1692 [dash] Tweaking as per feedback.
  src/docs/index.md
Labels: cla: yes

#1697 Fixing errors that were lost from a previous PR.
  src/docs/get-started/install/_path-mac-linux.md
  src/docs/get-started/test-drive/_androidstudio.md
Labels: cla: yes

#1696 [dash] Add into to learn-more page.
  src/docs/get-started/learn-more.md
  src/docs/index.md
Labels: cla: yes

#1679 [dash] Updating a link to the Fluttery videos.
  src/docs/resources/videos.md
Labels: cla: yes

#1698 [dash] Prep for merge into master
  .firebaserc
  .travis.yml
  README.md
  _config.yml
Labels: cla: yes, infrastructure

#1699 Apply `toc: true` by default to doc pages only
  _config.yml
  src/404.md
  src/community/china.md
  src/community/index.html
  src/showcase/index.html
Labels: cla: yes, infrastructure

#1702 Update community.yml
  src/_data/community.yml
Labels: cla: yes

#1703 chore: update Gem versions
  tool/docker/Gemfile
  tool/docker/Gemfile.lock
Labels: cla: yes, infrastructure

#1700 fix name
  src/docs/development/data-and-backend/state-mgmt.md
Labels: cla: yes

#1701 Update libimobiledevice installation instructions
  src/docs/get-started/install/_ios-setup.md
Labels: cla: yes

#1707 Flip showcase Abbey Road image
  src/_assets/image/showcase/hero-abbey-road.jpg
  src/community/index.html
  src/showcase/index.html
Labels: cla: yes

#1711 Fix typo missing brackets opening
  src/docs/get-started/flutter-for/react-native-devs/index.md
Labels: cla: yes

#1709 adds `onPanStart`, `onPanUpdate` and `onPanEnd` documentation.
  src/docs/development/ui/advanced/gestures.md
Labels: cla: yes

#1715 Update JD showcase metadata
  src/_data/showcases.yml
Labels: cla: yes

#1722 Setting up a redirect for /setup
  firebase.json
Labels: cla: yes

#1718 Remove the survey banner
  src/_includes/banner.html
Labels: cla: yes

#1704 SDK Archive page: use BS tabs, drop "Show all" in favor of scrollable list
  src/_assets/js/archive.js
  src/_assets/js/tabs.js
  src/docs/development/tools/sdk/_os.md
  src/docs/development/tools/sdk/_sdk-archive-master.md
  src/docs/development/tools/sdk/archive.md
Labels: cla: yes, design, infrastructure

#1726 Add Cupertino textfield and datepicker. Clean up Cupertino catalog section
  src/_data/catalog/widgets.json
  src/images/widget-catalog/cupertino-date-picker.png
  src/images/widget-catalog/cupertino-textfield.png
Labels: cla: yes

#1732 External link cleanup
  src/docs/cookbook/persistence/key-value.md
  src/docs/cookbook/persistence/reading-writing-files.md
  src/docs/deployment/android.md
  src/docs/development/ui/animations/index.md
  src/docs/development/ui/assets-and-images.md
  src/docs/get-started/codelab.md
  src/docs/get-started/editor.md
  src/docs/get-started/flutter-for/xamarin-forms-devs.md
  src/docs/get-started/install/_android-setup.md
  src/docs/get-started/test-drive/_androidstudio.md
  src/docs/resources/faq.md
  src/docs/testing/debugging.md
  src/docs/testing/oem-debuggers.md
  src/docs/testing/ui-performance/index.md
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#1733 Drop `https://flutter.io` prefix from intrasite page links
  src/404.md
  src/docs/development/ui/assets-and-images.md
  src/docs/development/ui/interactive/index.md
  src/docs/get-started/flutter-for/xamarin-forms-devs.md
Labels: cla: yes

#1734 Updating pubspec after a fresh install
  pubspec.lock
Labels: cla: yes

#1737 Fixing more links
  _config_dev.yml
  src/docs/catalog/samples/basic-app-bar.md
  src/docs/catalog/samples/expansion-tile-sample.md
  src/docs/cookbook/animation/opacity-animation.md
  src/docs/cookbook/design/drawer.md
  src/docs/cookbook/design/snackbars.md
  src/docs/cookbook/navigation/hero-animations.md
  src/docs/deployment/android.md
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/ui/animations/index.md
  src/docs/development/ui/layout/index.md
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#1739 Drop invalid canonical page link element
  src/_includes/head.html
Labels: cla: yes

#1741 chore: update Gem versions, in particular for `rack`
  tool/docker/Gemfile.lock
Labels: cla: yes, infrastructure

#1742 Fix some typos in the "Introduction to integration testing" and "Rend…
  src/docs/cookbook/testing/integration/index.md
  src/docs/resources/rendering.md
Labels: cla: yes

#1740 Fix external links, most broken by paragraph word-wrapping
  src/docs/cookbook/images/fading-in-images.md
  src/docs/development/ui/animations/overview.md
  src/docs/get-started/flutter-for/android-devs.md
  src/docs/get-started/flutter-for/ios-devs.md
  src/docs/get-started/flutter-for/react-native-devs/index.md
  src/docs/get-started/flutter-for/xamarin-forms-devs.md
Labels: cla: yes

#1747 Fix 404s to Tapbox sources
  pubspec.lock
  src/docs/development/ui/interactive/index.md
Labels: cla: yes

#1746 Fix mistake on Cupertino catalog
  src/_data/catalog/widgets.json
Labels: cla: yes

#1751 Platform channels and generated plugins
  src/docs/development/platform-integration/platform-channels.md
Labels: cla: yes

#1752 Add discord to community
  src/_assets/image/community/logo-discord.png
  src/_data/community.yml
Labels: cla: yes

#1744 Replace <Null> with <void> for generics
  src/_includes/code/animation/basic_hero_animation/main.dart
  src/_includes/code/animation/basic_radial_hero_animation/main.dart
  src/_includes/code/animation/basic_staggered_animation/main.dart
  src/_includes/code/animation/hero_animation/main.dart
  src/_includes/code/animation/radial_hero_animation/main.dart
  src/_includes/code/animation/radial_hero_animation_animate_rectclip/main.dart
  src/_includes/code/animation/staggered_pic_selection/main.dart
  src/docs/cookbook/maintenance/error-reporting.md
  src/docs/development/platform-integration/platform-channels.md
  src/docs/development/ui/animations/hero-animations/index.md
  src/docs/development/ui/animations/staggered-animations/index.md
  src/docs/testing/debugging.md
  src/docs/testing/index.md
  src/docs/testing/oem-debuggers.md
Labels: cla: yes

#1759 Update minimal apk size
  src/docs/resources/faq.md
Labels: cla: yes

#1729 Adding an explanation of declarative vs imperative programming
  src/docs/get-started/flutter-for/android-devs.md
  src/docs/get-started/flutter-for/declarative.md
  src/docs/get-started/flutter-for/ios-devs.md
  src/docs/get-started/flutter-for/web-devs.md
  src/docs/get-started/flutter-for/xamarin-forms-devs.md
  src/images/declarativeUIchanges.png
Labels: cla: yes

#1761 Correct VS Code shortcut for quick-fixes
  src/docs/development/tools/ide/vs-code.md
Labels: cla: yes

#1760 Snackbar component, deprecated pages
  .firebaserc
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_snackbar.scss
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
  src/_assets/js/main.js
  src/_includes/snackbar.html
  src/_layouts/default.html
  src/docs/catalog/samples/AnimatedList.md
  src/docs/catalog/samples/AnimatedListState.md
  src/docs/catalog/samples/AppBar.md
  src/docs/catalog/samples/DefaultTabController.md
  src/docs/catalog/samples/ExpansionTile.md
  src/docs/catalog/samples/IconButton.md
  src/docs/catalog/samples/ListView.md
  src/docs/catalog/samples/PopupMenuButton.md
  src/docs/catalog/samples/PreferredSize.md
  src/docs/catalog/samples/Scaffold.md
  src/docs/catalog/samples/TabBar.md
  src/docs/catalog/samples/TabBarView.md
  src/docs/catalog/samples/TabController.md
  src/docs/catalog/samples/animated-list.md
  src/docs/catalog/samples/app-bar-bottom.md
  src/docs/catalog/samples/basic-app-bar.md
  src/docs/catalog/samples/expansion-tile-sample.md
  src/docs/catalog/samples/index.md
  src/docs/catalog/samples/tabbed-app-bar.md
Labels: cla: yes

#1770 Add 404 page
  src/404.html
  src/404.md
  src/_assets/css/_404.scss
  src/_assets/css/main.scss
  src/_assets/image/404/dash_nest.png
Labels: cla: yes

#1771 Update links on 404 page
  src/404.html
Labels: cla: yes

#1765 remove the IDE topics category; move IDE pages up one level
  firebase.json
  src/_data/sidenav.yml
  src/docs/development/tools/android-studio.md
  src/docs/development/tools/ide/index.md
  src/docs/development/tools/vs-code.md
  src/docs/development/ui/layout/index.md
  src/docs/resources/faq.md
  src/docs/testing/oem-debuggers.md
Labels: cla: yes

#1772 Better mobile handling for buttons and cta buttons
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_adjust.scss
Labels: cla: yes

#1777 fix the IDE side nav highlights
  src/_data/sidenav.yml
Labels: cla: yes

#1780 Fix some typos
  src/docs/development/ui/widgets-intro.md
Labels: cla: yes

#1782 Drop self-referential canonical links in site page heads
  src/_includes/head.html
Labels: cla: yes, infrastructure

#1774 Cookbook Updates
  src/docs/cookbook/design/themes.md
Labels: cla: yes

#1785 Add Samples catalog to sidenav
  src/_data/showcases.yml
  src/_data/sidenav.yml
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#1773 correctly attribute which chart is which thread
  src/docs/testing/ui-performance/index.md
Labels: cla: yes

#1788 Add redirects for top 404s (2018/11)
  firebase.json
Labels: cla: yes

#1790 Ensure flutter-for/react-native is mobile-friendly by making images responsive
  src/_assets/css/_base.scss
  src/_assets/image/get-started/android/react-native/api-calls.gif
  src/_assets/image/get-started/android/react-native/basic-layout.gif
  src/_assets/image/get-started/android/react-native/canvas.png
  src/_assets/image/get-started/android/react-native/card-swipe.gif
  src/_assets/image/get-started/android/react-native/custom-cards.png
  src/_assets/image/get-started/android/react-native/flatlist.gif
  src/_assets/image/get-started/android/react-native/flutter-fade.gif
  src/_assets/image/get-started/android/react-native/flutter-gestures.gif
  src/_assets/image/get-started/android/react-native/flutterstyling.gif
  src/_assets/image/get-started/android/react-native/hello-world-basic.png
  src/_assets/image/get-started/android/react-native/hello-world.png
  src/_assets/image/get-started/android/react-native/input-fields.gif
  src/_assets/image/get-started/android/react-native/modular.png
  src/_assets/image/get-started/android/react-native/navigation.gif
  src/_assets/image/get-started/android/react-native/stack.png
  src/_assets/image/get-started/android/react-native/state-change.gif
  src/_assets/image/get-started/ios/react-native/api-calls.gif
  src/_assets/image/get-started/ios/react-native/basic-layout.gif
  src/_assets/image/get-started/ios/react-native/canvas.png
  src/_assets/image/get-started/ios/react-native/card-swipe.gif
  src/_assets/image/get-started/ios/react-native/custom-cards.png
  src/_assets/image/get-started/ios/react-native/flatlist.gif
  src/_assets/image/get-started/ios/react-native/flutter-fade.gif
  src/_assets/image/get-started/ios/react-native/flutter-gestures.gif
  src/_assets/image/get-started/ios/react-native/flutterstyling.gif
  src/_assets/image/get-started/ios/react-native/hello-world-basic.png
  src/_assets/image/get-started/ios/react-native/hello-world.png
  src/_assets/image/get-started/ios/react-native/input-fields.gif
  src/_assets/image/get-started/ios/react-native/modular.png
  src/_assets/image/get-started/ios/react-native/navigation.gif
  src/_assets/image/get-started/ios/react-native/stack.png
  src/_assets/image/get-started/ios/react-native/state-change.gif
  src/docs/get-started/flutter-for/_android-ios-figure-pair.md
  src/docs/get-started/flutter-for/react-native-devs.md
  src/docs/get-started/flutter-for/react-native-devs/images/6b18b6e158b15685.png
  src/docs/get-started/flutter-for/react-native-devs/images/android.png
  src/docs/get-started/flutter-for/react-native-devs/images/canvas_android.png
  src/docs/get-started/flutter-for/react-native-devs/images/canvas_iOS.png
  src/docs/get-started/flutter-for/react-native-devs/images/flutter_fade_android.gif
  src/docs/get-started/flutter-for/react-native-devs/images/flutter_gestures_android.gif
  src/docs/get-started/flutter-for/react-native-devs/images/flutter_gestures_iOS.gif
  src/docs/get-started/flutter-for/react-native-devs/images/hello_world_basic_android.png
  src/docs/get-started/flutter-for/react-native-devs/images/hello_world_basic_iOS.png
  src/docs/get-started/flutter-for/react-native-devs/images/iOS.png
  src/docs/get-started/flutter-for/react-native-devs/images/modular_android.png
  src/docs/get-started/flutter-for/react-native-devs/images/modular_iOS.png
  src/docs/get-started/flutter-for/react-native-devs/images/stack_android.png
  src/docs/get-started/flutter-for/react-native-devs/images/stack_iOS.png
Labels: cla: yes

#1791 flutter-for/react-native: fix link
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#1792 chore: linkcheck package update
  pubspec.lock
  pubspec.yaml
Labels: cla: yes, infrastructure

#1796 Make android-ios-figure-pair.md a global include
  src/_includes/android-ios-figure-pair.md
  src/docs/get-started/_android-ios-figure-pair.md
  src/docs/get-started/codelab.md
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes, infrastructure

#1804 Redirect old widget catalog page links to development/ui/widgets
  firebase.json
Labels: cla: yes

#1805 Adjust link text to match destination page title
  src/docs/get-started/learn-more.md
Labels: cla: yes

#1807 Drop field with invalid link from catalog/index.json data
  src/_data/catalog/index.json
Labels: cla: yes

#1806 Test drive: add note about comments in code
  src/docs/get-started/test-drive/_androidstudio.md
  src/docs/get-started/test-drive/_main-code-note.md
  src/docs/get-started/test-drive/_terminal.md
  src/docs/get-started/test-drive/_vscode.md
Labels: cla: yes
