Repository flutter/website, pull requests merged in 2018-02, with the labels that each got.

#794 Update AUTHORS
  AUTHORS
Labels: cla: yes

#795 Minor things for JSON article: typo fixes, clarifications, rewordings
  json.md
Labels: cla: yes

#796 Update json_serializable and build_runner versions & remove obsolete library directive from sample
  json.md
Labels: cla: yes

#802 Add an entry for background execution
  faq.md
Labels: cla: yes

#808 Update README.md
  README.md
Labels: cla: yes

#809 Add a temporary redirect for the new 'get started' landing page
  firebase.json
Labels: cla: yes

#805 [Material] Updating copy mentioning Material
  _data/catalog/index.json
  _data/catalog/widgets.json
  animations/staggered-animations/index.md
  catalog/samples/animated_list.md
  catalog/samples/app_bar_bottom.md
  catalog/samples/basic_app_bar.md
  catalog/samples/expansion_tile_sample.md
  catalog/samples/tabbed_app_bar.md
  debugging.md
  faq.md
  flutter-for-android.md
  gestures.md
  getting-started.md
  index.md
  technical-overview.md
  tutorials/interactive/index.md
  tutorials/international/index.md
  tutorials/layout/index.md
  widgets-intro.md
  widgets/cupertino.md
  widgets/materialdesign.md
Labels: cla: yes, faq, getting started, tutorial

#803 Move imports above code depending on imports
  platform-channels.md
Labels: cla: yes

#810 Fix missing material page contents
  widgets/materialdesign.md
Labels: cla: yes

#807 Initial Widget Inspector page
  _includes/sidebar.html
  inspector.md
Labels: cla: yes

#806 Cookbook: Let's get it started in here.
  _includes/sidebar.html
  _sass/_customstyles.scss
  cookbook/index.md
  cookbook/networking/fetch-data.md
Labels: cla: yes

#811 Cookbook: More recipes
  cookbook/images/network-image.md
  cookbook/index.md
  cookbook/lists/basic-list.md
  cookbook/lists/horizontal-list.md
  cookbook/lists/long-lists.md
  cookbook/networking/authenticated-requests.md
Labels: cla: no

#812 Update inspector documentation.
  images/intellij/inspector_select_example.gif
  images/intellij/switch_inspector_tree.gif
  images/intellij/visual-debugging.png
  inspector.md
  using-ide.md
Labels: cla: yes

#813 Remove the “Building a Flutter app?” banner
  _layouts/page.html
Labels: cla: yes

#814 Put gif of final app to the right of TOC
  _sass/_base.scss
  _sass/_customstyles.scss
  get-started/codelab/images/startup-namer-app.gif
  get-started/codelab/index.md
Labels: cla: yes

#798 "Getting started with Flutter" codelab/tutorial
  _sass/_base.scss
  _sass/_customstyles.scss
  get-started/codelab/images/AndroidStudioIcon.png
  get-started/codelab/images/green-run.png
  get-started/codelab/images/hello-world-screenshot.png
  get-started/codelab/images/hot-reload-button.png
  get-started/codelab/images/startup-namer-app.gif
  get-started/codelab/images/step2-screenshot.png
  get-started/codelab/images/step3-screenshot.png
  get-started/codelab/images/step4-screenshot.png
  get-started/codelab/images/step5-screenshot.png
  get-started/codelab/images/step6a-screenshot.png
  get-started/codelab/images/step6b-screenshot.png
  get-started/codelab/images/step7-themes.png
  get-started/codelab/index.md
Labels: cla: no

#818 Tweak
  get-started/codelab/index.md
Labels: cla: yes

#819 Tweak VS Code format text
  get-started/codelab/index.md
Labels: cla: yes

#820 Incorporating some of Pascal's feedback.
  get-started/codelab/index.md
Labels: cla: yes

#800 Reworked getting started experience
  _includes/setup/editor-setup.md
  _includes/setup/get-sdk-win.md
  _includes/setup/get-sdk.md
  _includes/setup/path-mac-linux.md
  _includes/sidebar.html
  _layouts/default.html
  _sass/_tabs.scss
  animations/hero-animations/index.md
  css/main.scss
  firebase.json
  formatting.md
  get-started/codelab/index.md
  get-started/editor.md
  get-started/index.md
  get-started/install.md
  get-started/learn-more.md
  get-started/setup_linux.md
  get-started/setup_macos.md
  get-started/setup_windows.md
  get-started/test-drive.md
  getting-started.md
  ide-setup.md
  images/flutter-starter-app-android.png
  index.md
  inspector.md
  js/tabs.js
  setup.md
  technical-overview.md
  tutorials/interactive/index.md
  tutorials/layout/index.md
  using-ide.md
Labels: cla: yes

#823 Tweaking
  get-started/codelab/index.md
Labels: cla: yes

#816 Add a way to check links and redirects
  README.md
  tool/sitemap.txt
Labels: cla: yes

#824 Ignore Jekyll metadata
  .gitignore
Labels: cla: yes

#817 Add first version of flutter.io/docs
  _data/docs_cards.yml
  docs.md
Labels: cla: yes

#825 Tweaking the docs landing page.
  _data/docs_cards.yml
  docs.md
Labels: cla: yes

#827 Make the final app gif look more like an app
  get-started/codelab/images/startup-namer-app.gif
  get-started/codelab/index.md
Labels: cla: yes

#828 Minor text tweaks
  _includes/sidebar.html
  docs.md
Labels: cla: yes

#830 Clarifying the description for the _buildRow method.
  get-started/codelab/index.md
Labels: cla: yes

#833 Add Learn More link
  index.md
Labels: cla: yes

#826 Specify --no-codesign when testing plugin development
  developing-packages.md
Labels: cla: yes

#834 Correct typo in editor.md
  get-started/editor.md
Labels: cla: yes

#835 Hide Firebase codelab from sidenav
  _includes/sidebar.html
Labels: cla: yes

#837 Change dev to beta
  upgrading.md
Labels: cla: yes

#801 Flutter for React Native Developers
  _includes/sidebar.html
  flutter-for-react-native.md
Labels: cla: yes

#821 Update get-sdk-win's flutter doctor section
  _includes/setup/get-sdk-win.md
  _includes/setup/get-sdk.md
Labels: cla: yes
