Repository flutter/website, pull requests merged in 2018-12, with the labels that each got.

#1815 Fix sample CSS indentation
  src/docs/get-started/flutter-for/web-devs.md
Labels: cla: yes

#1809 Avoid duplicate widget catalog pages
  firebase.json
  src/docs/development/ui/animations/index.md
  src/docs/development/ui/layout/index.md
  src/docs/development/ui/widgets
  src/docs/development/ui/widgets-intro.md
  src/docs/development/ui/widgets/accessibility.md
  src/docs/development/ui/widgets/animation.md
  src/docs/development/ui/widgets/assets.md
  src/docs/development/ui/widgets/async.md
  src/docs/development/ui/widgets/basics.md
  src/docs/development/ui/widgets/cupertino.md
  src/docs/development/ui/widgets/index.md
  src/docs/development/ui/widgets/input.md
  src/docs/development/ui/widgets/interaction.md
  src/docs/development/ui/widgets/layout.md
  src/docs/development/ui/widgets/material.md
  src/docs/development/ui/widgets/painting.md
  src/docs/development/ui/widgets/scrolling.md
  src/docs/development/ui/widgets/styling.md
  src/docs/development/ui/widgets/text.md
  src/docs/get-started/flutter-for/android-devs.md
  src/docs/get-started/flutter-for/ios-devs.md
  src/docs/get-started/flutter-for/react-native-devs.md
  src/docs/get-started/flutter-for/xamarin-forms-devs.md
  src/docs/reference/widgets.md
  src/docs/resources/faq.md
Labels: cla: yes

#1813 missing comma
  src/docs/get-started/flutter-for/web-devs.md
Labels: cla: yes

#1862 Banner update
  src/_includes/banner.html
Labels: cla: yes

#1868 Flutter 1.0 stable!
  _config.yml
  src/_assets/js/archive.js
  src/_includes/banner.html
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#1811 Make flutter-for/react-native tables more mobile-friendly
  src/_assets/css/_base.scss
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#1869 Fix http.get() API 404
  src/docs/cookbook/networking/background-parsing.md
  src/docs/cookbook/networking/fetch-data.md
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#1872 Replace old homepage news item
  src/_assets/image/homepage/news-1.png
  src/index.html
Labels: cla: yes

#1874 FAQ: mention Hummingbird
  src/docs/resources/faq.md
Labels: cla: yes

#1884 SDK archive page: show all channels
  src/docs/development/tools/sdk/_os.md
Labels: cla: yes, infrastructure

#1888 Long-lists cookbook page copyedit
  src/docs/cookbook/lists/long-lists.md
Labels: cla: yes

#1890 Add JD Finance iOS app store link
  src/_data/showcases.yml
Labels: cla: yes

#1892 Fix code highlighting in Flutter for React Native page
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#1894 Flutter for React Native: fix Dartpad code excerpt
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#1896 Add PageView widget to widget list and Scrolling category
  src/_data/catalog/widgets.json
Labels: cla: yes

#1900 chore: update firebase-tools and tweak rule
  firebase.json
  package.json
Labels: cla: yes, infrastructure

#1902 Cleanup: don't show pages with empty TOCs
  _config.yml
  src/docs/development/ui/navigation.md
  src/docs/reference/widgets.md
Labels: cla: yes

#1899 Add Expanded widget as a "Layout helper"
  src/_data/catalog/index.json
  src/_data/catalog/widgets.json
Labels: cla: yes

#1904 Test drive, terminal variant: properly explain how to hot reload
  src/docs/get-started/test-drive/_terminal.md
  src/docs/get-started/test-drive/_try-hot-reload.md
Labels: cla: yes

#1903 Add DropdownButton
  src/_data/catalog/widgets.json
Labels: cla: yes

#1907 Ensure that intermediate breadcrumb TOC pages have content
  src/_layouts/toc.html
  src/docs/development/index.md
Labels: cla: yes

#1919 Fixes #1887: Hide any previous snackbars and show the latest result
  src/docs/cookbook/navigation/returning-data.md
Labels: cla: yes

#1926 Generalize app-figure.md template
  src/_includes/app-figure.md
  src/docs/get-started/codelab.md
  src/docs/get-started/test-drive/_try-hot-reload.md
Labels: cla: yes, infrastructure

#1930 Add CupertinoPopupSurface to widget catalog
  src/_data/catalog/widgets.json
Labels: cla: yes

#1931 Update Google Ads logo on homepage
  src/_assets/image/homepage/logo-google_ads.png
  src/_assets/image/homepage/logo-google_adsx.png
  src/_assets/image/homepage/logo-google_adwords.png
  src/index.html
Labels: cla: yes

#1932 Drop alternate (unused) Google Ads logo
  src/_assets/image/homepage/logo-google_adsx.png
Labels: cla: yes

#1925 Add mockito links to testing page
  src/docs/testing/index.md
Labels: cla: yes

#1934 Homepage: fix use-case and news spacing
  src/_assets/css/_homepage.scss
  src/_assets/css/_landing-page.scss
  src/index.html
Labels: cla: yes, design

#1941 External link 404: comment out JD Finance AppStore link
  src/_data/showcases.yml
Labels: cla: yes

#1939 Building Layouts: make images responsive, and other mobile-friendly adjustments
  src/_assets/image/ui/layout/button-section-diagram.png
  src/_assets/image/ui/layout/card-flutter-gallery.png
  src/_assets/image/ui/layout/card.png
  src/_assets/image/ui/layout/column-diagram.png
  src/_assets/image/ui/layout/column-visual.png
  src/_assets/image/ui/layout/container.png
  src/_assets/image/ui/layout/gridview-count-flutter-gallery.png
  src/_assets/image/ui/layout/gridview-extent.png
  src/_assets/image/ui/layout/hello-world.png
  src/_assets/image/ui/layout/lakes-column-elts.png
  src/_assets/image/ui/layout/lakes-icons-visual.png
  src/_assets/image/ui/layout/lakes-icons.png
  src/_assets/image/ui/layout/lakes.jpg
  src/_assets/image/ui/layout/layout-too-large.png
  src/_assets/image/ui/layout/listtile-flutter-gallery.png
  src/_assets/image/ui/layout/listview-flutter-gallery.png
  src/_assets/image/ui/layout/listview.png
  src/_assets/image/ui/layout/margin-padding-border.png
  src/_assets/image/ui/layout/packed.png
  src/_assets/image/ui/layout/pavlova-diagram.png
  src/_assets/image/ui/layout/pavlova-icons-row-diagram.png
  src/_assets/image/ui/layout/pavlova-large-annotated.png
  src/_assets/image/ui/layout/pavlova-large.png
  src/_assets/image/ui/layout/pavlova-left-column-diagram.png
  src/_assets/image/ui/layout/pavlova-ratings-row-diagram.png
  src/_assets/image/ui/layout/pavlova-visual.png
  src/_assets/image/ui/layout/pavlova.png
  src/_assets/image/ui/layout/row-diagram.png
  src/_assets/image/ui/layout/row-expanded-2-visual.png
  src/_assets/image/ui/layout/row-expanded-visual.png
  src/_assets/image/ui/layout/row-spaceevenly-visual.png
  src/_assets/image/ui/layout/sample-flutter-layout.png
  src/_assets/image/ui/layout/stack-flutter-gallery.png
  src/_assets/image/ui/layout/stack.png
  src/_assets/image/ui/layout/title-section-parts.png
  src/_assets/image/ui/layout/widget-tree-pavlova-icon-row.png
  src/_assets/image/ui/layout/widget-tree-pavlova-rating-row.png
  src/docs/development/ui/layout/images/lakes-diagram.png
  src/docs/development/ui/layout/index.md
Labels: cla: yes, mobile

#1943 Change Fluter 1.0 news image
  src/_assets/image/homepage/news-1.png
Labels: cla: yes

#1944 Add back the link to JD Finance iOS app, but don't check it
  src/_data/showcases.yml
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#1942 Add a link to the Flutter App Highlight Reel
  src/showcase/index.html
Labels: cla: yes

#1953 SDK archive page: tweak download table CSS
  src/docs/development/tools/sdk/archive.md
Labels: cla: yes

#1973 Install page copyedits
  src/docs/get-started/install/_get-sdk.md
Labels: cla: yes

#1978 FAQ typos: object-orientated -> object-oriented
  src/docs/resources/faq.md
Labels: cla: yes

#1979 Fix `android/app/build.gradle`
  src/docs/deployment/android.md
Labels: cla: yes

#1974 MacOS install: "Deploying to iOS device" section rework
  src/docs/get-started/install/_ios-setup.md
Labels: cla: yes

#2014 Community > GitHub: show issue with thumbs-ups
  src/_assets/image/community/screen-github.png
  src/_data/community.yml
  src/community/index.html
Labels: cla: yes

#2017 chore: upgrade to v1 of `build_runner`
  pubspec.yaml
Labels: cla: yes

#2020 chore: site alert style fixes due to fontawesome icon changes
  _config.yml
Labels: cla: yes

#2016 Clarify that China support is community run
  src/community/china.md
Labels: cla: yes

#2022 Flutter for React Native developers: sync DartPad with code excerpt
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#2025 Fix fastlane CI documentation link
  src/docs/deployment/fastlane-cd.md
Labels: cla: yes

#2018 Update 'Building layouts' page dart code reference
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2028 Update minimal APK size
  src/docs/resources/faq.md
Labels: cla: yes

#2037 Fix links to codelab sources
  _config.yml
  src/docs/get-started/codelab.md
Labels: cla: yes

#2043 Add minimal IPA size to FAQ
  src/docs/resources/faq.md
Labels: cla: yes

#2053 Add and use new code_diff plugin
  pubspec.lock
  src/_plugins/code_diff.rb
  src/_plugins/dart_site_util.rb
  src/docs/get-started/codelab.md
Labels: cla: yes

#2049 Added CircularProgressIndicator; edited LPI description
  src/_data/catalog/widgets.json
Labels: cla: yes

#2090 Fixed the get-started urls by add docs/
  src/_includes/header.html
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/tools/android-studio.md
  src/docs/development/tools/formatting.md
  src/docs/development/tools/hot-reload.md
  src/docs/development/tools/inspector.md
  src/docs/development/tools/vs-code.md
  src/docs/development/ui/animations/hero-animations/index.md
  src/docs/development/ui/interactive/index.md
  src/docs/development/ui/layout/index.md
  src/docs/get-started/codelab.md
  src/docs/get-started/editor.md
  src/docs/get-started/flutter-for/react-native-devs.md
  src/docs/get-started/install/index.md
  src/docs/get-started/install/linux.md
  src/docs/get-started/install/macos.md
  src/docs/get-started/install/windows.md
  src/docs/get-started/learn-more.md
  src/docs/get-started/test-drive/_terminal.md
  src/docs/get-started/test-drive/_vscode.md
  src/docs/get-started/test-drive/index.md
  src/docs/resources/faq.md
  src/docs/resources/technical-overview.md
  src/docs/testing/debugging.md
  src/docs/testing/oem-debuggers.md
  src/showcase/index.html
Labels: cla: yes

#2091 Fix two top 404s as of Dec 18
  firebase.json
Labels: E0, cla: yes, infrastructure

#2073 Add FAQ to doc homepage
  src/docs/index.md
Labels: cla: yes

#2045 Update linux.md
  src/docs/get-started/install/linux.md
Labels: cla: yes

#1820 Update react-native-devs.md
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes, question

#1816 Update android.md
  src/docs/deployment/android.md
Labels: cla: yes

#1946 Update the FAQ
  src/docs/resources/faq.md
Labels: cla: yes

#1866 iOS simulator, Android emulator
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#2097 Add Chinese pub mirror to skip list
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#2099 Update internationalization.md
  src/docs/development/accessibility-and-localization/internationalization.md
Labels: cla: yes

#2106 Update ios-devs.md
  src/docs/get-started/flutter-for/ios-devs.md
Labels: cla: yes

#2112 JSON page edits
  _config.yml
  src/docs/development/data-and-backend/json.md
Labels: cla: yes

#2119 Wrong url
  src/docs/development/ui/animations/hero-animations/index.md
Labels: cla: yes

#2120 Make tutorials more easily discoverable
  src/_data/sidenav.yml
Labels: cla: yes

#2114 Homepage: add Reflectly description, and fix layout
  src/_assets/css/_homepage.scss
  src/index.html
Labels: E1, cla: yes, design

#2125 Don't add "Contents" heading when there is no TOC
  src/_includes/toc.html
  src/_layouts/default.html
  src/docs/catalog/samples/index.md
  src/docs/development/tools/sdk/archive.md
  src/docs/development/ui/navigation.md
  src/docs/development/ui/widgets/assets.md
  src/docs/development/ui/widgets/index.md
  src/docs/get-started/editor.md
  src/docs/get-started/install/index.md
  src/docs/get-started/learn-more.md
  src/docs/get-started/test-drive/index.md
  src/docs/reference/tutorials.md
  src/docs/reference/widgets.md
  src/docs/resources/bootstrap-into-dart.md
Labels: cla: yes, infrastructure

#2127 Ensure pages have appropriate heading levels
  src/docs/development/ui/animations/overview.md
  src/docs/resources/inside-flutter.md
Labels: cla: yes

#2128 Revert to "toc:false" for pages with tabbed content
  src/docs/development/tools/sdk/archive.md
  src/docs/get-started/editor.md
  src/docs/get-started/test-drive/index.md
Labels: cla: yes
