Repository flutter/website, pull requests merged in 2018-08, with the labels that each got.

#1124 Updating getting started codelab
  _config.yml
  get-started/codelab/images/android-hello-world-frame.png
  get-started/codelab/images/android-infinite-list-frame.png
  get-started/codelab/images/android-step2-frame.png
  get-started/codelab/images/hello-world-screenshot-ios.png
  get-started/codelab/images/startup_namer_1_opt.gif
  get-started/codelab/images/step2-screenshot-ios.png
  get-started/codelab/images/step3-screenshot.png
  get-started/codelab/images/step4-screenshot-ios.png
  get-started/codelab/images/step5-screenshot.png
  get-started/codelab/images/step6a-screenshot.png
  get-started/codelab/images/step6b-screenshot.png
  get-started/codelab/images/step7-themes.png
  get-started/codelab/index.md
Labels: cla: no

#1130 Update FAQ entry about app size
  faq.md
Labels: cla: yes

#1127 Fix url of Debugging Flutter Apps
  tutorials/layout/index.md
Labels: cla: yes

#1132 Add the FlutterDev subreddit
  support.md
Labels: cla: yes

#1137 Change references to Flutter Travis build to Cirrus
  debugging.md
  design-principles.md
  fastlane.md
Labels: cla: yes

#1145 Fixing broken links to dartlang. (Fix build)
  bootstrap-into-dart.md
  widgets-intro.md
Labels: cla: yes

#1144 Removed a redundant line
  get-started/learn-more.md
Labels: cla: yes

#1139 Add ListTile link
  cookbook/lists/basic-list.md
Labels: cla: yes

#1146 Update comment and tweak retries count
  .cirrus.yml
  tool/build_check_deploy.sh
Labels: cla: yes

#1142 Added LinearLayout Article Link
  flutter-for-android.md
Labels: cla: yes

#1153 20471 fill out cupertino dialog images. Optimized PNGs.
  images/widget-catalog/cupertino-alert-dialog.png
  images/widget-catalog/cupertino-dialog-action.png
  images/widget-catalog/cupertino-dialog.png
Labels: cla: yes

#1158 Added Sketch file that contains a few Cupertino widget catalog images.
  _diagrams/widget-catalog/cupertino_screenshots.sketch
Labels: cla: yes

#1128 Integration testing recipes
  Rakefile
  cookbook/index.md
  cookbook/testing/integration-test-introduction.md
  cookbook/testing/integration-test-profiling.md
  cookbook/testing/integration-test-scrolling.md
Labels: cla: yes

#1156 Fix #1152
  android-release-build.md
Labels: cla: yes

#1161 chore: tweak config and update setup instructions
  Gemfile
  Gemfile.lock
  README.md
  _config.yml
  tool/serve.sh
Labels: Infrastructure, cla: yes

#1167 README.md: fix step numbering
  README.md
Labels: cla: yes

#1168 chore: Jekyll config and site head cleanup
  _config.yml
  _includes/footer.html
  _includes/head.html
  _plugins/regex_replace_filter.rb
  design-principles.md
  faq.md
  get-started/learn-more.md
Labels: Infrastructure, cla: yes

#1178 Fix broken links caused by src/ dir move in 4ed3f9f from #1169
  src/_layouts/page.html
  src/animations/hero-animations/index.md
  src/animations/staggered-animations/index.md
  src/cookbook/images/cached-images.md
  src/cookbook/images/fading-in-images.md
  src/cookbook/images/network-image.md
  src/cookbook/navigation/hero-animations.md
  src/design-principles.md
  src/tutorials/animation/index.md
  src/tutorials/interactive/index.md
  src/tutorials/international/index.md
  src/tutorials/layout/index.md
Labels: cla: yes

#1180 Fix spelling of fastlane
  src/fastlane.md
Labels: cla: yes

#1181 Clarify what each of the two rows are in the perf overlay
  src/ui-performance/index.md
Labels: cla: yes

#1187 Fix letter capitalization
  src/flutter-for-xamarin-forms.md
Labels: cla: yes

#1197 Fix error in Dockerfile, Fix build due to Flutter beta release.
  .cirrus.yml
  example/pubspec.yaml
  pubspec.yaml
  src/cookbook/forms/validation.md
  src/cookbook/gestures/dismissible.md
  src/cookbook/gestures/ripples.md
  src/cookbook/networking/authenticated-requests.md
  src/cookbook/persistence/key-value.md
  tool/docker/Dockerfile
Labels: cla: yes

#1203 chore: reinstate Travis builds
  .firebaserc
  .gitignore
  .travis.yml
  example/pubspec.yaml
  tool/before_install.sh
  tool/check-examples.sh
  tool/deploy-firebase.sh
Labels: Infrastructure, cla: yes

#1199 Use jekyll-assets 3 and Bootstrap 3
  _config_now.yml
  src/_assets/css/_archive.scss
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_catalog.scss
  src/_assets/css/_code_pre.scss
  src/_assets/css/_customstyles.scss
  src/_assets/css/_fix_custom_search_results.scss
  src/_assets/css/_header.scss
  src/_assets/css/_homepage.scss
  src/_assets/css/_layout.scss
  src/_assets/css/_prism.scss
  src/_assets/css/_prism_overrides.scss
  src/_assets/css/_responsive_embeds.scss
  src/_assets/css/_showcase.scss
  src/_assets/css/_sidebar.scss
  src/_assets/css/_tabs.scss
  src/_assets/css/_tutorial.scss
  src/_assets/css/lavish-bootstrap.css
  src/_assets/css/main.scss
  src/_assets/css/two_column.css
  src/_assets/js/main.js
  src/_assets/js/vendor/jquery-3.3.1.js
  src/_includes/head.html
  src/_plugins/load-bootstrap-sass.rb
  src/css/fonts/FontAwesome.otf
  src/css/fonts/fontawesome-webfont.eot
  src/css/fonts/fontawesome-webfont.svg
  src/css/fonts/fontawesome-webfont.ttf
  src/css/fonts/fontawesome-webfont.woff
  src/css/fonts/fontawesome-webfont.woff2
  src/web-analogs.md
  tool/docker/Gemfile
  tool/docker/Gemfile.lock
Labels: Infrastructure, cla: yes

#1191 Fixing some typos and removing references to "checked mode"
  .firebaserc
  src/debugging.md
  src/flutter-for-ios.md
  src/flutter-for-react-native/index.md
  src/get-started/codelab/index.md
  src/layout.md
Labels: cla: yes

#1209 Migrate to bootstrap 4
  _config.yml
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_catalog.scss
  src/_assets/css/_customstyles.scss
  src/_assets/css/_icons.scss
  src/_assets/css/_layout.scss
  src/_assets/css/_legacy.scss
  src/_assets/css/lavish-bootstrap.css
  src/_assets/css/main.scss
  src/_assets/js/main.js
  src/_includes/footer.html
  src/_includes/head.html
  src/_includes/header.html
  src/_includes/main-nav.html
  src/_includes/sidebar.html
  src/_layouts/default.html
  src/_layouts/page.html
  src/_layouts/tutorial.html
  src/_plugins/load-bootstrap-sass.rb
  src/catalog/samples/AnimatedListState_index.md
  src/catalog/samples/AnimatedList_index.md
  src/catalog/samples/AppBar_index.md
  src/catalog/samples/DefaultTabController_index.md
  src/catalog/samples/ExpansionTile_index.md
  src/catalog/samples/IconButton_index.md
  src/catalog/samples/ListView_index.md
  src/catalog/samples/PopupMenuButton_index.md
  src/catalog/samples/PreferredSize_index.md
  src/catalog/samples/Scaffold_index.md
  src/catalog/samples/TabBarView_index.md
  src/catalog/samples/TabBar_index.md
  src/catalog/samples/TabController_index.md
  src/catalog/samples/animated_list.md
  src/catalog/samples/app_bar_bottom.md
  src/catalog/samples/basic_app_bar.md
  src/catalog/samples/expansion_tile_sample.md
  src/catalog/samples/index.md
  src/catalog/samples/tabbed_app_bar.md
  src/showcase/index.md
  src/tutorials/layout/index.md
  tool/docker/Gemfile
  tool/docker/Gemfile.lock
Labels: Infrastructure, cla: yes

#1211 Fix Travis deploy
  .travis.yml
  Rakefile
  tool/deploy-firebase.sh
Labels: Infrastructure, cla: yes

#1212 Deploy script tweaks, reinstate deploy
  .travis.yml
  tool/deploy.sh
Labels: Infrastructure, cla: yes

#1215 Disable page edit button
  .gitignore
  src/_assets/css/_base.scss
  src/_layouts/page.html
Labels: cla: yes
