Repository flutter/website, pull requests merged in 2018-09, with the labels that each got.

#1220 Set cursor for main nav dropdown
  .travis.yml
  src/_assets/css/_layout.scss
Labels: cla: yes

#1224 [dash] Minimal CSS and JS setup to use bootstrap as a base
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/main.scss
  src/_assets_old/css/_archive.scss
  src/_assets_old/css/_base.scss
  src/_assets_old/css/_bootstrap_config.scss
  src/_assets_old/css/_catalog.scss
  src/_assets_old/css/_code_pre.scss
  src/_assets_old/css/_customstyles.scss
  src/_assets_old/css/_fix_custom_search_results.scss
  src/_assets_old/css/_header.scss
  src/_assets_old/css/_homepage.scss
  src/_assets_old/css/_icons.scss
  src/_assets_old/css/_layout.scss
  src/_assets_old/css/_legacy.scss
  src/_assets_old/css/_prism.scss
  src/_assets_old/css/_prism_overrides.scss
  src/_assets_old/css/_responsive_embeds.scss
  src/_assets_old/css/_showcase.scss
  src/_assets_old/css/_sidebar.scss
  src/_assets_old/css/_tabs.scss
  src/_assets_old/css/_tutorial.scss
  src/_assets_old/css/main.scss
  src/_assets_old/css/two_column.css
  src/_assets_old/js/archive.js
  src/_assets_old/js/customscripts.js
  src/_assets_old/js/prism.js
  src/_assets_old/js/sidebar_toggle.js
  src/_assets_old/js/tabs.js
  src/_includes/head.html
  src/_layouts/default.html
  src/_layouts/page.html
  src/web-analogs.md
Labels: cla: yes

#1233 [dash] Initial layout for navbar
  src/_includes/header.html
  src/_includes/main-nav.html
Labels: cla: yes

#1232 [dash] Moved the "Flutter for" articles to the new IA location.
  src/_data/side-nav.yml
  src/docs.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/ios-devs.md
  src/get-started/flutter-for/react-native-devs/images/2e973d40d6e82114.png
  src/get-started/flutter-for/react-native-devs/images/6b18b6e158b15685.png
  src/get-started/flutter-for/react-native-devs/images/android.png
  src/get-started/flutter-for/react-native-devs/images/api_calls_android.gif
  src/get-started/flutter-for/react-native-devs/images/api_calls_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/basic_layout_android.gif
  src/get-started/flutter-for/react-native-devs/images/basic_layout_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/canvas_android.png
  src/get-started/flutter-for/react-native-devs/images/canvas_iOS.png
  src/get-started/flutter-for/react-native-devs/images/card_swipe_android.gif
  src/get-started/flutter-for/react-native-devs/images/card_swipe_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/flatlist_android.gif
  src/get-started/flutter-for/react-native-devs/images/flatlist_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/flutter_fade_android.gif
  src/get-started/flutter-for/react-native-devs/images/flutter_fade_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/flutter_gestures_android.gif
  src/get-started/flutter-for/react-native-devs/images/flutter_gestures_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/flutterstyling_android.gif
  src/get-started/flutter-for/react-native-devs/images/flutterstyling_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/hello_world_basic_android.png
  src/get-started/flutter-for/react-native-devs/images/hello_world_basic_iOS.png
  src/get-started/flutter-for/react-native-devs/images/iOS.png
  src/get-started/flutter-for/react-native-devs/images/input_fields_android.gif
  src/get-started/flutter-for/react-native-devs/images/input_fields_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/modular_android.png
  src/get-started/flutter-for/react-native-devs/images/modular_iOS.png
  src/get-started/flutter-for/react-native-devs/images/navigation_android.gif
  src/get-started/flutter-for/react-native-devs/images/navigation_iOS.gif
  src/get-started/flutter-for/react-native-devs/images/stack_android.png
  src/get-started/flutter-for/react-native-devs/images/stack_iOS.png
  src/get-started/flutter-for/react-native-devs/images/state_change_android.gif
  src/get-started/flutter-for/react-native-devs/images/state_change_iOS.gif
  src/get-started/flutter-for/react-native-devs/index.md
  src/get-started/flutter-for/web-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/get-started/learn-more.md
Labels: cla: yes

#1236 [dash] Reinstate autodeploy, disable check-links only
  .travis.yml
  Rakefile
  tool/before_install.sh
  tool/build_check_deploy.sh
Labels: Infrastructure, cla: yes

#1237 [dash] Travis: use `language:dart`, reinstate link checking
  .gitignore
  .travis.yml
  README.md
  example/analysis_options.yaml
  example/pubspec.yaml
  package.json
  pubspec.lock
  pubspec.yaml
  src/_includes/code/layout/main.dart
  tool/before_install.sh
  tool/build_check_deploy.sh
  tool/check-links.sh
  tool/config/linkcheck-skip-list.txt
  tool/deploy.sh
  tool/env-set.sh
  tool/install.sh
  tool/serve.sh
  tool/shared/env-set.sh
  tool/shared/get-ruby.sh
Labels: cla: yes, infrastructure

#1244 [dash] A little help for zsh users, and ensure bundle install is always run
  tool/before_install.sh
  tool/install.sh
  tool/shared/env-set.sh
Labels: cla: yes, infrastructure

#1240 [dash] Renaming files, fixing broken links
  _includes/code/layout/lakes/pubspec.lock
  src/_data/catalog/widgets.json
  src/_includes/sidebar.html
  src/catalog/samples/AnimatedList.md
  src/catalog/samples/AnimatedListState.md
  src/catalog/samples/AppBar.md
  src/catalog/samples/DefaultTabController.md
  src/catalog/samples/ExpansionTile.md
  src/catalog/samples/IconButton.md
  src/catalog/samples/ListView.md
  src/catalog/samples/PopupMenuButton.md
  src/catalog/samples/PreferredSize.md
  src/catalog/samples/Scaffold.md
  src/catalog/samples/TabBar.md
  src/catalog/samples/TabBarView.md
  src/catalog/samples/TabController.md
  src/catalog/samples/animated-list.md
  src/catalog/samples/app-bar-bottom.md
  src/catalog/samples/basic-app-bar.md
  src/catalog/samples/expansion-tile-sample.md
  src/catalog/samples/index.md
  src/catalog/samples/tabbed-app-bar.md
  src/developing-packages.md
  src/docs.md
  src/faq.md
  src/get-started/flutter-for/ios-devs.md
  src/get-started/flutter-for/react-native-devs/index.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/get-started/learn-more.md
  src/get-started/test-drive.md
  src/index.md
  src/tutorials/layout/index.md
  src/using-packages.md
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#1242 [dash] Adds default and landing layouts
  src/_includes/sidebar.html
  src/_includes/toc.html
  src/_layouts/base.html
  src/_layouts/default.html
  src/_layouts/landing.html
  src/_layouts/page.html
  src/index.md
Labels: cla: yes

#1247 i18n: Add iOS-specific instructions
  src/tutorials/internationalization.md
Labels: cla: yes

#1246 i18n: Add iOS-specific instructions
  src/tutorials/international/index.md
Labels: cla: yes

#1258 [dash] Add base styles for doc pages
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_content.scss
  src/_assets/css/_header.scss
  src/_assets/css/_sidebar.scss
  src/_assets/css/_toc.scss
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
  src/_includes/head.html
  src/_includes/header.html
  src/_includes/toc.html
  src/_layouts/default.html
Labels: cla: yes

#1260 [dash] Use jekyll-toc for auto-TOC generation; docs page cleanup
  _config.yml
  src/_includes/toc.html
  src/docs.md
  src/get-started/codelab/index.md
  tool/config/linkcheck-skip-list.txt
  tool/docker/Gemfile
  tool/docker/Gemfile.lock
Labels: cla: yes, infrastructure

#1261 [dash] Fix some TOC-related missing anchor issues
  _config.yml
  src/_includes/toc.html
  src/showcase/index.md
  src/tools/using-ide.md
  src/ui-performance/index.md
  src/using-packages.md
  src/widgets-intro.md
  src/widgets.md
  src/widgets/assets.md
Labels: cla: yes

#1265 [dash] Drop tutorial.html layout
  src/_layouts/tutorial.html
  src/development/ui/interactive/index.md
  src/get-started/codelab/index.md
  src/tutorials/internationalization.md
Labels: cla: yes

#1266 [dash] Drop jekyll-redirect-from gem in favor of Firebase redirect rules
  _config.yml
  firebase.json
  src/research-optout.md
  src/research-signup.md
  tool/docker/Gemfile
  tool/docker/Gemfile.lock
Labels: cla: yes, infrastructure

#1267 [dash] Refine style for navbar and sidebar
  src/_assets/css/_base.scss
  src/_assets/css/_content.scss
  src/_assets/css/_header.scss
  src/_assets/css/_sidebar.scss
  src/_assets/css/_toc.scss
  src/_assets/css/_variables.scss
  src/_includes/head.html
  src/_includes/header.html
  src/_includes/sidebar.html
  src/_includes/toc.html
  src/_layouts/default.html
Labels: cla: yes

#1270 [dash] "Get Started: Install" page edits and markdown cleanup
  _config.yml
  src/_includes/note.html
  src/get-started/install.md
Labels: cla: yes

#1268 [dash] Adds barebones footer to the site
  src/_assets/css/_footer.scss
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
  src/_includes/footer.html
Labels: cla: yes

#1271 [dash] Added side- and inlined-TOC styling and scroll spy
  README.md
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_content.scss
  src/_assets/css/_toc.scss
  src/_assets/css/main.scss
  src/_assets/js/main.js
  src/_includes/toc.html
  src/_layouts/default.html
Labels: cla: yes

#1274 [dash] Adds mobile nav as a side-drawer
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_footer.scss
  src/_assets/css/_header.scss
  src/_assets/css/_sidebar.scss
  src/_assets/css/_toc.scss
  src/_assets/css/_variables.scss
  src/_includes/header.html
  src/_layouts/default.html
Labels: cla: yes

#1284 Update to RP2
  src/index.md
Labels: cla: yes

#1286 [dash] jekyll-toc gem ref adjustment
  tool/docker/Gemfile
  tool/docker/Gemfile.lock
Labels: cla: yes, infrastructure

#1285 [dash] Refactoring sass var names to ‘site’ prefix
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_content.scss
  src/_assets/css/_footer.scss
  src/_assets/css/_header.scss
  src/_assets/css/_sidebar.scss
  src/_assets/css/_toc.scss
  src/_assets/css/_variables.scss
Labels: cla: yes

#1287 [dash] Fix sidebar and toc scrolling issues
  src/_assets/css/_base.scss
  src/_assets/css/_footer.scss
  src/_assets/css/_sidebar.scss
  src/_assets/css/_toc.scss
  src/_assets/css/_variables.scss
  src/_assets/js/main.js
  src/_includes/toc.html
  src/_layouts/default.html
Labels: cla: yes

#1278 Update "Google AdWords" in showcase per rebrand
  src/_data/showcases.yml
Labels: cla: yes

#1288 [dash] Updates styles for /docs landing page
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_content.scss
  src/docs.md
Labels: cla: yes

#1305 [dash] Fix broken links
  src/get-started/codelab.md
Labels: cla: yes

#1307 [dash] Drop src/get-started/index.md
  firebase.json
  src/get-started/index.md
Labels: cla: yes

#1308 [dash] Hide TOC page-top button
  src/_assets/css/_site_overrides.scss
  src/_assets/css/main.scss
Labels: cla: yes

#1189 Update starter Android app screenshot image
  src/images/flutter-starter-app-android.png
Labels: cla: yes

#1311 Fixing a couple issues filed against master.
  README.md
  src/cookbook/networking/fetch-data.md
  src/images/flutter-starter-app-android.png
Labels: cla: yes

#1309 [dash] Make a.card style more closely match a plain `<a>` element style
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_adjust.scss
Labels: cla: yes

#1313 [dash] Add 3 more cupertino widgets to the catalog
  src/_data/catalog/widgets.json
  src/images/widget-catalog/cupertino-action-sheet.png
  src/images/widget-catalog/cupertino-segmented-control.png
  src/images/widget-catalog/cupertino-timer-picker.png
Labels: cla: yes

#1312 [dash] Initial cleanup of OS install pages
  src/_assets/css/_code-highlight.scss
  src/_assets/css/_site_overrides.scss
  src/_assets/css/main.scss
  src/_assets/js/archive.js
  src/_assets/js/main.js
  src/_includes/head.html
  src/_includes/setup/android-setup.md
  src/_includes/setup/get-sdk-win.md
  src/_includes/setup/get-sdk.md
  src/_includes/setup/ios-setup.md
  src/_includes/setup/path-mac-linux.md
  src/_includes/setup/system-linux.md
  src/_includes/setup/system-mac.md
  src/_includes/setup/system-win.md
  src/_plugins/prettify.rb
  src/development/ui/interactive/index.md
  src/get-started/codelab.md
  src/get-started/install/_analytics.md
  src/get-started/install/_android-setup.md
  src/get-started/install/_get-sdk-win.md
  src/get-started/install/_get-sdk.md
  src/get-started/install/_ios-setup.md
  src/get-started/install/_path-mac-linux.md
  src/get-started/install/index.md
  src/get-started/install/linux.md
  src/get-started/install/macos.md
  src/get-started/install/windows.md
  src/get-started/setup-linux.md
  src/get-started/setup-macos.md
  src/get-started/setup-windows.md
Labels: cla: yes

#1314 Updates ‘Getting started’ pages styles
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_variables.scss
  src/_includes/head.html
  src/get-started/_android-ios-figure-pair.md
  src/get-started/_app-figure.md
  src/get-started/codelab.md
Labels: cla: yes

#1320 [dash] Style side TOC
  src/_assets/css/_toc.scss
  src/_assets/js/main.js
  src/_includes/toc.html
Labels: cla: yes

#1319 [dash] removing white background for highlight
  src/_assets/css/_code-highlight.scss
Labels: cla: yes

#1326 [dash] Support show/hide of Get Started button per page
  src/_includes/header.html
  src/_layouts/landing.html
Labels: cla: yes, infrastructure

#1329 [dash] Addresses part of #1323
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_content.scss
  src/_assets/css/_toc.scss
  src/_assets/css/_variables.scss
  src/_includes/head.html
  src/_layouts/default.html
Labels: cla: yes

#1331 [dash] Improve syntax highlighting colors, other misc followup tweaks
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_code_pre.scss
  src/_assets/css/_material_colors.scss
  src/_assets/css/_pygments-bg-dark.scss
  src/_assets/css/_pygments-bg-light.scss
  src/_assets/css/_toc.scss
  src/_assets/css/main.scss
  src/_layouts/default.html
Labels: cla: yes

#1302 Add 3 more cupertino widgets to the catalog
  src/_data/catalog/widgets.json
  src/images/widget-catalog/cupertino-action-sheet.png
  src/images/widget-catalog/cupertino-segmented-control.png
  src/images/widget-catalog/cupertino-timer-picker.png
Labels: cla: yes

#1339 [dash] Sidenav from yaml, iteration 1
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_sidebar.scss
  src/_data/side-nav.yml
  src/_includes/header.html
  src/_includes/sidebar.html
  src/_layouts/default.html
Labels: cla: yes

#1341 [dash] Drop manually inserted TOCs; copyedits and markdown cleanup
  README.md
  firebase.json
  src/_data/side-nav.yml
  src/accessibility/index.md
  src/accessibility/internationalization.md
  src/deployment/android-release.md
  src/deployment/fastlane-cd.md
  src/deployment/ios-release.md
  src/development/data-and-backend/json.md
  src/development/packages-and-plugins/developing-packages.md
  src/development/packages-and-plugins/using-packages.md
  src/development/platform-integration/platform-channels.md
  src/development/tools/formatting.md
  src/development/tools/hot-reload.md
  src/development/tools/inspector.md
  src/development/tools/using-ide/index.md
  src/development/tools/using-ide/vscode.md
  src/development/ui/advanced/gestures.md
  src/development/ui/animations/hero-animations/index.md
  src/development/ui/animations/index.md
  src/development/ui/animations/overview.md
  src/development/ui/animations/staggered-animations/index.md
  src/development/ui/assets-and-images.md
  src/development/ui/interactive/index.md
  src/development/ui/layout/box-constraints.md
  src/development/ui/layout/index.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/ios-devs.md
  src/get-started/flutter-for/react-native-devs/index.md
  src/get-started/flutter-for/web-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/get-started/learn-more.md
  src/resources/bug-reports.md
  src/resources/design-principles.md
  src/resources/faq.md
  src/resources/rendering.md
  src/resources/videos.md
  src/testing/debugging.md
  src/testing/index.md
Labels: cla: yes

#1330 [dash] Adding a page on Flutter's compile modes.
  src/testing/building-apps.md
  src/testing/index.md
Labels: cla: yes

#1243 [dash] Make Swift code look more idiomatic
  src/development/platform-integration/platform-channels.md
Labels: cla: yes

#1344 Update minimal APK size on dash
  src/resources/faq.md
Labels: cla: yes

#1343 Update minimal APK size
  src/faq.md
Labels: cla: yes
