Repository flutter/website, pull requests merged in 2018-10, with the labels that each got.

#1345 [dash] Homepage content refactor
  src/index.md
Labels: cla: yes

#1349 [dash] Changed "fat arrow" to "arrow".
  src/get-started/codelab.md
Labels: cla: yes

#1350 [dash] Initial port of prev/next subnav, added to top & bottom on page
  src/_assets/css/_next-prev-nav.scss
  src/_assets/css/main.scss
  src/_includes/next-prev-nav.html
  src/_layouts/default.html
  src/get-started/codelab.md
  src/get-started/editor.md
  src/get-started/install/index.md
  src/get-started/learn-more.md
  src/get-started/test-drive.md
Labels: cla: yes

#1353 [dash] Update text of security policy, based on group feedback.
  src/security.md
Labels: cla: yes

#1359 chore: .gitignore dash files
  .gitignore
Labels: cla: yes

#1364 Improve contrast of "Latest release" tag line
  .firebaserc
  src/_assets/css/_homepage.scss
Labels: cla: yes, design

#1367 [dash] Add banner to non-landing pages
  .firebaserc
  _config.yml
  src/_includes/banner.html
  src/_layouts/default.html
Labels: cla: yes

#1362 [dash] Fixes #1336 -- Removing the listener twice
  src/cookbook/forms/text-field-changes.md
Labels: cla: yes

#1358 Fixing a number of little issues.
  src/_data/side-nav.yml
  src/_includes/footer.html
  src/deployment/android-release.md
  src/development/tools/upgrading.md
  src/development/tools/using-ide/index.md
  src/development/ui/animations/index.md
  src/resources/design-principles.md
  src/resources/rendering.md
  src/security.md
Labels: cla: yes

#1372 [dash] Get started: adjust titles
  src/_data/side-nav.yml
  src/get-started/codelab.md
  src/get-started/editor.md
  src/get-started/install/index.md
  src/get-started/install/linux.md
  src/get-started/install/macos.md
  src/get-started/install/windows.md
  src/get-started/learn-more.md
  src/get-started/test-drive.md
Labels: cla: yes

#1373 [dash] Progress on landing page styles
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_header.scss
  src/_assets/css/_homepage.scss
  src/_assets/css/main.scss
  src/_includes/head.html
  src/_layouts/base.html
  src/images/homepage/news-1.png
  src/images/homepage/news-2.png
  src/images/homepage/platform-parity.png
  src/images/homepage/reflectly.png
  src/images/icon-development.svg
  src/images/icon-performance.svg
  src/images/icon-ui.svg
  src/index.md
Labels: cla: yes

#1375 [dash] Add homepage banner
  _config.yml
  src/_assets/css/_homepage.scss
  src/_includes/banner.html
  src/index.md
Labels: cla: yes

#1378 [dash] cookbook/testing: source file reorg before adding next/prev links
  _config.yml
  src/cookbook/index.md
  src/cookbook/networking/fetch-data.md
  src/cookbook/testing/integration/index.md
  src/cookbook/testing/integration/profiling.md
  src/cookbook/testing/integration/scrolling.md
  src/cookbook/testing/unit/index.md
  src/cookbook/testing/unit/mocking.md
  src/cookbook/testing/widget/finders.md
  src/cookbook/testing/widget/index.md
  src/cookbook/testing/widget/tap-drag.md
Labels: cla: yes

#1374 Adding Inside Flutter page for a deep dive on Flutter internals.
  src/_data/side-nav.yml
  src/resources/inside-flutter.md
Labels: cla: yes

#1383 Fix a typo in class name
  src/get-started/codelab.md
Labels: cla: yes

#1382 Fixes #1380: Align Focus recipe with focus api docs.
  src/cookbook/forms/focus.md
Labels: cla: yes

#1389 [dash] Refactor testing/debugging* pages and fix broken links
  src/_assets/image/testing/debugging/oem/android-debugger.png
  src/_assets/image/testing/debugging/oem/attach-process-button.png
  src/_assets/image/testing/debugging/oem/choose-process-dialog.png
  src/_assets/image/testing/debugging/oem/dart-debugger.png
  src/_assets/image/testing/debugging/oem/debug-pane-action.png
  src/_assets/image/testing/debugging/oem/debug-pane.png
  src/_assets/image/testing/debugging/oem/debug-run.png
  src/_assets/image/testing/debugging/oem/flutter-inspector.png
  src/_assets/image/testing/debugging/oem/flutter-outline.png
  src/_assets/image/testing/debugging/oem/hot-reload-button.png
  src/_assets/image/testing/debugging/oem/launch-flutter-io.png
  src/_assets/image/testing/debugging/oem/moto-g-process.png
  src/_assets/image/testing/debugging/oem/presentation-assistant-find-pane.png
  src/_assets/image/testing/debugging/oem/presentation-assistant-search-results.png
  src/_assets/image/testing/debugging/oem/presentation-assistant-teaches.png
  src/_data/side-nav.yml
  src/testing/debugging/index.md
  src/testing/debugging/oem.md
Labels: cla: yes

#1393 [dash] Make OEM debuggers a level-3 entry in the sidenav
  src/_data/side-nav.yml
Labels: cla: yes

#1401 [dash] Main nav adjustments following 2018/10/05 meeting
  src/_includes/header.html
  src/_layouts/landing.html
  src/showcase/index.md
Labels: cla: yes

#1399 [dash] Enable old custom tabs and use BS tabs for "Set up an editor" page
  src/_assets/css/_tabs.scss
  src/_assets/css/main.scss
  src/_assets/js/main.js
  src/_assets/js/tabs.js
  src/_data/side-nav.yml
  src/get-started/editor.md
  src/get-started/test-drive.md
Labels: cla: yes

#1387 Progress on homepage styling
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_homepage.scss
  src/_assets/image/homepage/hot-reload.gif
  src/_assets/image/homepage/icon-development.svg
  src/_assets/image/homepage/icon-performance.svg
  src/_assets/image/homepage/icon-ui.svg
  src/_assets/image/homepage/logo-abbey_road_studios.png
  src/_assets/image/homepage/logo-alibaba.png
  src/_assets/image/homepage/logo-google.svg
  src/_assets/image/homepage/logo-google_adwords.png
  src/_assets/image/homepage/logo-groupon.png
  src/_assets/image/homepage/logo-hamilton.png
  src/_assets/image/homepage/logo-tencent.png
  src/_assets/image/homepage/platform-parity.png
  src/_assets/image/homepage/reflectly.png
  src/images/icon-development.svg
  src/images/icon-performance.svg
  src/images/icon-ui.svg
  src/index.md
Labels: cla: yes

#1409 [dash] Use "Set up an editor" in next/prev links
  src/get-started/install/index.md
  src/get-started/install/linux.md
  src/get-started/install/macos.md
  src/get-started/install/windows.md
  src/get-started/test-drive.md
Labels: cla: yes

#1408 Initial style for Showcase page
  src/_assets/css/_base.scss
  src/_assets/css/_homepage.scss
  src/_assets/css/_landing-page.scss
  src/_assets/css/_showcase.scss
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
  src/index.md
  src/showcase/index.md
Labels: cla: yes

#1411 Fix broken link to template file
  src/technical-overview.md
Labels: cla: yes

#1415 [dash] Use query parameter to encode selected editor
  src/_assets/js/tabs.js
Labels: cla: yes, infrastructure

#1417 [dash] Get started / Test drive: cleanup, refactoring and use of BS tabs
  src/get-started/test-drive.md
  src/get-started/test-drive/_androidstudio.md
  src/get-started/test-drive/_terminal.md
  src/get-started/test-drive/_try-hot-reload.md
  src/get-started/test-drive/_vscode.md
  src/get-started/test-drive/index.md
Labels: cla: yes

#1426 [dash] Sidenav: have API and Development entries expanded by default
  src/_data/side-nav.yml
  src/_includes/sidebar.html
Labels: cla: yes, infrastructure

#1427 [dash] By default collapse sidenav level 2 entries with children
  src/_data/side-nav.yml
  src/_includes/sidebar.html
Labels: cla: yes, infrastructure

#1429 [dash] Support proper active-entry status-indicator for all sidenav entries
  src/_assets/css/_base.scss
  src/_assets/css/_sidebar.scss
  src/_data/side-nav.yml
  src/_includes/sidebar.html
  src/_plugins/sidenav-active-entry-filter.rb
  src/testing/debugging.md
  src/testing/oem-debuggers.md
Labels: cla: yes

#1430 Fix build by temporarily ignoring analyzer issue when checking example code
  src/_includes/code/animation/radial_hero_animation_animate_rectclip/main.dart
  tool/serve.sh
Labels: P1, cla: yes, examples

#1431 Change .lerp to .transform in code example
  src/_includes/code/animation/radial_hero_animation_animate_rectclip/main.dart
Labels: cla: yes

#1432 Change `tween.lerp()` to `tween.transform()`
  src/_includes/code/animation/radial_hero_animation_animate_rectclip/main.dart
Labels: cla: yes

#1421 Misc updates to navbar and homepage
  src/_assets/css/_base.scss
  src/_assets/css/_header.scss
  src/_assets/css/_homepage.scss
  src/_assets/css/_landing-page.scss
  src/_assets/css/_sidebar.scss
  src/_assets/image/flutter-lockup.svg
  src/_assets/image/flutter-lockup_w_tagline.svg
  src/_assets/image/homepage/logo-abbey_road_studios.png
  src/_assets/image/homepage/logo-hamilton.png
  src/_includes/header.html
  src/index.md
Labels: cla: yes

#1434 [dash] Visually distinguish active main nav entries
  src/_assets/css/_header.scss
  src/_includes/header.html
Labels: cla: yes

#1436 [dash] Use cards for each OS on Install page
  src/_assets/css/_base.scss
  src/get-started/install/index.md
Labels: cla: yes

#1406 [dash] Adding a placeholder page for bgnd processes, and a "What's new" section
  src/_data/side-nav.yml
  src/development/packages-and-plugins/background-processes.md
  src/development/packages-and-plugins/developing-packages.md
  src/development/packages-and-plugins/using-packages.md
  src/docs.md
  src/testing/build-modes.md
Labels: cla: yes

#1439 Update Showcase page style
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_landing-page.scss
  src/_assets/css/_showcase.scss
  src/_assets/image/showcase/hero-hamilton.jpg
  src/_assets/image/showcase/logo-abbey_road_studios.png
  src/_assets/image/showcase/logo-alibaba.png
  src/_assets/image/showcase/logo-app_tree.png
  src/_assets/image/showcase/logo-google_adwords.png
  src/_assets/image/showcase/logo-hamilton.png
  src/_assets/image/showcase/logo-reflectly.png
  src/_assets/image/showcase/logo-tencent.png
  src/_data/showcases.yml
  src/showcase/index.md
Labels: cla: yes

#1394 [dash] Cleaned up the oem page markdown, and added remaining Inside Flutter text
  src/resources/inside-flutter.md
  src/testing/oem-debuggers.md
Labels: cla: yes

#1445 [dash] sidenav plugin fix and file name adjustment
  src/_data/sidenav.yml
  src/_includes/header.html
  src/_includes/sidenav.html
  src/_layouts/default.html
  src/_plugins/sidenav-active-entry-filter.rb
Labels: cla: yes, infrastructure

#1449 Fixes for demo
  src/_assets/css/_header.scss
  src/_assets/css/_homepage.scss
  src/_assets/image/homepage/logo-abbey_road_studios.png
  src/_assets/image/homepage/logo-hamilton.png
  src/_assets/image/homepage/news-1.png
  src/_assets/image/homepage/news-2.png
  src/images/homepage/news-1.png
  src/images/homepage/news-2.png
  src/index.md
Labels: cla: yes

#1447 [dash] "Get started > Test drive": copyedits and figure fix
  src/_assets/image/get-started/android/starter-app.png
  src/_assets/image/get-started/ios/starter-app.png
  src/_includes/app-figure.md
  src/get-started/_android-ios-figure-pair.md
  src/get-started/codelab.md
  src/get-started/editor.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/ios-devs.md
  src/get-started/flutter-for/react-native-devs/index.md
  src/get-started/flutter-for/web-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/get-started/learn-more.md
  src/get-started/test-drive/_androidstudio.md
  src/get-started/test-drive/_terminal.md
  src/get-started/test-drive/_try-hot-reload.md
  src/get-started/test-drive/_vscode.md
  src/get-started/test-drive/index.md
  src/images/flutter-starter-app-ios.png
Labels: cla: yes

#1453 Styles breadcrumbs
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_content.scss
  src/_layouts/default.html
Labels: cla: yes

#1454 [dash] Implement carets for 2nd level entries with subentries
  src/_assets/css/_sidebar.scss
  src/_includes/sidenav.html
Labels: cla: yes, design

#1455 [dash] Keep widget catalog under /development/ui; move index under "APIs & references"
  _config.yml
  src/_data/docs_cards.yml
  src/_data/sidenav.yml
  src/_includes/catalogpage.html
  src/api-and-reference/widgets/accessibility.md
  src/api-and-reference/widgets/animation.md
  src/api-and-reference/widgets/assets.md
  src/api-and-reference/widgets/async.md
  src/api-and-reference/widgets/basics.md
  src/api-and-reference/widgets/cupertino.md
  src/api-and-reference/widgets/index.md
  src/api-and-reference/widgets/input.md
  src/api-and-reference/widgets/interaction.md
  src/api-and-reference/widgets/layout.md
  src/api-and-reference/widgets/material.md
  src/api-and-reference/widgets/painting.md
  src/api-and-reference/widgets/scrolling.md
  src/api-and-reference/widgets/styling.md
  src/api-and-reference/widgets/text.md
  src/development/ui/animations/index.md
  src/development/ui/layout/index.md
  src/development/ui/widgets-catalog.md
  src/development/ui/widgets-intro.md
  src/development/ui/widgets/widgetindex.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/ios-devs.md
  src/get-started/flutter-for/react-native-devs/index.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/index.md
  src/resources/faq.md
Labels: cla: yes

#1472 change API break label
  src/resources/design-principles.md
Labels: cla: yes

#1385 Fix docs on performance overlay
  src/testing/ui-performance/index.md
Labels: cla: yes

#1459 [dash] Updates for widgets pages
  src/_assets/css/_base.scss
  src/_assets/css/_bootstrap_adjust.scss
  src/_assets/css/_header.scss
  src/_assets/css/_showcase.scss
  src/_includes/catalogpage.html
  src/_includes/header.html
  src/_layouts/default.html
  src/api-and-reference/widgets/index.md
  src/development/ui/widgets-catalog.md
  src/showcase/index.md
Labels: cla: yes

#1480 [dash] Support level-4 entries
  src/_includes/sidenav-level-2.html
  src/_includes/sidenav-level-3.html
  src/_includes/sidenav-level-4.html
  src/_includes/sidenav.html
Labels: cla: yes, infrastructure

#1479 Add YouTube icon to the main nav
  _config.yml
  src/_assets/css/_header.scss
  src/_includes/header.html
Labels: cla: yes

#1481 Updates marketing copy for homepage and showcases
  src/_data/showcases.yml
  src/index.html
  src/showcase/index.html
Labels: cla: yes

#1482 Styles sidebar multi-level nav
  src/_assets/css/_bootstrap_config.scss
  src/_assets/css/_sidebar.scss
Labels: cla: yes

#1487 [dash] Refactor entries under Tools
  firebase.json
  src/_assets/image/tools/android-studio/assists.gif
  src/_assets/image/tools/android-studio/dart-analysis.png
  src/_assets/image/tools/android-studio/debug-panel.png
  src/_assets/image/tools/android-studio/hot-reload.gif
  src/_assets/image/tools/android-studio/inspector_select_example.gif
  src/_assets/image/tools/android-studio/keymap-settings-flutter-plugin.png
  src/_assets/image/tools/android-studio/log.png
  src/_assets/image/tools/android-studio/main-toolbar.png
  src/_assets/image/tools/android-studio/switch_inspector_tree.gif
  src/_assets/image/tools/android-studio/templates.gif
  src/_assets/image/tools/android-studio/trailing-comma-with.png
  src/_assets/image/tools/android-studio/trailing-comma-without.png
  src/_assets/image/tools/android-studio/visual-debugging.png
  src/_assets/image/tools/vs-code/assists.png
  src/_assets/image/tools/vs-code/debug_console.png
  src/_assets/image/tools/vs-code/device_status_bar.png
  src/_assets/image/tools/vs-code/problems.png
  src/_assets/image/tools/vs-code/snippets.png
  src/_data/sidenav.yml
  src/_includes/sidenav-level-2.html
  src/_includes/sidenav-level-3.html
  src/_includes/sidenav-level-4.html
  src/development/tools/formatting.md
  src/development/tools/hot-reload.md
  src/development/tools/ide/android-studio.md
  src/development/tools/ide/vs-code.md
  src/development/tools/inspector.md
  src/development/tools/sdk/_sdk-archive-master.md
  src/development/tools/sdk/archive.md
  src/development/tools/sdk/upgrading.md
  src/development/tools/using-ide/vscode.md
  src/development/ui/layout/index.md
  src/get-started/codelab.md
  src/get-started/install/_get-sdk-win.md
  src/get-started/install/_get-sdk.md
  src/get-started/test-drive/_androidstudio.md
  src/get-started/test-drive/_vscode.md
  src/resources/faq.md
  src/security.md
  src/testing/oem-debuggers.md
  src/testing/ui-performance/index.md
  tool/check-code.sh
Labels: cla: yes

#1499 Banner update
  src/_includes/banner.html
  src/animations/overview.md
Labels: cla: yes

#1502 [dash] fix deep linking to URL with fragment - compensate for top nav
  src/_assets/css/_content.scss
Labels: cla: yes

#1503 [dash] Turn on the banner and sync with changes made to master
  _config.yml
  src/_includes/banner.html
Labels: cla: yes

#1513 [dash] Add sidenav link to "Dart language overview"
  src/_data/sidenav.yml
  src/_includes/sidenav-level-2.html
  src/_includes/sidenav-level-3.html
  src/_includes/sidenav-level-4.html
  src/sitemap.xml
Labels: cla: yes

#1520 [dash] Rename path `src/api-and-reference` to `src/reference`
  _config.yml
  src/_data/sidenav.yml
  src/development/ui/animations/index.md
  src/development/ui/widget-catalog.md
  src/development/ui/widgets-intro.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/ios-devs.md
  src/get-started/flutter-for/react-native-devs/index.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/reference/widgets/accessibility.md
  src/reference/widgets/animation.md
  src/reference/widgets/assets.md
  src/reference/widgets/async.md
  src/reference/widgets/basics.md
  src/reference/widgets/cupertino.md
  src/reference/widgets/index.md
  src/reference/widgets/input.md
  src/reference/widgets/interaction.md
  src/reference/widgets/layout.md
  src/reference/widgets/material.md
  src/reference/widgets/painting.md
  src/reference/widgets/scrolling.md
  src/reference/widgets/styling.md
  src/reference/widgets/text.md
Labels: cla: yes, infrastructure

#1521 [dash] Readjust heading font sizes
  src/_assets/css/_bootstrap_config.scss
Labels: cla: yes

#1523 [dash] Gestures copyedit
  src/development/ui/advanced/gestures.md
Labels: cla: yes

#1524 [dash] Fix header clearance for dual-id cases
  src/_assets/css/_content.scss
Labels: cla: yes, infrastructure

#1525 Banner update for Flutter Live
  src/_includes/banner.html
Labels: cla: yes

#1527 [dash] Add support for heading anchors
  src/_assets/css/_content.scss
  tool/docker/Gemfile
  tool/docker/Gemfile.lock
Labels: cla: yes, infrastructure

#1534 Update APK sizes
  src/faq.md
Labels: cla: yes

#1533 Update APK sizes (dash)
  src/resources/faq.md
Labels: cla: yes

#1531 Update /json for latest release of pkg:json_serializable
  src/development/data-and-backend/json.md
  src/images/json/ide_warning.png
Labels: cla: yes

#1552 [dash] Drop duplicate sidenav entry for widget inspector
  firebase.json
  src/_data/sidenav.yml
Labels: cla: yes

#1555 Banner: Join us for Flutter Live
  src/_includes/banner.html
Labels: cla: yes

#1557 [dash] Use latest firebase-tools
  package.json
Labels: cla: yes, infrastructure

#1558 Use latest firebase-tools
  tool/deploy.sh
Labels: cla: yes, infrastructure

#1470 Fixed a slew of bugs filed against master
  src/_data/sidenav.yml
  src/deployment/android-release.md
  src/development/accessibility-and-localization/internationalization.md
  src/docs.md
  src/get-started/install/_get-sdk-win.md
  src/get-started/install/_get-sdk.md
  src/get-started/install/_path-mac-linux.md
  src/get-started/test-drive/_androidstudio.md
  src/images/whatisflutter/diagram-layercake.svg
  src/resources/technical-overview.md
Labels: cla: yes

#1538 Update scrolling.md - add "await" for driver.close
  src/cookbook/testing/integration/scrolling.md
Labels: cla: yes

#1554 Update JSON example code
  src/images/json/ide_warning.png
  src/json.md
Labels: cla: yes

#1564 [dash] Fix docs breadcrumbs after page move
  _config.yml
  src/docs/index.md
  src/docs/reference/widgets/index.md
Labels: cla: yes, infrastructure

#1581 Add survey info to banner
  src/_includes/banner.html
Labels: cla: yes

#1580 Adding a landing page for Flavors.
  src/_data/sidenav.yml
  src/docs/deployment/flavors.md
Labels: cla: yes

#1579 Incorporating Andrew's feedback on samples submenu.
  src/_data/sidenav.yml
Labels: cla: yes

#1588 [dash] Create a separate page for "Navigation & routing"
  src/_data/sidenav.yml
  src/docs/development/ui/navigation.md
Labels: cla: yes

#1578 Making widget card image clickable
  src/_includes/catalogpage.html
  src/docs/reference/widgets/index.md
Labels: cla: yes

#1582 Homepage intro card usability updates
  src/index.html
Labels: cla: yes

#1591 Fix missing search results
  src/search.html
  src/search.md
Labels: cla: yes

#1597 Breaking change announcements point to flutter-announce@
  src/design-principles.md
Labels: cla: yes

#1593 Constrain max width to 960px on docs content pages
  src/_assets/css/_content.scss
  src/_assets/css/_variables.scss
Labels: cla: yes

#1594 Removes hidden character on first news item
  src/index.html
Labels: cla: yes

#1536 Fix Android release tutorial to not break builds sans android/key.properties
  src/docs/deployment/android-release.md
Labels: cla: yes

#1600 Remove content that moved to the style guide
  src/docs/resources/design-principles.md
Labels: cla: yes

#1601 Adding a page on firebase.
  src/_data/sidenav.yml
  src/docs/development/data-and-backend/firebase.md
Labels: cla: yes

#1606 Open search results links in same tab.
  src/search.html
Labels: cla: yes

#1602 Fixes issue 1586
  src/_data/catalog/index.json
Labels: cla: yes

#1599 Updates learn more ctas for showcase apps
  src/_data/showcases.yml
  src/showcase/index.html
Labels: cla: yes

#1610 [dash] Reintroduce Tutorials index page
  src/_assets/image/ui/AnimatedBuilder-WidgetTree.png
  src/_data/sidenav.yml
  src/docs/development/ui/animations/tutorial.md
  src/docs/reference/tutorials.md
Labels: cla: yes

#1604 Moving info on China to our site.
  src/community.md
  src/community/china.md
  src/community/index.md
  src/docs/get-started/install/index.md
Labels: cla: yes

#1613 [dash] Add homepage hero carousel animation
  src/_assets/css/_homepage.scss
  src/_assets/css/_variables.scss
  src/_assets/image/homepage/carousel/phone_bezel.png
  src/_assets/image/homepage/carousel/slide_1-bg.jpg
  src/_assets/image/homepage/carousel/slide_1-layer_1.png
  src/_assets/image/homepage/carousel/slide_1-layer_2.png
  src/index.html
Labels: cla: yes

#1572 Update README.md
  README.md
Labels: cla: yes

#1622 [dash] Add state management page
  src/_data/sidenav.yml
  src/docs/development/data-and-backend/state-mgmt.md
Labels: cla: yes

#1623 [dash] Docs page copyedits from Shams
  src/docs/index.md
Labels: cla: yes

#1624 [dash] Animations: sidenav entry cleanup and page misc edits by Shams
  src/_data/sidenav.yml
  src/docs/development/ui/animations/index.md
  src/docs/development/ui/animations/overview.md
  src/docs/development/ui/animations/tutorial.md
Labels: cla: yes

#1616 [dash] Resizing some overly large pics.
  src/docs/cookbook/design/fonts.md
  src/docs/cookbook/design/snackbars.md
  src/docs/cookbook/design/themes.md
  src/images/cookbook/basic-list.png
  src/images/cookbook/drawer.png
  src/images/cookbook/fonts.png
  src/images/cookbook/mixed-list.png
  src/images/cookbook/network-image.png
  src/images/cookbook/package-fonts.png
  src/images/cookbook/themes.png
Labels: cla: yes

#1630 [dash] Firebase redirects, a few sidenav entry additions + file renames
  firebase.json
  src/_data/sidenav.yml
  src/docs/deployment/android.md
  src/docs/deployment/ios.md
  src/docs/resources/design-principles.md
  src/docs/resources/faq.md
  src/docs/testing/build-modes.md
Labels: cla: yes, infrastructure

#1629 Minor content updates for showcase page
  src/_assets/image/showcase/logo-jd.jpg
  src/_assets/image/showcase/logo-jd.png
  src/_data/showcases.yml
Labels: cla: yes

#1636 Content update for landing page carousel
  src/_assets/css/_homepage.scss
  src/_assets/image/homepage/carousel/slide_2-bg.jpg
  src/_assets/image/homepage/carousel/slide_2-layer_1.png
  src/_assets/image/homepage/carousel/slide_2-layer_2.png
  src/_assets/image/homepage/carousel/slide_3-bg.jpg
  src/_assets/image/homepage/carousel/slide_3-layer_1.png
  src/_assets/image/homepage/carousel/slide_3-layer_2.png
  src/_assets/image/homepage/carousel/slide_4-bg.jpg
  src/_assets/image/homepage/carousel/slide_4-layer_1.png
  src/_assets/image/homepage/carousel/slide_4-layer_2.png
  src/index.html
Labels: cla: yes
