Repository flutter/website, pull requests merged in 2019-11, with the labels that each got.

#3190 update test execution speed claims
  src/docs/testing/index.md
Labels: cla: yes

#3183 Fix minor typos
  src/docs/development/packages-and-plugins/developing-packages.md
Labels: cla: yes

#3185 Add implicit animations codelab to sidenav
  src/docs/codelabs/implicit-animations.md
  src/docs/codelabs/index.md
Labels: cla: yes

#3169 Assets hint
  src/docs/development/platform-integration/platform-channels.md
  src/docs/development/ui/layout/tutorial.md
  src/docs/resources/platform-adaptations.md
Labels: cla: yes

#3194 Update app-size.md
  src/docs/perf/app-size.md
Labels: cla: yes

#3196 Sliver Design Doc Link
  firebase.json
Labels: cla: yes

#3197 Update internationalization.md
  src/docs/development/accessibility-and-localization/internationalization.md
Labels: cla: yes

#3204 Add go link for Android embedding asset lookup change
  firebase.json
Labels: cla: yes

#3206 Flutter Clock Contest
  _config.yml
  src/_assets/css/_clock.scss
  src/_assets/css/_showcase.scss
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
  src/_assets/image/clock/left_rectangle.svg
  src/_assets/image/clock/oval.svg
  src/_assets/image/clock/right_rectangle.svg
  src/_assets/js/countdown.js
  src/_layouts/base.html
  src/clock/index.html
Labels: cla: yes

#3205 docs: fix typo
  src/docs/development/platform-integration/c-interop.md
Labels: cla: yes

#3207 Tweaking the banner
  src/_includes/banner.html
Labels: cla: yes

#3208 Update analytics statement
  src/docs/get-started/install/_analytics.md
Labels: cla: yes

#3214 Reflect that Flutter web is on the dev channel
  src/docs/get-started/web.md
Labels: cla: yes

#3212 Android tip for camera plugin
  src/docs/cookbook/plugins/picture-using-camera.md
Labels: cla: yes

#3215 docs: Fix typo in ui-performance.md
  src/docs/perf/rendering/ui-performance.md
Labels: cla: yes

#3217 Corrected CrossAxisAlignment --> not just for Row.
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3211 Replace broken (possibly old?) Step #4
  src/docs/cookbook/navigation/navigate-with-arguments.md
Labels: cla: yes

#3219 Remove the Basic Layout survey
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3220 Basic Flutter Layout Page Fix
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3177 Update json.md
  src/docs/development/data-and-backend/json.md
Labels: cla: yes, e0-minutes, p3-low

#3223 Add UXR research banner.
  src/docs/development/ui/widgets/cupertino.md
  src/docs/resources/platform-adaptations.md
Labels: cla: yes

#3227 Added link to Provider article
  src/docs/development/data-and-backend/state-mgmt/options.md
Labels: cla: yes

#3231 Cross-link to dart.dev docs
  src/docs/development/tools/devtools/overview.md
Labels: cla: yes

#3192 [DO NOT MERGE] Update C interop note
  src/docs/development/platform-integration/c-interop.md
Labels: cla: yes

#3232 Demo for Grid List Page
  README.md
  src/docs/cookbook/lists/grid-lists.md
  src/images/cookbook/grid-list.gif
Labels: cla: yes

#3225 Simple State Mgt Example Repair
  src/_assets/image/development/data-and-backend/state-mgmt/simple-widget-tree-with-cart.png
  src/_assets/image/development/data-and-backend/state-mgmt/simple-widget-tree.png
  src/docs/development/data-and-backend/state-mgmt/simple.md
Labels: cla: yes

#3230 Update json_serializable example
  src/docs/development/data-and-backend/json.md
Labels: cla: yes

#3234 Tweak link to dart.dev
  src/docs/development/tools/devtools/overview.md
Labels: cla: yes

#3236 Closes #1716, highlights official Google Groups in /community
  src/_assets/image/community/screen-google.png
  src/_data/community.yml
  src/community/index.html
Labels: cla: yes

#3233 Closes #3218, makes books page mobile-friendly.
  src/_assets/css/_books.scss
  src/_assets_old/css/_bootstrap_config.scss
  src/docs/resources/books.md
Labels: cla: yes

#3235 Adding a link to the Firebase hosting article and some cleanup.
  src/docs/development/data-and-backend/firebase.md
  src/docs/development/data-and-backend/json.md
  src/docs/development/ui/navigation.md
  src/docs/development/ui/widgets-intro.md
  src/docs/development/ui/widgets/index.md
Labels: cla: yes

#3239 Updates add-flutter-screen.md to the latest embedding API.
  src/docs/development/add-to-app/android/add-flutter-screen.md
Labels: cla: yes

#3238 Updates add-flutter-fragment.md instructions to latest embedding API.
  src/docs/development/add-to-app/android/add-flutter-fragment.md
Labels: cla: yes

#3240 Be more clear about add to app
  src/docs/development/androidx-migration.md
Labels: cla: yes

#3242 Template for breaking change descriptions
  src/docs/release/breaking-changes/template.md
Labels: cla: yes

#3237 Add iOS add-to-app docs to sidenav
  src/_data/sidenav.yml
  src/docs/development/add-to-app/android/project-setup.md
  src/docs/development/add-to-app/ios/add-flutter-screen.md
  src/docs/development/add-to-app/ios/project-setup.md
Labels: cla: yes

#3243 Updates to add-flutter-screen.md to clarify a few instructions.
  src/docs/development/add-to-app/android/add-flutter-screen.md
Labels: cla: yes

#3244 Update tap-drag.md
  src/docs/cookbook/testing/widget/tap-drag.md
Labels: cla: yes

#3253 Flutter Clock Phase 2
  src/_assets/css/_clock.scss
  src/_assets/css/_variables.scss
  src/_assets/image/clock/Flutter-logo.svg
  src/_assets/image/clock/G-Assistant-logo.svg
  src/_assets/image/clock/Lenovo-WTM.png
  src/_assets/image/clock/Lenovo-logo.svg
  src/_assets/image/clock/card-beauty.png
  src/_assets/image/clock/card-code-quality.png
  src/_assets/image/clock/card-execution.png
  src/_assets/image/clock/card-novelty.png
  src/_assets/image/clock/hero/hero-circle.svg
  src/_assets/image/clock/hero/hero-clock.svg
  src/_assets/image/clock/hero/hero-diamond.svg
  src/_assets/image/clock/hero/hero-dots.svg
  src/_assets/image/clock/hero/hero-oval.svg
  src/_assets/image/clock/iMac.png
  src/_assets/image/clock/prizes__background.svg
  src/_assets/image/clock/wtm__background-bottom.svg
  src/_assets/image/clock/wtm__background-top.svg
  src/_data/clock/contest_rules.yml
  src/_data/clock/entries.yml
  src/_data/clock/faqs.yml
  src/_data/clock/getting_started_items.yml
  src/_data/clock/prizes.yml
  src/_data/clock/submission_requirements.yml
  src/_data/clock_cards.yml
  src/_data/faqs.yml
  src/clock/index.html
Labels: cla: yes

#3255 Banner
  src/_includes/banner.html
Labels: cla: yes

#3254 refactor layout-basics to use inject_embed.dart.js
  src/_includes/layout-basics/add-four-icons.md
  src/_includes/layout-basics/aligning-text.md
  src/_includes/layout-basics/changing-fit-properties.md
  src/_includes/layout-basics/create-the-name-and-title.md
  src/_includes/layout-basics/creating-a-column.md
  src/_includes/layout-basics/creating-an-icon.md
  src/_includes/layout-basics/creating-more-space.md
  src/_includes/layout-basics/creating-space.md
  src/_includes/layout-basics/displaying-an-image.md
  src/_includes/layout-basics/enter-contact-information.md
  src/_includes/layout-basics/filling-extra-space.md
  src/_includes/layout-basics/modifying-axis-size.md
  src/_includes/layout-basics/modifying-cross-axis-alignment.md
  src/_includes/layout-basics/modifying-main-axis-alignment.md
  src/_includes/layout-basics/resizing-a-widget.md
  src/_includes/layout-basics/testing-flex-values.md
  src/_includes/layout-basics/tweak-the-layout.md
  src/_includes/layout-basics/wrap-the-column-in-a-row.md
  src/assets/codelabs/js/inject_embed.dart.js
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3259 fix warnings in console on homepage
  src/_packages/dartpad_picker/compile.sh
  src/_packages/dartpad_picker/compile_dev.sh
  src/_packages/dartpad_picker/lib/dartpad_picker.dart
  src/assets/js/dartpad_picker_main.dart.js
  src/assets/js/detect_safari.js
  src/index.html
Labels: cla: yes

#3258 Update implicit animations codelab w/ inject script
  src/_includes/implicit-animations/fade-in-complete.md
  src/_includes/implicit-animations/fade-in-starter-code.md
  src/_includes/implicit-animations/shape-shifting-complete.md
  src/_includes/implicit-animations/shape-shifting-starter-code.md
  src/docs/codelabs/implicit-animations.md
Labels: cla: yes

#3250 Added Flutter Succinctly in Books
  src/_assets/image/cover/flutter-succinctly.png
  src/_data/books.yml
Labels: cla: yes

#3251 Fixed typo in link title
  src/docs/development/data-and-backend/state-mgmt/options.md
Labels: cla: yes

#3256 Add a section on error handling
  src/_data/sidenav.yml
  src/docs/testing/errors.md
Labels: cla: yes

#3252 Fix powershell link in windows setup page
  src/docs/get-started/install/windows.md
Labels: cla: yes

#3257 Add missing add-to-app header images.
  src/_assets/image/development/add-to-app/android/add-flutter-fragment/add-flutter-fragment_fullscreen.png
  src/_assets/image/development/add-to-app/android/add-flutter-fragment/add-flutter-fragment_partial-ui.png
Labels: cla: yes

#3260 Fixing typo.
  src/_data/clock/getting_started_items.yml
Labels: cla: yes

#3261 Revert "Update implicit animations codelab w/ inject script"
  src/_includes/implicit-animations/fade-in-complete.md
  src/_includes/implicit-animations/fade-in-starter-code.md
  src/_includes/implicit-animations/shape-shifting-complete.md
  src/_includes/implicit-animations/shape-shifting-starter-code.md
  src/docs/codelabs/implicit-animations.md
Labels: cla: yes

#3264 Revert "refactor layout-basics to use inject_embed.dart.js"
  src/_includes/layout-basics/add-four-icons.md
  src/_includes/layout-basics/aligning-text.md
  src/_includes/layout-basics/changing-fit-properties.md
  src/_includes/layout-basics/create-the-name-and-title.md
  src/_includes/layout-basics/creating-a-column.md
  src/_includes/layout-basics/creating-an-icon.md
  src/_includes/layout-basics/creating-more-space.md
  src/_includes/layout-basics/creating-space.md
  src/_includes/layout-basics/displaying-an-image.md
  src/_includes/layout-basics/enter-contact-information.md
  src/_includes/layout-basics/filling-extra-space.md
  src/_includes/layout-basics/modifying-axis-size.md
  src/_includes/layout-basics/modifying-cross-axis-alignment.md
  src/_includes/layout-basics/modifying-main-axis-alignment.md
  src/_includes/layout-basics/resizing-a-widget.md
  src/_includes/layout-basics/testing-flex-values.md
  src/_includes/layout-basics/tweak-the-layout.md
  src/_includes/layout-basics/wrap-the-column-in-a-row.md
  src/assets/codelabs/js/inject_embed.dart.js
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3268 Switch gist examples to use unforked dartpad backend
  _config.yml
  src/_packages/dartpad_picker/lib/dartpad_picker.dart
  src/_packages/dartpad_picker/web/dartpad_picker_main.dart
  src/assets/js/dartpad_picker_main.dart.js
  src/docs/codelabs/implicit-animations.md
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3267 Flutter - Showcase - Update Groupon Card
  src/_assets/image/showcase/cards/groupon-top-400.jpg
  src/_assets/image/showcase/cards/groupon-top-400.png
  src/_assets/image/showcase/cards/groupon-top-600.jpg
  src/_assets/image/showcase/cards/groupon-top-600.png
  src/_data/showcases.yml
Labels: cla: yes

#3263 Fixed the format issue on URL links.
  src/docs/testing/errors.md
Labels: cla: yes

#3269 update all embeds to non-experimental, unforked versions
  .firebaserc
  README.md
  _config.yml
  src/_packages/dartpad_picker/lib/dartpad_picker.dart
  src/assets/js/dartpad_picker_main.dart.js
  src/docs/codelabs/implicit-animations.md
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3271 Document new breaking change policy
  src/_data/sidenav.yml
  src/docs/release/breaking-changes/index.md
  src/docs/resources/compatibility.md
Labels: cla: yes

#3265 Add an add-to-app landing page
  src/_data/sidenav.yml
  src/docs/development/add-to-app/android/add-flutter-fragment.md
  src/docs/development/add-to-app/android/index.md
  src/docs/development/add-to-app/index.md
  src/docs/development/add-to-app/ios/index.md
Labels: cla: yes

#3275 refresh-code-excerpts.sh fix
  tool/refresh-code-excerpts.sh
Labels: cla: yes, infrastructure

#3274 Update firebase.json
  firebase.json
Labels: cla: yes

#3279 Add clarification about cartModel.
  src/docs/development/data-and-backend/state-mgmt/simple.md
Labels: cla: yes

#3278 Add Post class -- was formerly undefined.
  src/docs/cookbook/testing/unit/mocking.md
Labels: cla: yes

#3273 Adding a link to the "Why Flutter uses Dart" video.
  src/docs/perf/rendering/ui-performance.md
Labels: cla: yes

#3280 fixed unknown backgroundColor parameter
  src/docs/get-started/flutter-for/web-devs.md
Labels: cla: yes

#2977 propose to correct the comment
  examples/layout/card_and_stack/lib/main.dart
Labels: cla: yes

#3283 Flutter - Showcase - Update Philips Hue Card
  src/_assets/image/showcase/cards/hue_philips-logo.png
  src/_assets/image/showcase/cards/philips_hue-logo.png
  src/_assets/image/showcase/cards/philips_hue-top-400.jpg
  src/_assets/image/showcase/cards/philips_hue-top-600.jpg
  src/_data/showcases.yml
  src/showcase/index.html
Labels: cla: yes

#3285 Update banner with Q4 survey link
  src/_includes/banner.html
Labels: cla: yes

#3286 Re-sync non-add-to-app changes to master
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/packages-and-plugins/using-packages.md
Labels: cla: yes

#3289 Add implicit animations codelab to site banner.
  src/_includes/banner.html
Labels: cla: yes

#3301 Flutter Clock phase 2 - feedback
  src/_assets/css/_clock.scss
  src/_data/clock/faqs.yml
  src/_data/clock/getting_started_items.yml
  src/clock/index.html
  src/images/flutter-clock-social.png
Labels: cla: yes

#3303 Document the new plugin platforms key
  src/docs/development/packages-and-plugins/developing-packages.md
Labels: cla: yes

#3304 Flutter - Update clock faqs
  src/_data/clock/faqs.yml
Labels: cla: yes

#3290 Add go/actions-and-shortcuts-design-revision
  firebase.json
Labels: cla: yes

#3299 Broken links for Firebase Messaging plugin
  src/docs/get-started/flutter-for/android-devs.md
Labels: cla: yes

#3295 Update passing-data.md
  src/docs/cookbook/navigation/passing-data.md
Labels: cla: yes

#3312 Add Sliver Boring Show to slivers page
  src/docs/development/ui/advanced/slivers.md
Labels: cla: yes

#3282 Add Kotlin sample code for fullscreen and fragment guides.
  src/docs/development/add-to-app/android/add-flutter-fragment.md
  src/docs/development/add-to-app/android/add-flutter-screen.md
Labels: cla: yes

#3309 Revise iOS add-to-app usage page
  src/_assets/image/development/add-to-app/ios/add-flutter-screen/cli-attach.png
  src/_assets/image/development/add-to-app/ios/add-flutter-screen/intellij-attach.png
  src/_assets/image/development/add-to-app/ios/add-flutter-screen/vscode-attach.png
  src/_assets/js/main.js
  src/_assets/js/tabs.js
  src/_data/sidenav.yml
  src/docs/development/add-to-app/ios/add-flutter-screen.md
Labels: cla: yes

#3324 Fix firebase.json
  firebase.json
Labels: cla: yes
