Repository flutter/website, pull requests merged in 2019-10, with the labels that each got.

#3047 Updated link to Nubank section
  src/_data/showcases.yml
Labels: cla: yes

#3050 hide debug banner in front page samples
  src/_packages/dartpad_picker/web/dartpad_picker_main.dart
  src/assets/dash/js/dartpad_picker_main.dart.js
Labels: cla: yes

#3048 Fix Typo
  src/docs/development/platform-integration/c-interop.md
Labels: cla: yes

#3057 update swift samples to Swift 5
  src/docs/development/platform-integration/platform-channels.md
Labels: cla: yes

#3062 Update to Groupon Card
  src/_data/showcases.yml
Labels: cla: yes

#3053 SubHeader: Adding gesture detection to widgets
  src/docs/development/ui/advanced/gestures.md
Labels: cla: yes

#3064 change order of forms cookbook section
  src/docs/cookbook/forms/focus.md
  src/docs/cookbook/forms/retrieve-input.md
  src/docs/cookbook/forms/text-field-changes.md
  src/docs/cookbook/forms/text-input.md
Labels: cla: yes

#3067 Use sentence case for image
  src/_assets/image/resources/diagram-layercake.png
  src/_diagrams/resources/diagram-layercake.graffle
  src/docs/resources/technical-overview.md
  src/images/whatisflutter/diagram-layercake.svg
Labels: cla: yes

#3068 Adding a warning about app bundles not working on some devices.
  src/docs/deployment/android.md
Labels: cla: yes

#3069 Create go link for "Navigator with Router"
  firebase.json
Labels: cla: yes

#3070 fix previous article link
  src/docs/cookbook/gestures/ripples.md
Labels: cla: yes

#3078 Reinstate check-code, but allow it to fail
  .travis.yml
Labels: cla: yes, examples, infrastructure, tests

#3077 C-interop: don't try to analyze incomplete code fragmennts
  src/docs/development/platform-integration/c-interop.md
Labels: cla: yes, examples, tests

#3072 Changing "Pub" to "pub.dev" across the site.
  src/docs/codelabs/index.md
  src/docs/codelabs/layout-basics.md
  src/docs/cookbook/design/package-fonts.md
  src/docs/cookbook/networking/fetch-data.md
  src/docs/development/data-and-backend/state-mgmt/options.md
  src/docs/development/packages-and-plugins/developing-packages.md
  src/docs/development/packages-and-plugins/using-packages.md
  src/docs/development/platform-integration/web.md
  src/docs/development/ui/animations/staggered-animations.md
  src/docs/get-started/codelab.md
  src/docs/get-started/flutter-for/ios-devs.md
  src/docs/get-started/flutter-for/react-native-devs.md
  src/docs/get-started/flutter-for/xamarin-forms-devs.md
  src/docs/resources/faq.md
Labels: cla: yes

#3080 Add AndroidX migration docs
  firebase.json
  src/_data/sidenav.yml
  src/docs/development/androidx-migration.md
  src/docs/development/packages-and-plugins/androidx-compatibility.md
  src/images/androidx/do_androidx_refactor.png
  src/images/androidx/migrate_prompt.png
Labels: cla: yes

#3090 Update dartpad url
  _config.yml
  src/_packages/dartpad_picker/lib/dartpad_picker.dart
  src/assets/dash/js/dartpad_picker_main.dart.js
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3092 Fix a link
  src/docs/resources/bootstrap-into-dart.md
Labels: cla: yes

#3093 Fix markdown in AndroidX migration guide
  src/docs/development/androidx-migration.md
Labels: cla: yes

#2996 Updating the pub command.
  src/docs/development/packages-and-plugins/developing-packages.md
Labels: cla: yes

#3084 Added a help page for iOS add-to-app.
  src/docs/development/add-to-app/ios/add-flutter-screen.md
Labels: cla: yes

#3102 use site.custom instead of custom for dartpad URL
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#3105 Swift and Kotlin is the default for flutter create
  src/docs/development/packages-and-plugins/developing-packages.md
Labels: cla: yes

#3103 Added info about Google Ads on Android app page
  src/docs/deployment/android.md
Labels: cla: yes

#3108 Refresh pubspec.lock files
  example/pubspec.lock
  pubspec.lock
Labels: cla: yes, examples, infrastructure

#3101 Add xcodebuild -runFirstLaunch command to iOS setup instructions
  src/docs/get-started/install/_ios-setup.md
Labels: cla: yes

#3097 Typo in sqflite
  src/docs/cookbook/persistence/sqlite.md
Labels: cla: yes

#3096 Added CD Option
  src/docs/deployment/cd.md
Labels: cla: yes

#3110 Animation tutorial: drop unnecessary local var type decl
  examples/animation/animate2/lib/main.dart
  examples/animation/animate3/lib/main.dart
  examples/animation/animate5/lib/main.dart
  src/docs/development/ui/animations/tutorial.md
Labels: cla: yes

#3109 Check code-excerpt freshness
  tool/check-code.sh
  tool/refresh-code-excerpts.sh
Labels: cla: yes, infrastructure

#3112 Don't commit pubspec.lock files for tools and examples
  .gitignore
  example/pubspec.lock
  pubspec.lock
Labels: cla: yes, infrastructure

#3115 Move position of "Try Flutter" section further up on landing page
  src/index.html
Labels: cla: yes

#3114 update fetch-data article
  src/docs/cookbook/networking/fetch-data.md
Labels: cla: yes

#3128 Add go link for faster cocoon design doc
  firebase.json
Labels: cla: yes

#3124 Add link for go/android-assets-in-flutter
  firebase.json
Labels: cla: yes

#3121 Remove instructions to install CocoaPods version 1.7.5
  src/docs/get-started/install/_ios-setup.md
Labels: cla: yes

#3119 Replaced example code with code that is less fraught with peril.
  src/docs/development/ui/assets-and-images.md
Labels: cla: yes

#3117 Added google ads info to FAQ
  src/docs/resources/faq.md
Labels: cla: yes

#3116 Added Google ads info to iOS page
  src/docs/deployment/ios.md
Labels: cla: yes

#3122 Add Android Studio workaround
  src/docs/development/androidx-migration.md
Labels: cla: yes

#3125 Fix typo on introduction.md in integration testing
  src/docs/cookbook/testing/integration/introduction.md
Labels: cla: yes

#3113 check-code: try to offer a bit more guidance / help when refresh fails
  src/docs/development/ui/interactive.md
  tool/check-code.sh
Labels: cla: yes, infrastructure, ⚠ WIP

#3132 Add instructions for updating the version number
  src/docs/deployment/android.md
Labels: cla: yes

#3133 Clarification of 'onTap on 'Taps, drags, and other gestures' page
  src/docs/development/ui/advanced/gestures.md
Labels: cla: yes

#3129 Fix GitHub Actions link
  src/docs/deployment/cd.md
Labels: cla: yes

#3135 Update index.html
  src/index.html
Labels: cla: yes

#3134 Updated Link for Custom Paint Stackoverflow
  src/docs/get-started/flutter-for/android-devs.md
Labels: cla: yes

#3131 Add step for importing packages after dependency installation
  src/docs/cookbook/persistence/sqlite.md
Labels: cla: yes

#3130 [package.json] Flutter not Dart for name, description, and url
  package.json
Labels: cla: yes

#3139 Make the spinning curve more natural
  src/_packages/dartpad_picker/web/dartpad_picker_main.dart
Labels: cla: yes

#3142 go link for platform-interface-breaking-changes
  firebase.json
Labels: cla: yes

#3143 Update README.md
  README.md
Labels: cla: yes

#3144 Updated JSON and Serialization Page
  src/docs/development/data-and-backend/json.md
Labels: cla: yes

#3147 go link for synchronized-widgettester
  firebase.json
Labels: cla: yes

#3149 Revert "Move position of "Try Flutter" section further up on landing page"
  src/index.html
Labels: cla: yes

#3150 Update fetch-data.md
  src/docs/cookbook/networking/fetch-data.md
Labels: cla: yes

#3137 Code excerpt refresh: support keep .dart_tool via option
  tool/check-code.sh
  tool/refresh-code-excerpts.sh
Labels: cla: yes, infrastructure

#3154 Don't check links twice and don't deploy from a cron build
  .travis.yml
Labels: cla: yes, infrastructure

#3156 Fixed optional type usage for swift example code.
  src/docs/development/add-to-app/ios/add-flutter-screen.md
Labels: cla: yes

#3158 docs: fix typo
  src/docs/resources/technical-overview.md
Labels: cla: yes

#3157 Update 404.html
  src/404.html
Labels: cla: yes

#3161 Add 'this section' to the list of resources
  src/docs/development/data-and-backend/state-mgmt/options.md
Labels: cla: yes

#3151 Corrected Punctuation
  src/docs/deployment/cd.md
Labels: cla: yes

#3162 Set up layout for resources/books page
  src/_assets/css/_books.scss
  src/_assets/css/main.scss
  src/_assets/image/cover/beginning-flutter.png
  src/_data/books.yml
  src/_data/sidenav.yml
  src/docs/resources/books.md
Labels: cla: yes

#3174 tweaking
  src/_includes/banner.html
Labels: cla: yes

#3175 Fixing links.
  src/_includes/banner.html
Labels: cla: yes

#3171 Update navigation-basics.md
  src/docs/cookbook/navigation/navigation-basics.md
Labels: cla: yes

#3168 docs: fix typos
  src/docs/cookbook/design/themes.md
  src/docs/development/ui/advanced/gestures.md
  src/docs/development/ui/layout/box-constraints.md
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#3159 Performance
  firebase.json
  src/_data/sidenav.yml
  src/_includes/run-profile.md
  src/docs/deployment/android.md
  src/docs/deployment/cd.md
  src/docs/deployment/flavors.md
  src/docs/development/tools/devtools/inspector.md
  src/docs/development/tools/devtools/timeline.md
  src/docs/perf/app-size.md
  src/docs/perf/index.md
  src/docs/perf/memory.md
  src/docs/perf/power.md
  src/docs/perf/rendering/best-practices.md
  src/docs/perf/rendering/index.md
  src/docs/perf/rendering/ui-performance.md
  src/docs/testing/code-debugging.md
  src/docs/testing/debugging.md
  src/docs/testing/oem-debuggers.md
  src/docs/whats-new-archive.md
Labels: cla: yes

#3141 (completely optional) Use BigInt for fibonacci computation
  src/_packages/dartpad_picker/web/dartpad_picker_main.dart
  src/assets/dash/js/dartpad_picker_main.dart.js
Labels: cla: yes

#3182 Add automatic-android-plugin-registration link
  firebase.json
Labels: cla: yes

#3181 Improvement to spinning sample code
  src/_packages/dartpad_picker/web/dartpad_picker_main.dart
  src/assets/dash/js/dartpad_picker_main.dart.js
Labels: cla: yes
