Repository flutter/website, pull requests merged in 2019-01, with the labels that each got.

#2155 Homepage native app demo attribution
  src/index.html
Labels: cla: yes

#2161 Fix code diff plugin issue
  src/_plugins/code_diff.rb
Labels: cla: yes, infrastructure

#2162 Make 'JSON and serialization' page mobile friendly
  src/docs/development/data-and-backend/json.md
Labels: cla: yes

#2163 App code for examples/layout/lakes in 6 steps
  examples/layout/lakes/step0/lib/main.dart
  examples/layout/lakes/step0/pubspec.yaml
  examples/layout/lakes/step0/test/widget_test.dart
  examples/layout/lakes/step2/lib/main.dart
  examples/layout/lakes/step2/pubspec.yaml
  examples/layout/lakes/step2/test/widget_test.dart
  examples/layout/lakes/step3/lib/main.dart
  examples/layout/lakes/step3/pubspec.yaml
  examples/layout/lakes/step3/test/widget_test.dart
  examples/layout/lakes/step4/lib/main.dart
  examples/layout/lakes/step4/pubspec.yaml
  examples/layout/lakes/step4/test/widget_test.dart
  examples/layout/lakes/step5/images/lake.jpg
  examples/layout/lakes/step5/lib/main.dart
  examples/layout/lakes/step5/pubspec.yaml
  examples/layout/lakes/step5/test/widget_test.dart
  examples/layout/lakes/step6/images/lake.jpg
  examples/layout/lakes/step6/lib/main.dart
  examples/layout/lakes/step6/pubspec.yaml
  examples/layout/lakes/step6/test/widget_test.dart
Labels: cla: yes, examples

#2164 Update the Building Layouts page to use the new app sources
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2174 A few tweaks to the branding
  src/brand.md
  src/tos.md
Labels: cla: yes

#2179 Code_excerpt plugin with a functional copy code button
  src/_assets/css/_code.scss
  src/_assets/css/main.scss
  src/_assets/js/main.js
  src/_includes/head.html
  src/_plugins/code_excerpt.rb
  src/docs/development/ui/layout/index.md
Labels: cla: yes, infrastructure

#2184 Add a copy-code button to every code excerpt
  src/_assets/css/_code.scss
  src/_assets/js/main.js
  src/_plugins/code_excerpt.rb
Labels: cla: yes, infrastructure

#2185 Rename "iTunes Connect" to "App Store Connect"
  src/docs/deployment/ios.md
Labels: cla: yes

#2175 Update widgets.json
  src/_data/catalog/widgets.json
Labels: cla: yes

#2121 Showcase: show Reel w/o leaving page
  src/showcase/index.html
Labels: cla: yes

#2180 Updating the video page and fixing a bug in the Android Release page.
  src/docs/deployment/android.md
  src/docs/resources/videos.md
Labels: cla: yes

#2191 System requirements: state that git 2.x is required
  src/docs/get-started/install/linux.md
  src/docs/get-started/install/macos.md
  src/docs/get-started/install/windows.md
Labels: cla: yes

#2192 Tutorial sources: link to GitHub page rather than raw content
  src/_data/sidenav.yml
  src/docs/catalog/samples/animated-list.md
  src/docs/catalog/samples/app-bar-bottom.md
  src/docs/catalog/samples/basic-app-bar.md
  src/docs/catalog/samples/expansion-tile-sample.md
  src/docs/development/ui/animations/staggered-animations/index.md
  src/docs/development/ui/animations/tutorial.md
  src/docs/development/ui/interactive/index.md
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2195 Fix link to React site
  src/docs/development/ui/widgets-intro.md
Labels: cla: yes

#2197 Factor out code_diff_core
  src/_plugins/code_diff.rb
  src/_plugins/code_diff_core.rb
Labels: cla: yes, infrastructure

#2171 Fix small typos on Accesibility docs
  src/docs/development/accessibility-and-localization/accessibility.md
Labels: cla: yes

#2209 Address typo and tweak phrasing
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2168 Updated Testing Index.md Documentation
  src/docs/testing/index.md
Labels: cla: yes

#2093 Updates to Navigation cookbook page
  src/docs/cookbook/navigation/navigation-basics.md
Labels: cla: yes

#2218 Add next/prev links to cookbook pages
  pubspec.lock
  pubspec.yaml
  src/docs/cookbook/animation/opacity-animation.md
  src/docs/cookbook/design/drawer.md
  src/docs/cookbook/design/fonts.md
  src/docs/cookbook/design/orientation.md
  src/docs/cookbook/design/package-fonts.md
  src/docs/cookbook/design/snackbars.md
  src/docs/cookbook/design/tabs.md
  src/docs/cookbook/design/themes.md
  src/docs/cookbook/forms/focus.md
  src/docs/cookbook/forms/retrieve-input.md
  src/docs/cookbook/forms/text-field-changes.md
  src/docs/cookbook/forms/text-input.md
  src/docs/cookbook/forms/validation.md
  src/docs/cookbook/gestures/dismissible.md
  src/docs/cookbook/gestures/handling-taps.md
  src/docs/cookbook/gestures/ripples.md
  src/docs/cookbook/images/cached-images.md
  src/docs/cookbook/images/fading-in-images.md
  src/docs/cookbook/images/network-image.md
  src/docs/cookbook/lists/basic-list.md
  src/docs/cookbook/lists/grid-lists.md
  src/docs/cookbook/lists/horizontal-list.md
  src/docs/cookbook/lists/long-lists.md
  src/docs/cookbook/lists/mixed-list.md
  src/docs/cookbook/maintenance/error-reporting.md
  src/docs/cookbook/navigation/hero-animations.md
  src/docs/cookbook/navigation/named-routes.md
  src/docs/cookbook/navigation/navigation-basics.md
  src/docs/cookbook/navigation/passing-data.md
  src/docs/cookbook/navigation/returning-data.md
  src/docs/cookbook/networking/authenticated-requests.md
  src/docs/cookbook/networking/background-parsing.md
  src/docs/cookbook/networking/fetch-data.md
  src/docs/cookbook/networking/web-sockets.md
  src/docs/cookbook/persistence/key-value.md
  src/docs/cookbook/persistence/reading-writing-files.md
  src/docs/cookbook/testing/integration/introduction.md
  src/docs/cookbook/testing/integration/profiling.md
  src/docs/cookbook/testing/integration/scrolling.md
  src/docs/cookbook/testing/unit/introduction.md
  src/docs/cookbook/testing/unit/mocking.md
  src/docs/cookbook/testing/widget/finders.md
  src/docs/cookbook/testing/widget/introduction.md
  src/docs/cookbook/testing/widget/tap-drag.md
  tool/next_prev.dart
  tool/pubspec.yaml
Labels: cla: yes, infrastructure

#2219 Widget catalog: list widget categories in alphabetical order
  src/docs/development/ui/widgets/index.md
Labels: cla: yes, infrastructure

#2221 Ensure `Get started > Test drive` page is mobile friendly
  src/_assets/css/_code.scss
  src/docs/get-started/test-drive/_androidstudio.md
  src/docs/get-started/test-drive/_try-hot-reload.md
Labels: cla: yes, mobile

#2223 Split "Building Layouts" into two pages
  src/_data/sidenav.yml
  src/docs/development/ui/layout/box-constraints.md
  src/docs/development/ui/layout/index.md
  src/docs/development/ui/layout/tutorial.md
  src/docs/get-started/codelab.md
Labels: cla: yes

#2224 Adjust links to main cookbook unit testing page
  firebase.json
  src/docs/cookbook/networking/fetch-data.md
  src/docs/cookbook/testing/unit/mocking.md
  src/docs/cookbook/testing/widget/introduction.md
Labels: cla: yes

#2225 Drop files from src/_includes/code/layout/lakes since they aren't used anymore
  src/_includes/code/layout/lakes/.gitignore
  src/_includes/code/layout/lakes/images/lake.jpg
  src/_includes/code/layout/lakes/main.dart
  src/_includes/code/layout/lakes/pubspec.yaml
Labels: cla: yes

#2226 Don't use raw github repo images in examples
  src/docs/cookbook/images/cached-images.md
  src/docs/cookbook/images/fading-in-images.md
  src/docs/cookbook/images/network-image.md
  src/docs/cookbook/navigation/hero-animations.md
Labels: cla: yes

#2227 Interactive Layout page cleanup
  src/_assets/image/ui/favorited-not-favorited.png
  src/_assets/image/ui/tapbox-active-state.png
  src/_assets/image/ui/tapbox-inactive-state.png
  src/docs/development/ui/interactive.md
  src/docs/development/ui/interactive/images/lakes.jpg
  src/docs/development/ui/layout/box-constraints.md
  src/docs/development/ui/layout/index.md
  src/docs/development/ui/layout/tutorial.md
  src/docs/reference/tutorials.md
  src/docs/resources/technical-overview.md
Labels: cla: yes

#2232 Rename layout `lakes/step0` example to `base` so it can be reused
  examples/layout/base/README.md
  examples/layout/base/lib/main.dart
  examples/layout/base/pubspec.yaml
  examples/layout/base/test/widget_test.dart
  examples/layout/lakes/step2/lib/main.dart
  examples/layout/lakes/step3/lib/main.dart
  examples/layout/lakes/step4/lib/main.dart
  examples/layout/lakes/step5/lib/main.dart
  examples/layout/lakes/step6/lib/main.dart
  src/_includes/code/layout/lakes-interactive/main.dart
  src/docs/development/ui/layout/tutorial.md
  tool/build_check_deploy.sh
Labels: cla: yes, examples, infrastructure

#2230 Flutter Layout page copyedits and markdown cleanup
  src/docs/development/ui/layout/index.md
Labels: cla: yes, copyedits

#2231 Add LICENSE file
  LICENSE
Labels: cla: yes

#2234 Make old code excerpter ignore new `<?code-excerpt?>` blocks
  src/docs/development/ui/layout/tutorial.md
  src/docs/get-started/codelab.md
  tool/extract.dart
Labels: cla: yes, examples, infrastructure

#2236 Accessibility page: make images responsive, and clean markdown
  src/_assets/image/a18n/app-large-fonts.png
  src/_assets/image/a18n/app-regular-fonts.png
  src/docs/development/accessibility-and-localization/accessibility.md
Labels: cla: yes, copyedits, mobile

#2239 Add quotes around PATH value
  src/docs/get-started/install/_get-sdk.md
  src/docs/get-started/install/_path-mac-linux.md
Labels: cla: yes

#2243 Fix code-block spacing, and drop the few manual adjustments
  src/_assets/css/_code.scss
  src/docs/development/accessibility-and-localization/accessibility.md
  src/docs/get-started/test-drive/_try-hot-reload.md
Labels: cla: yes

#2244 Fix symlink to examples/layout/base/README.md
  examples/layout/base/README.md
Labels: cla: yes, examples

#2245 Fix typo for checkerboardRasterCacheImages
  src/docs/testing/ui-performance/index.md
Labels: cla: yes

#2247 Fix URL to PerformanceOverlayLayer.checkerboardRasterCacheImages
  src/docs/testing/ui-performance/index.md
Labels: cla: yes

#2251 Use new path-brace syntax for diff paths
  src/docs/development/ui/layout/tutorial.md
  src/docs/get-started/codelab.md
Labels: cla: yes, infrastructure

#2252 Added closing parenthesis that was missing
  src/docs/resources/faq.md
Labels: cla: yes

#2235 Rework of "Lay out a widget" + use of code-excerpts
  examples/layout/base/lib/main.dart
  examples/layout/lakes/step5/lib/main.dart
  examples/layout/non_material/README.md
  examples/layout/non_material/lib/main.dart
  examples/layout/non_material/pubspec.yaml
  examples/layout/non_material/test/widget_test.dart
  src/_includes/code/layout/widgets-only/.gitignore
  src/_includes/code/layout/widgets-only/pubspec.yaml
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2255 chore: use code_excerpt_updater v0.17.1
  pubspec.lock
Labels: cla: yes, infrastructure

#2257 Ensure FAQ is mobile friendly
  src/docs/resources/faq.md
Labels: cla: yes

#2259 Interactive UI page: markdown cleanup
  pubspec.lock
  src/docs/development/ui/interactive.md
Labels: cla: yes

#2267 Add examples/layout/lakes/interactive code
  examples/layout/lakes/interactive/README.md
  examples/layout/lakes/interactive/images/lake.jpg
  examples/layout/lakes/interactive/lib/main.dart
  examples/layout/lakes/interactive/pubspec.yaml
  examples/layout/lakes/interactive/test/widget_test.dart
Labels: cla: yes

#2273 Ensure i18n page is mobile friendly
  src/docs/development/accessibility-and-localization/internationalization.md
Labels: cla: yes

#2275 _data/catalog/widgets.json: merge two Transform widget entries
  src/_data/catalog/widgets.json
Labels: cla: yes

#2276 Animation tutorial: fix link to src and center img
  src/docs/development/ui/animations/tutorial.md
Labels: cla: yes

#2277 Material Components widgets: add SliverAppBar
  src/_data/catalog/widgets.json
Labels: cla: yes

#2281 Test-drive / VS Code: make mobile-friendly
  src/docs/get-started/test-drive/_vscode.md
Labels: cla: yes

#2282 Animations overview copyedit: add missing "a"
  src/docs/development/ui/animations/overview.md
Labels: cla: yes, copyedits

#2284 Community > Google Groups: add flutter-announce
  src/_data/community.yml
  src/community/index.html
Labels: cla: yes

#2287 Add link to Spanish site
  src/_assets/css/_footer.scss
  src/_includes/footer.html
Labels: cla: yes

#2288 Community: link to "Using Flutter in China"
  src/community/index.html
Labels: cla: yes

#2293 Layout tutorial: remove unused Liquid variable
  src/docs/development/ui/layout/tutorial.md
Labels: cla: yes

#2294 Layout row app + tests
  examples/layout/row/README.md
  examples/layout/row/images/pic1.jpg
  examples/layout/row/images/pic2.jpg
  examples/layout/row/images/pic3.jpg
  examples/layout/row/lib/main.dart
  examples/layout/row/pubspec.yaml
  examples/layout/row/test/widget_test.dart
Labels: cla: yes, examples

#2295 Layout row example - fix code excerpt
  examples/layout/row/lib/main.dart
  examples/layout/row/test/widget_test.dart
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2300 Add flutter-announce to link skip list
  tool/config/linkcheck-skip-list.txt
Labels: cla: yes

#2258 Added Codemagic CI for Flutter
  src/docs/testing/index.md
Labels: cla: yes

#2301 Layout sizing example app
  examples/layout/sizing/README.md
  examples/layout/sizing/images/pic1.jpg
  examples/layout/sizing/images/pic2.jpg
  examples/layout/sizing/images/pic3.jpg
  examples/layout/sizing/lib/main.dart
  examples/layout/sizing/pubspec.yaml
  examples/layout/sizing/test/widget_test.dart
  src/_assets/image/ui/layout/layout-too-large.png
  src/_includes/code/layout/hello-world/main.dart
  src/_includes/code/layout/hello-world/pubspec.yaml
  src/_includes/code/layout/row-expanded-2/.gitignore
  src/_includes/code/layout/row-expanded-2/main.dart
  src/_includes/code/layout/row-expanded-2/pubspec.yaml
  src/_includes/code/layout/row-expanded/.gitignore
  src/_includes/code/layout/row-expanded/images/pic1.jpg
  src/_includes/code/layout/row-expanded/images/pic2.jpg
  src/_includes/code/layout/row-expanded/images/pic3.jpg
  src/_includes/code/layout/row-expanded/main.dart
  src/_includes/code/layout/row-expanded/pubspec.yaml
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2305 Layout tutorial copyedits
  src/docs/development/ui/layout/tutorial.md
Labels: cla: yes, copyedits

#2307 Layout widgets: Container example app
  examples/layout/container/README.md
  examples/layout/container/images/pic1.jpg
  examples/layout/container/images/pic2.jpg
  examples/layout/container/images/pic3.jpg
  examples/layout/container/images/pic4.jpg
  examples/layout/container/lib/main.dart
  examples/layout/container/pubspec.yaml
  examples/layout/container/test/widget_test.dart
  examples/layout/pavlova/lib/main.dart
  src/_includes/code/layout/container/.gitignore
  src/_includes/code/layout/container/main.dart
  src/_includes/code/layout/container/pubspec.yaml
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2309 Layout example: ListView
  examples/layout/grid/lib/main.dart
  examples/layout/grid_and_list/README.md
  examples/layout/grid_and_list/images/pic0.jpg
  examples/layout/grid_and_list/images/pic1.jpg
  examples/layout/grid_and_list/images/pic10.jpg
  examples/layout/grid_and_list/images/pic11.jpg
  examples/layout/grid_and_list/images/pic12.jpg
  examples/layout/grid_and_list/images/pic13.jpg
  examples/layout/grid_and_list/images/pic14.jpg
  examples/layout/grid_and_list/images/pic15.jpg
  examples/layout/grid_and_list/images/pic16.jpg
  examples/layout/grid_and_list/images/pic17.jpg
  examples/layout/grid_and_list/images/pic18.jpg
  examples/layout/grid_and_list/images/pic19.jpg
  examples/layout/grid_and_list/images/pic2.jpg
  examples/layout/grid_and_list/images/pic20.jpg
  examples/layout/grid_and_list/images/pic21.jpg
  examples/layout/grid_and_list/images/pic22.jpg
  examples/layout/grid_and_list/images/pic23.jpg
  examples/layout/grid_and_list/images/pic24.jpg
  examples/layout/grid_and_list/images/pic25.jpg
  examples/layout/grid_and_list/images/pic26.jpg
  examples/layout/grid_and_list/images/pic27.jpg
  examples/layout/grid_and_list/images/pic28.jpg
  examples/layout/grid_and_list/images/pic29.jpg
  examples/layout/grid_and_list/images/pic3.jpg
  examples/layout/grid_and_list/images/pic4.jpg
  examples/layout/grid_and_list/images/pic5.jpg
  examples/layout/grid_and_list/images/pic6.jpg
  examples/layout/grid_and_list/images/pic7.jpg
  examples/layout/grid_and_list/images/pic8.jpg
  examples/layout/grid_and_list/images/pic9.jpg
  examples/layout/grid_and_list/lib/main.dart
  examples/layout/grid_and_list/pubspec.yaml
  examples/layout/grid_and_list/test/widget_test.dart
  src/_includes/code/layout/listview/.gitignore
  src/_includes/code/layout/listview/main.dart
  src/_includes/code/layout/listview/pubspec.yaml
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2306 Update banner for Q1 survey (to be launched Jan 30)
  src/_includes/banner.html
Labels: cla: yes

#2314 Layout example: Card and Stack
  examples/layout/card_and_stack/README.md
  examples/layout/card_and_stack/images/pic.jpg
  examples/layout/card_and_stack/lib/main.dart
  examples/layout/card_and_stack/pubspec.yaml
  examples/layout/card_and_stack/test/widget_test.dart
  examples/layout/lakes/interactive/lib/main.dart
  examples/layout/lakes/step2/lib/main.dart
  examples/layout/lakes/step3/lib/main.dart
  examples/layout/lakes/step4/lib/main.dart
  examples/layout/lakes/step5/lib/main.dart
  examples/layout/lakes/step6/lib/main.dart
  examples/layout/non_material/lib/main.dart
  examples/layout/pavlova/lib/main.0.dart
  src/_includes/code/layout/card/.gitignore
  src/_includes/code/layout/card/pubspec.yaml
  src/_includes/code/layout/stack/.gitignore
  src/_includes/code/layout/stack/main.dart
  src/_includes/code/layout/stack/pubspec.yaml
  src/docs/development/ui/interactive.md
  src/docs/development/ui/layout/index.md
  src/docs/development/ui/layout/tutorial.md
Labels: cla: yes

#2316 README tweaks
  README.md
Labels: cla: yes

#2317 Animations markdown cleanup
  src/docs/development/ui/animations/index.md
  src/docs/development/ui/animations/tutorial.md
Labels: cla: yes

#2320 Animation tutorial: create full example apps and use code excerpter
  examples/animation/.gitignore
  examples/animation/animate0/README.md
  examples/animation/animate0/lib/main.dart
  examples/animation/animate0/pubspec.yaml
  examples/animation/animate0/test/widget_test.dart
  examples/animation/animate1/README.md
  examples/animation/animate1/lib/main.dart
  examples/animation/animate1/pubspec.yaml
  examples/animation/animate1/test/widget_test.dart
  examples/animation/animate2/README.md
  examples/animation/animate2/lib/main.dart
  examples/animation/animate2/pubspec.yaml
  examples/animation/animate2/test/widget_test.dart
  examples/animation/animate3/README.md
  examples/animation/animate3/lib/main.dart
  examples/animation/animate3/pubspec.yaml
  examples/animation/animate3/test/widget_test.dart
  examples/animation/animate4/README.md
  examples/animation/animate4/lib/main.dart
  examples/animation/animate4/pubspec.yaml
  examples/animation/animate4/test/widget_test.dart
  examples/animation/animate5/README.md
  examples/animation/animate5/lib/main.dart
  examples/animation/animate5/pubspec.yaml
  examples/animation/animate5/test/widget_test.dart
  src/_includes/code/animation/animate1/pubspec.yaml
  src/_includes/code/animation/animate2/pubspec.yaml
  src/_includes/code/animation/animate3/main.dart
  src/_includes/code/animation/animate3/pubspec.yaml
  src/_includes/code/animation/animate4/main.dart
  src/_includes/code/animation/animate4/pubspec.yaml
  src/_includes/code/animation/animate5/main.dart
  src/_includes/code/animation/animate5/pubspec.yaml
  src/docs/development/ui/animations/tutorial.md
Labels: cla: yes

#2145 Update android-devs.md
  src/docs/get-started/flutter-for/android-devs.md
Labels: cla: yes

#2329 Uploaded hot reload time
  src/docs/development/tools/hot-reload.md
Labels: cla: yes

#2328 Update Mac setup with create
  src/docs/get-started/install/_ios-setup.md
Labels: cla: yes

#2327 Added rel="noopener" where missing
  src/community/index.html
  src/index.html
  src/showcase/index.html
Labels: cla: yes

#2324 Fixed typing of lists in sample code
  src/docs/get-started/flutter-for/android-devs.md
Labels: cla: yes
