Repository flutter/website, pull requests merged in 2019-07, with the labels that each got.

#2783 Created a guide for adding a single Flutter screen to an Android app.
  src/_assets/image/development/platform-integration/add-to-app-android/add-flutter-screen/add-single-flutter-screen-transparent_header.png
  src/_assets/image/development/platform-integration/add-to-app-android/add-flutter-screen/add-single-flutter-screen_header.png
  src/_data/sidenav.yml
  src/docs/development/platform-integration/add-to-app-android/add-flutter-screen.md
Labels: cla: yes

#2799 Adjust the step by step to the same file name
  src/docs/get-started/flutter-for/android-devs.md
Labels: cla: yes

#2800 Fix a few more .org links
  _config.yml
  examples/internationalization/intl_example/lib/main.dart
  src/_data/sidenav.yml
Labels: cla: yes

#2801 update DartPad layout in layout-basics codelab
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#2805 typo on play-video.md
  src/docs/cookbook/plugins/play-video.md
Labels: cla: yes

#2803 dartpad.dev ftw!
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#2804 Added cupertino localizations
  src/docs/development/accessibility-and-localization/internationalization.md
Labels: cla: yes

#2807 Remove confusing provider article
  src/docs/development/data-and-backend/state-mgmt/options.md
Labels: cla: yes

#2812 add page route animation article to cookbook
  src/docs/cookbook/animation/animated-container.md
  src/docs/cookbook/animation/page-route-animation.md
  src/images/cookbook/page-route-animation.gif
Labels: cla: yes

#2810 Update simple state management sample to provider 3.0
  examples/layout/base/lib/main.dart
  examples/state_mgmt/simple/pubspec.yaml
  examples/state_mgmt/simple/test/widget_test.dart
  src/docs/development/data-and-backend/state-mgmt/simple.md
  src/docs/development/ui/layout/tutorial.md
  src/docs/get-started/codelab.md
Labels: cla: yes

#2816 The 1.7 Flutter release.
  src/_includes/banner.html
  src/docs/deployment/android.md
  src/docs/index.md
  src/docs/whats-new-archive.md
Labels: cla: yes

#2814 Add a link from adaptations to a custom adaptation sample
  src/docs/resources/platform-adaptations.md
Labels: cla: yes

#2818 Added the missing link of Flutter’s build modes
  src/docs/testing/build-modes.md
Labels: cla: yes

#2821 Fix typo markdown link at faq doc
  src/docs/resources/faq.md
Labels: cla: yes

#2824 Fixing a broken link and a broken anchor.
  src/docs/cookbook/forms/focus.md
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2822 redirect fastlane-cd
  firebase.json
Labels: cla: yes

#2827 Updated position of Flutter community events rule
  src/brand.md
Labels: cla: yes

#2825 Update brand guidelines to include Event rule
  src/brand.md
Labels: cla: yes

#2832 Add `--split-per-abi` to size question
  src/docs/resources/faq.md
Labels: cla: yes

#2819 Added details about invoking platform channel APIs on the main thread.
  src/docs/development/platform-integration/platform-channels.md
Labels: cla: yes

#2842 Fix analyzer warning for listenable in Animation Tutorial
  examples/animation/animate2/lib/main.dart
  examples/animation/animate3/lib/main.dart
  examples/animation/animate5/lib/main.dart
Labels: cla: yes, tutorial

#2823 Added splash screen guide for Android.
  src/_assets/image/development/platform-integration/add-to-app-android/add-splash-screen/splash-screens_header.png
  src/_data/sidenav.yml
  src/docs/development/platform-integration/add-to-app-android/add-splash-screen.md
  src/docs/development/ui/assets-and-images.md
Labels: cla: yes

#2835 Add DevTools docs for Performance Page.
  src/_assets/image/tools/devtools/cpu_profiler_bottom_up.png
  src/_assets/image/tools/devtools/cpu_profiler_call_tree.png
  src/_assets/image/tools/devtools/cpu_profiler_flame_chart.png
  src/_assets/image/tools/devtools/timeline-dark-mode.png
  src/_assets/image/tools/devtools/timeline_cpu_profiler_bottom_up.png
  src/_assets/image/tools/devtools/timeline_cpu_profiler_call_tree.png
  src/_assets/image/tools/devtools/timeline_cpu_profiler_flame_chart.png
  src/_assets/image/tools/devtools/timeline_frame_rendering_chart.png
  src/_data/sidenav.yml
  src/docs/development/tools/devtools/performance.md
  src/docs/development/tools/devtools/timeline.md
Labels: cla: yes

#2843 travis CI: allow external links to fail
  .travis.yml
Labels: cla: yes

#2845 Layout basics fix
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#2848 normalize the json files in the widget catalog
  src/_data/catalog/index.json
  src/_data/catalog/widgets.json
Labels: cla: yes

#2850 Tweak the wording on the "Profile and release runs" include
  src/_includes/run-profile.md
Labels: cla: yes

#2841 Fix bugs
  firebase.json
  src/docs/deployment/android.md
  src/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app.md
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#2851 Updating info on size of Flutter engine
  src/docs/deployment/ios.md
  src/docs/resources/faq.md
Labels: cla: yes

#2854 Fixed the anchor.
  src/docs/development/packages-and-plugins/androidx-compatibility.md
Labels: cla: yes

#2858 Update link to the sample with newly landed url
  src/docs/development/data-and-backend/state-mgmt/simple.md
Labels: cla: yes

#2855 Update Docs: chromeos-abdroid-sdk-setup.md fix broken copy code
  src/docs/get-started/install/_chromeos-android-sdk-setup.md
Labels: cla: yes

#2859 Update reading-writing-files.md: getTemporaryDirectory returns NSCachesDirectory
  src/docs/cookbook/persistence/reading-writing-files.md
Labels: cla: yes

#2863 Update size of IPA on an iPhone X
  src/docs/resources/faq.md
Labels: cla: yes, iOS

#2861 issue 35703 documentation fix
  src/docs/development/packages-and-plugins/developing-packages.md
Labels: cla: yes

#2865 Updated Form-validation Documentation according to screenshot
  src/docs/cookbook/forms/validation.md
Labels: cla: yes

#2862 add physics simulation article to cookbook
  src/docs/cookbook/animation/animated-container.md
  src/docs/cookbook/animation/page-route-animation.md
  src/docs/cookbook/animation/physics-simulation.md
  src/images/cookbook/animation-physics-card-drag.gif
Labels: cla: yes

#2869 Update layout-basics.md
  src/docs/codelabs/layout-basics.md
Labels: cla: yes

#2798 Create guide for adding a FlutterFragment to an existing Android app.
  src/_assets/image/development/platform-integration/add-to-app-android/add-flutter-fragment/add-flutter-fragment_header.png
  src/_data/sidenav.yml
  src/docs/development/platform-integration/add-to-app-android/add-flutter-fragment.md
Labels: cla: yes
