Repository flutter/website, pull requests merged in 2019-02, with the labels that each got.

#2269 Update react-native-devs.md and Clear add-on space
  src/docs/get-started/flutter-for/react-native-devs.md
Labels: cla: yes

#2343 Add note to _config_now.yml
  _config_now.yml
Labels: cla: yes

#2353 Fix code excerpter
  tool/refresh-code-excerpts.sh
Labels: cla: yes

#2354 More state mgmt testing
  examples/state_mgmt/simple/lib/main.dart
  examples/state_mgmt/simple/lib/src/scoped_model.dart
  examples/state_mgmt/simple/pubspec.yaml
  src/docs/development/data-and-backend/state-mgmt/simple.md
Labels: cla: yes

#2355 Complete state testing
  examples/state_mgmt/simple/lib/main.dart
  examples/state_mgmt/simple/lib/src/common.dart
  examples/state_mgmt/simple/lib/src/passing_callbacks.dart
  examples/state_mgmt/simple/lib/src/performance.dart
  examples/state_mgmt/simple/lib/src/scoped_model.dart
  examples/state_mgmt/simple/lib/src/set_state.dart
  examples/state_mgmt/simple/pubspec.yaml
  examples/state_mgmt/simple/test/model_test.dart
  examples/state_mgmt/simple/test/widget_test.dart
  src/docs/development/data-and-backend/state-mgmt/simple.md
Labels: cla: yes

#2356 Ignore the tmp/ folder
  .gitignore
Labels: cla: yes

#2349 Add documentation on the AndroidX migration
  src/docs/development/packages-and-plugins/androidx-compatibility.md
Labels: cla: yes

#2362 Update AndroidX headings
  src/docs/development/packages-and-plugins/androidx-compatibility.md
Labels: cla: yes

#2359 Remove unnecessary VS Code relaunch step.
  src/docs/get-started/editor.md
Labels: cla: yes

#2369 Fixes #2013 - Remove unnecessary `async` keyword.
  src/docs/cookbook/persistence/reading-writing-files.md
Labels: cla: yes

#2368 Fixes #2342 -- Wrong command for running test.
  src/docs/cookbook/testing/unit/mocking.md
Labels: cla: yes

#2371 Corrected broken link
  src/docs/development/accessibility-and-localization/internationalization.md
Labels: cla: yes

#2358 Add info about x86 library to run-android section
  src/docs/resources/faq.md
Labels: cla: yes

#2336 Fix missing import in intent example
  src/docs/get-started/flutter-for/android-devs.md
Labels: cla: yes

#2335 Integration testing: Add test dependency
  src/docs/cookbook/testing/integration/introduction.md
Labels: cla: yes

#2379 Remove Q1 survey banner
  src/_includes/banner.html
Labels: cla: yes

#2375 Rephrasing and replacing URLs with macros.
  src/docs/development/packages-and-plugins/androidx-compatibility.md
Labels: cla: yes

#2351 Added Bitrise Flutter support
  src/docs/testing/index.md
Labels: cla: yes

#2376 State Management Options Docs Update for Bloc Package
  src/docs/development/data-and-backend/state-mgmt/options.md
Labels: cla: yes

#2380 Consolidate the testing page with recipes from the cookbook.
  .firebaserc
  src/_includes/testing_toc.md
  src/docs/testing/index.md
Labels: cla: yes

#2384 Fixed typo in json.md
  src/docs/development/data-and-backend/json.md
Labels: cla: yes

#2385 Add Flutter create page
  src/_assets/css/_create.scss
  src/_assets/css/_variables.scss
  src/_assets/css/main.scss
  src/_assets/image/create/create-hero-illo.png
  src/_assets/image/create/icon-beauty.png
  src/_assets/image/create/icon-code.png
  src/_assets/image/create/icon-execution.png
  src/_assets/image/create/icon-idea.png
  src/_assets/image/create/prize-home-max.png
  src/_assets/image/create/prize-home-mini.png
  src/_assets/image/create/prize-iMac.png
  src/create/index.html
Labels: cla: yes

#2386 Fix bad link to dartlang.org
  src/docs/development/packages-and-plugins/androidx-compatibility.md
Labels: cla: yes

#2390 Tweaking text
  src/create/index.html
Labels: cla: yes

#2405 Fixes a minor typo in the accessibility docs
  src/docs/development/accessibility-and-localization/accessibility.md
Labels: cla: yes

#2400 Double 'the' in description
  src/docs/cookbook/testing/integration/profiling.md
Labels: cla: yes

#2401 "specfies" poorly written.
  src/docs/cookbook/design/fonts.md
Labels: cla: yes

#2392 Fix a mistake of #2390
  src/create/index.html
Labels: cla: yes

#2402 Updated firebase project for publishing to .dev domain
  .firebaserc
  _config.yml
  firebase.json
Labels: cla: yes, e1-hours, p1-high

#2409 Revert "Updated firebase project for publishing to .dev domain"
  .firebaserc
  _config.yml
  firebase.json
Labels: cla: yes

#2410 Various little tweaks to the create challenge
  src/create/index.html
Labels: cla: yes

#2407 Update deploy script to publish to flutter.dev
  .firebaserc
  _config.yml
  firebase.json
  src/docs/development/tools/vs-code.md
  tool/build_check_deploy.sh
Labels: cla: no

#2417 Fixing incorrect firebase project name...
  .firebaserc
Labels: cla: no

#2420 Text tweak
  src/create/index.html
Labels: cla: yes

#2423 some updates related to devtools
  src/docs/development/tools/android-studio.md
  src/docs/development/tools/vs-code.md
  src/docs/testing/ui-performance/index.md
Labels: cla: yes

#2415 Update the banner with Flutter Create contest
  src/_includes/banner.html
Labels: cla: yes

#2421 Fix small markdown rendering error
  src/docs/development/ui/layout/index.md
Labels: cla: yes

#2422 fixed androidx-compatibility.md error
  src/docs/development/packages-and-plugins/androidx-compatibility.md
Labels: cla: yes

#2431 Tweaking text
  src/create/index.html
Labels: cla: yes

#2429 change meta tags for flutter create
  src/create/index.html
  src/images/flutter-create-social.png
Labels: cla: yes

#2433 Removing the 1.0 announcement from the banner.
  src/_includes/banner.html
  src/create/index.html
Labels: cla: yes

#2434 Change twitter card to card with large image
  src/_includes/head.html
Labels: cla: yes

#2426 Update link to focused tab according selected IDE
  src/docs/development/tools/android-studio.md
  src/docs/development/tools/vs-code.md
Labels: cla: yes

#2424 SQLite recipe
  example/pubspec.yaml
  src/docs/cookbook/networking/web-sockets.md
  src/docs/cookbook/persistence/reading-writing-files.md
  src/docs/cookbook/persistence/sqlite.md
Labels: cla: yes

#2440 Update internationalization.md
  src/docs/development/accessibility-and-localization/internationalization.md
Labels: cla: yes

#2448 Some general cleanup and incorporating the DevTools into the site.
  src/_data/sidenav.yml
  src/docs/development/tools/inspector.md
  src/docs/index.md
  src/docs/whats-new-archive.md
Labels: cla: yes

#2449 Update simple.md
  src/docs/development/data-and-backend/state-mgmt/simple.md
Labels: cla: yes
