Repository flutter/website, pull requests merged in 2021-02, with the labels that each got.

#5242 Fixes for dryLayout breaking change guide
  src/docs/release/breaking-changes/renderbox-dry-layout.md
  src/docs/release/breaking-changes/template.md
Labels: cla: yes

#5252 Typo in website/src/docs/get-started/web.md
  src/docs/get-started/web.md
Labels: cla: yes

#5250 Update web-images.md
  src/docs/development/platform-integration/web-images.md
Labels: cla: yes

#5248 Update flutter artifacts bucket
  src/_assets/js/archive.js
  src/_assets_old/js/archive.js
  src/community/china.md
Labels: cla: yes

#5253 Revert "Update flutter artifacts bucket"
  src/_assets/js/archive.js
  src/_assets_old/js/archive.js
  src/community/china.md
Labels: cla: yes

#5240 Un-deprecate scrollable alert dialog by default
  src/docs/release/breaking-changes/scrollable-alert-dialog.md
Labels: cla: yes

#5254 Updating banner
  src/_includes/banner.html
Labels: cla: yes

#5221 Add content to docs/perf
  src/_data/sidenav.yml
  src/docs/perf/appendix.md
  src/docs/perf/faq.md
  src/docs/perf/index.md
  src/docs/perf/metrics.md
Labels: cla: no

#5227 Migrate Layout Basics Codelab to Null Safety
  src/docs/codelabs/layout-basics_migrated.md
Labels: cla: yes

#5202 Pass a URI to package:http API
  src/docs/cookbook/networking/fetch-data.md
  src/docs/cookbook/networking/send-data.md
Labels: cla: yes

#5256 Adding warning about hot reload unavailabe in web
  src/docs/get-started/web.md
  src/web.md
Labels: cla: yes

#5258 Adding skips to layout-basics_migrated.md
  src/docs/codelabs/layout-basics_migrated.md
  src/docs/cookbook/networking/fetch-data.md
  src/docs/cookbook/networking/send-data.md
Labels: cla: yes

#5210 Remove Duplicate Command in flutter-cli.md
  src/docs/reference/flutter-cli.md
Labels: cla: yes

#5262 Fixing image links in layout basics codelab.
  src/docs/codelabs/layout-basics.md
  src/docs/codelabs/layout-basics_migrated.md
Labels: cla: yes

#5259 Adding CORS headers to cookbook image files
  firebase.json
Labels: cla: yes

#5263 Include section about MD for Android
  src/docs/deployment/android.md
Labels: cla: yes

#5166 Update index.md
  examples/integration_test/integration_test/counter_test.dart
  src/docs/testing/integration-tests/index.md
Labels: cla: yes

#5244 Add deep linking page
  src/_data/sidenav.yml
  src/docs/development/ui/navigation/deep-linking.md
  src/docs/development/ui/navigation/index.md
Labels: cla: yes

#5265 Change the docs of integration test
  src/docs/testing/integration-tests/index.md
Labels: cla: yes

#5271 Add ecosystem job posting
  src/jobs/ecosystem.html
Labels: cla: yes

#5268 Windows MSIX instructions
  src/desktop.md
Labels: cla: yes

#5251 Update picture-using-camera.md
  example/pubspec.yaml
  src/docs/cookbook/plugins/picture-using-camera.md
Labels: cla: yes

#5266 Reland update flutter artifacts bucket.
  src/_assets/js/archive.js
  src/_assets_old/js/archive.js
  src/community/china.md
Labels: cla: yes

#5274 Add engine job posting
  src/jobs/engine.html
Labels: cla: yes

#5267 Update error reporting guide
  src/docs/cookbook/maintenance/error-reporting.md
Labels: cla: yes

#5247 Doc for multiple Flutters
  src/_assets/image/development/add-to-app/multiple-flutters-sample.gif
  src/_data/sidenav.yml
  src/docs/development/add-to-app/index.md
  src/docs/development/add-to-app/multiple-flutters.md
  src/docs/development/add-to-app/performance.md
Labels: cla: yes

#5278 Removed important note
  src/docs/development/packages-and-plugins/developing-packages.md
Labels: cla: yes

#5282 Jobs
  firebase.json
  src/_includes/banner.html
  src/jobs/index.md
Labels: cla: yes

#5276 Add notes to macOS distribution section
  src/desktop.md
Labels: cla: yes

#5281 Fix to 'unsecured connection not allowed'
  src/docs/cookbook/networking/web-sockets.md
Labels: cla: yes

#5284 Known null safety issues
  src/docs/null-safety.md
Labels: cla: yes

#5283 Update the list of contribution in adopt a widget
  src/adoptawidget/index.md
Labels: cla: yes

#5288 Entitlements -> entitlements
  src/desktop.md
Labels: cla: yes

#5289 fixing typo in deeplinking document
  src/docs/development/ui/navigation/deep-linking.md
Labels: cla: yes

#5302 Update create instructions
  src/desktop.md
Labels: cla: yes

#5300 Update flutter doctor output
  src/desktop.md
Labels: cla: yes

#5298 Documenting macOS Flutter app distribution options
  src/desktop.md
Labels: cla: yes

#5301 Fix typos in src/docs/development/add-to-app/multiple-flutters.md
  src/docs/development/add-to-app/multiple-flutters.md
Labels: cla: yes

#5294 Update Adopt a Widget contributions list
  src/adoptawidget/index.md
Labels: cla: yes

#5290 Add DraggableScrollableSheet
  src/_data/catalog/widgets.json
Labels: cla: yes

#5287 Adding definition of plugins vs packages
  src/docs/development/packages-and-plugins/using-packages.md
Labels: cla: yes

#5303 Update cookbook
  src/_assets/image/cookbook/effects/expandable-fab_closed.png
  src/_assets/image/cookbook/effects/expandable-fab_open.png
  src/_includes/null-safe-recipe.md
  src/docs/cookbook/effects/expandable-fab.md
  src/docs/cookbook/effects/index.md
  src/docs/cookbook/forms/retrieve-input.md
  src/docs/cookbook/gestures/ripples.md
Labels: cla: yes

#5052 Documentation: update "Build and release a Linux app"
  src/docs/deployment/linux.md
Labels: cla: yes

#5309 Fixing null safe code to remove warning
  src/docs/cookbook/effects/expandable-fab.md
Labels: cla: yes

#5317 Migrate Implicit Animations Codelab to Null Safety
  examples/animation/implicit_migrated/container0/lib/main.dart
  examples/animation/implicit_migrated/container1/lib/main.dart
  examples/animation/implicit_migrated/container10/lib/main.dart
  examples/animation/implicit_migrated/container2/lib/main.dart
  examples/animation/implicit_migrated/container3/lib/main.dart
  examples/animation/implicit_migrated/container4/lib/main.dart
  examples/animation/implicit_migrated/container5/lib/main.dart
  examples/animation/implicit_migrated/container6/lib/main.dart
  examples/animation/implicit_migrated/container9/lib/main.dart
  examples/animation/implicit_migrated/opacity0/lib/main.dart
  examples/animation/implicit_migrated/opacity1/lib/main.dart
  examples/animation/implicit_migrated/opacity10/lib/main.dart
  examples/animation/implicit_migrated/opacity2/lib/main.dart
  examples/animation/implicit_migrated/opacity3/lib/main.dart
  examples/animation/implicit_migrated/opacity4/lib/main.dart
  examples/animation/implicit_migrated/opacity5/lib/main.dart
  examples/animation/implicit_migrated/opacity9/lib/main.dart
  src/_includes/implicit-animations_migrated/fade-in-complete.md
  src/_includes/implicit-animations_migrated/fade-in-starter-code.md
  src/_includes/implicit-animations_migrated/shape-shifting-complete.md
  src/_includes/implicit-animations_migrated/shape-shifting-starter-code.md
  src/docs/codelabs/implicit-animations_migrated.md
Labels: cla: yes

#5320 Update banner.html
  src/_includes/banner.html
Labels: cla: yes

#5312 Page is all about deploying Flutter to the Snap Store
  src/docs/deployment/linux.md
Labels: cla: yes

#5321 Mention error messages should be mentioned in breaking change template
  src/docs/release/breaking-changes/template.md
Labels: cla: yes

#5332 Fix link section in Linux Snap page
  src/docs/deployment/linux.md
Labels: cla: yes

#5336 Fix router sample url
  src/docs/development/ui/navigation/deep-linking.md
Labels: cla: yes

#5330 Update firebase.json
  firebase.json
Labels: cla: yes

#5325 Migrate Explicit Animations Codelab to Null Safety
  examples/animation/explicit_migrated/explicit1/lib/main.dart
  examples/animation/explicit_migrated/explicit2/lib/main.dart
  examples/animation/explicit_migrated/explicit3/lib/main.dart
  examples/animation/explicit_migrated/explicit4/lib/main.dart
  examples/animation/explicit_migrated/explicit5/lib/main.dart
  examples/animation/explicit_migrated/explicit6/lib/main.dart
  src/_includes/explicit-animations_migrated/animation-controller-starter-code-1.md
  src/_includes/explicit-animations_migrated/bouncing-ball-starter-code-1.md
  src/_includes/explicit-animations_migrated/bouncing-ball-starter-code-2.md
  src/_includes/explicit-animations_migrated/bouncing-ball-starter-code-3.md
  src/_includes/explicit-animations_migrated/bouncing-ball-starter-code-4.md
  src/_includes/explicit-animations_migrated/bouncing-ball-starter-code-5.md
  src/docs/codelabs/explicit-animations_migrated.md
Labels: cla: yes

#5314 Migrate to GitHub Actions
  .cirrus-disabled.yml
  .github/workflows/build.yml
  .travis.yml
  README.md
  tool/before-install.sh
  tool/check-code.sh
Labels: cla: yes

#5326 Grammar fix
  src/docs/resources/faq.md
Labels: cla: yes

#5338 Update known limitations section of null-safety.md
  src/docs/null-safety.md
Labels: cla: yes

#5333 Document Linux distribution requirements
  src/desktop.md
Labels: cla: yes

#5125 Migration Guide for Deprecations removed since last stable release (1.22)
  src/docs/release/breaking-changes/1-22-deprecations.md
  src/docs/release/breaking-changes/index.md
Labels: cla: yes

#5340 Emphasise VS Code
  src/desktop.md
Labels: cla: yes

#5342 Update takePicture() docs in cookbook.
  src/docs/cookbook/plugins/picture-using-camera.md
Labels: cla: yes

#5313 Migrate Web Codelab to Null Safety
  src/docs/get-started/codelab-web_migrated.md
Labels: cla: yes

#5348 Add supported fonts to custom font page
  src/docs/cookbook/design/fonts.md
Labels: cla: yes

#5349 Update the survey date for Q1 2021
  src/f/flutter-survey-metadata.json
Labels: cla: yes

#5346 Returning to an old PR - beefing up template
  README.md
  src/docs/release/breaking-changes/template.md
Labels: cla: yes

#5345 Includes download links for the Philips Hue app
  src/_data/showcases.yml
Labels: cla: yes

#4304 Update splash-screen.md
  src/docs/development/ui/advanced/splash-screen.md
Labels: cla: yes

#4507 Show the proper FlutterActivity import
  src/docs/development/add-to-app/android/add-flutter-screen.md
Labels: cla: yes

#5352 Updated Provider Package
  examples/state_mgmt/simple/pubspec.yaml
Labels: cla: yes

#5199 TextEditingController.buildTextSpan migration guide
  src/docs/release/breaking-changes/buildtextspan-buildcontext.md
Labels: cla: yes

#5324 updating provider package version number
  src/docs/development/data-and-backend/state-mgmt/simple.md
Labels: cla: yes

#5353 Adding a recipe
  NOT-YET
  src/_assets/image/cookbook/effects/DownloadButton.gif
  src/_assets/image/cookbook/effects/DragAUIElement.gif
  src/_assets/image/cookbook/effects/ExpandingFAB.gif
  src/_assets/image/cookbook/effects/TypingIndicator.gif
  src/_assets/image/cookbook/effects/expandable-fab_closed.png
  src/_assets/image/cookbook/effects/expandable-fab_open.png
  src/_assets/image/cookbook/effects/loading-shimmer.gif
  src/docs/cookbook/design/tabs.md
  src/docs/cookbook/effects/download-button.md
  src/docs/cookbook/effects/drag-a-widget.md
  src/docs/cookbook/effects/expandable-fab.md
  src/docs/cookbook/effects/typing-indicator.md
  src/docs/cookbook/gestures/ripples.md
Labels: cla: yes

#5341 Add flokk to samples and codelabs
  src/desktop.md
Labels: cla: yes

#5354 Updating the PR template
  NOT-YET
  backup-pr-template.md
  pull_request_template.md
Labels: cla: yes

#5195 Mark `dart:ffi` as stable
  src/docs/development/platform-integration/c-interop.md
Labels: cla: yes, ⚠ WIP
