Repository flutter/website, pull requests merged in 2022-12, with the labels that each got.

#7924 fixed typo
  src/codelabs/implicit-animations.md
Labels: RFM

#7963 Material 3 updates page
  src/_data/sidenav.yml
  src/development/ui/material3-updates.md
Labels: review:copy

#7867 Flavors documentation update
  src/assets/images/docs/flavors/podfile-config.png
  src/assets/images/docs/flavors/step-1-using-flavors-free.png
  src/assets/images/docs/flavors/step-2-using-flavors-free.png
  src/assets/images/docs/flavors/step-5-ios-scheme-free.png
  src/assets/images/docs/flavors/step3-ios-build-config.png
  src/assets/images/docs/flavors/step3-using-flavors.png
  src/deployment/flavors.md
Labels: review:copy

#8003 Addresses some validator warnings and improves whitespace handling in header
  src/_layouts/base.html
  src/_layouts/default.html
  src/_layouts/landing.html
Labels: RFM

#7736 Adding SwiftUI concepts and examples to iOS getting started doc
  examples/get-started/flutter-for/ios_devs/lib/canvas.dart
  examples/get-started/flutter-for/ios_devs/lib/column.dart
  examples/get-started/flutter-for/ios_devs/lib/cupertino_themes.dart
  examples/get-started/flutter-for/ios_devs/lib/get_started.dart
  examples/get-started/flutter-for/ios_devs/lib/grid.dart
  examples/get-started/flutter-for/ios_devs/lib/image.dart
  examples/get-started/flutter-for/ios_devs/lib/list.dart
  examples/get-started/flutter-for/ios_devs/lib/navigation.dart
  examples/get-started/flutter-for/ios_devs/lib/openapp.dart
  examples/get-started/flutter-for/ios_devs/lib/popback.dart
  examples/get-started/flutter-for/ios_devs/lib/row.dart
  examples/get-started/flutter-for/ios_devs/lib/scroll.dart
  examples/get-started/flutter-for/ios_devs/lib/simple_animation.dart
  examples/get-started/flutter-for/ios_devs/lib/state.dart
  examples/get-started/flutter-for/ios_devs/lib/stylingbutton.dart
  examples/get-started/flutter-for/ios_devs/lib/text_button.dart
  examples/get-started/flutter-for/ios_devs/pubspec.yaml
  src/_sass/base/_bootstrap_adjust.scss
  src/assets/images/docs/get-started/ios/flutter-widgets.png
  src/assets/images/docs/get-started/ios/swiftui-modifiers.png
  src/get-started/flutter-for/ios-devs.md
Labels: review:copy

#8010 Update directory listing of release-build structure
  src/deployment/web.md
Labels: review:tech
