Repository flutter/website, pull requests merged in 2022-11, with the labels that each got.

#7610 Zero To Hero Video Series
  src/resources/videos.md
Labels: cla: yes, review:copy

#7694 Create migration guide for RouteSettings.copywith
  src/release/breaking-changes/index.md
  src/release/breaking-changes/routesettings-copywith-migration.md
Labels: review:copy

#7705 Add a migration guide for some maybeOf conversions
  src/release/breaking-changes/index.md
  src/release/breaking-changes/supplemental-maybeOf-migration.md
Labels: review:copy

#7656 Clarify note about IDE formatting imports
  src/get-started/codelab.md
Labels: RFM

#7737 Adds optimizations to Docker Build
  Dockerfile
  Makefile
  docker-compose.yml
  package-lock.json
  package.json
  tool/check-code.sh
  tool/config/linkcheck-skip-list.txt
Labels: infrastructure, review:tech

#7746 Remove npm upgrade, update build action versions
  .github/workflows/build.yml
  Dockerfile
Labels: review:tech

#7703 A11y changes
  src/development/accessibility-and-localization/accessibility.md
  src/get-started/codelab.md
Labels: review:tech

#7814 Fix typo
  src/development/platform-integration/platform-channels.md
Labels: RFM

#7811 Update deep-linking.md
  src/development/ui/navigation/deep-linking.md
Labels: RFM

#7820 Update firebase.json
  firebase.json
Labels: review:tech

#7739 Changed Docker settings to allow Dart and Flutter websites to both run locally
  Dockerfile
  Makefile
  docker-compose.yml
Labels: infrastructure

#7829 Tweaking the banner
  src/_includes/banner.html
Labels: RFM

#7838 Fix error in explicit animations codelab and cleanup related JS
  src/assets/js/codelabs/animations_examples.js
  src/codelabs/explicit-animations.md
Labels: review:tech

#7747 Adding Apple frameworks > flutter plugins doc
  src/_data/sidenav.yml
  src/development/platform-integration/ios/apple-frameworks.md
Labels: RFM

#7859 Fix broken testing cookbox toc and anchor links
  src/_includes/docs/cookbook-toc.md
Labels: RFM

#7860 Fix capitalization in "Using the Performance view"
  src/development/tools/devtools/performance.md
Labels: RFM

#7861 Remove documentation about handleStatusBarTouches
  src/development/add-to-app/ios/add-flutter-screen.md
Labels: RFM

#7846 Preconnecting to font files.
  src/_layouts/base.html
Labels: review:tech

#7879 clarify Android S requirements for splashscreen
  src/development/ui/advanced/splash-screen.md
Labels: review:copy

#7870 Update tutorial for intl: 0.17.0
  examples/internationalization/intl_example/lib/main.dart
Labels: waiting for customer response

#7845 Optimizing web load speed 🚀
  src/_layouts/base.html
Labels: review:tech
