Repository flutter/website, pull requests merged in 2023-08, with the labels that each got.

#9175 Cleanup codelab description
  src/codelabs/index.md
Labels: review.copy

#9182 Move automatic platform adaptations to 'Platform integration'
  firebase.json
  src/_data/sidenav.yml
  src/get-started/flutter-for/dart-swift-concurrency.md
  src/get-started/flutter-for/swiftui-devs.md
  src/get-started/flutter-for/uikit-devs.md
  src/platform-integration/platform-adaptations.md
  src/platform-integration/platform-channels.md
  src/release/whats-new.md
  src/ui/layout/responsive/adaptive-responsive.md
Labels: review.copy

#9177 Give online courses its own page
  src/_data/sidenav.yml
  src/resources/courses.md
  src/resources/videos.md
Labels: review.copy

#9174 Reduce stage expiration time
  .github/workflows/stage.yml
Labels: infra.general

#9180 Clarified IDE plugin support
  src/get-started/editor.md
  src/get-started/test-drive/_androidstudio.md
  src/get-started/test-drive/_terminal.md
  src/get-started/test-drive/_vscode.md
  src/get-started/test-drive/index.md
Labels: st.RFM

#9172 Be explicit about how to invoke `ensureSemantics()`
  src/accessibility-and-localization/accessibility.md
Labels: review.tech

#9157 Make video player example runnable
  src/cookbook/plugins/play-video.md
Labels: st.RFM

#9176 Add extra verification for firebase.json
  tool/check-links.sh
  tool/verify_firebase_json.dart
Labels: infra.structure

#8952 Migration guide for predictive back
  src/release/breaking-changes/android-predictive-back.md
  src/release/breaking-changes/index.md
Labels: act.merge-to-next

#9204 Move 'Accessibility & localization' under UI
  firebase.json
  src/_data/clock/faqs.yml
  src/_data/sidenav.yml
  src/get-started/flutter-for/uikit-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/reference/tutorials.md
  src/release/breaking-changes/cupertino-tab-bar-localizations.md
  src/release/breaking-changes/text-field-material-localizations.md
  src/release/whats-new.md
  src/resources/faq.md
  src/ui/accessibility-and-localization/accessibility.md
  src/ui/accessibility-and-localization/index.md
  src/ui/accessibility-and-localization/internationalization.md
Labels: review.copy

#9205 feat: Add hover styles to TOC entries
  src/_sass/components/_toc.scss
Labels: review.await-update

#9216 Updates labels for Dependabot
  .github/dependabot.yml
Labels: infra.structure, st.RFM, lang.yaml

#9202 Add CupertinoPageRoute to Navigation Basics example
  examples/cookbook/navigation/navigation_basics/lib/main_cupertino.dart
  src/assets/images/docs/cookbook/navigation-basics-cupertino.gif
  src/cookbook/navigation/navigation-basics.md
Labels: st.RFM

#9256 Add a new banner for Flutter 3.13
  src/_includes/banner.html
Labels: review.copy

#9274 Fix build by marking beta as experimental
  .github/workflows/build.yml
Labels: st.RFM

#9275 Changed logo to SVG
  src/_includes/header.html
Labels: infra.design

#9276 Updated Xcode license flag
  src/get-started/install/_ios-setup.md
Labels: st.RFM.%, ed.xcode

#9278 Change "flutter pub run" to "dart run" on JSON serialization page
  src/data-and-backend/serialization/json.md
Labels: cla: no

#9281 Fix enhanced enums link on describe-enum migration guide
  src/release/breaking-changes/describe-enum.md
Labels: review.copy

#9213 Fix Bottom Overflow issue
  examples/animation/implicit/opacity1/lib/main.dart
  examples/animation/implicit/opacity2/lib/main.dart
  examples/animation/implicit/opacity3/lib/main.dart
  examples/animation/implicit/opacity4/lib/main.dart
  examples/animation/implicit/opacity5/lib/main.dart
  src/_includes/docs/implicit-animations/fade-in-complete.md
  src/_includes/docs/implicit-animations/fade-in-starter-code.md
  src/codelabs/implicit-animations.md
Labels: st.RFM.%

#9087 Improve Linux Install 4: Update PATH install section
  src/get-started/install/_path-linux-chromeos.md
Labels: a.get-started, st.RFM, devos.Linux

#9288 Updated customer label
  .github/workflows/no-response.yaml
Labels: infra.structure, review.tech

#9290 Added overview videos
  src/get-started/flutter-for/swiftui-devs.md
  src/get-started/flutter-for/uikit-devs.md
Labels: target.iOS, fix.video

#9302 Replaced flutter pub run with dart run
  src/cookbook/testing/unit/mocking.md
  src/packages-and-plugins/developing-packages.md
Labels: fix.copy, review.tech

#9081 Improve Linux Install 1: Add links to Linux requirements in _linux-desktop-setup.md
  src/get-started/install/_linux-desktop-setup.md
Labels: a.get-started, st.RFM, devos.Linux

#9296 Add arb-editor reference to i18n docs
  src/ui/accessibility-and-localization/internationalization.md
Labels: st.RFM

#9308 🔥 Use `flutter pub get` instead of `flutter packages get`
  tool/check-code.sh
  tool/refresh-code-excerpts.sh
Labels: infra.structure

#9305 Removes `time` measurement from the `Makefile`
  Makefile
Labels: infra.structure

#9303 Update twitter logo
  src/assets/images/social/twitter.svg
Labels: cla: yes

#9318 Fix duplicate Linux requirements from recent change
  src/_includes/docs/linux-requirements-command.md
  src/_includes/docs/linux-requirements-list.md
  src/get-started/install/_linux-desktop-setup.md
Labels: review.copy

#9322 Add missing redirect for old supported platforms location
  firebase.json
Labels: review.copy

#9324 Replace Font Awesome brand logos with SVG
  src/assets/images/docs/brand-svg/chromeos.svg
  src/assets/images/docs/brand-svg/linux.svg
  src/assets/images/docs/brand-svg/macos.svg
  src/assets/images/docs/brand-svg/windows.svg
  src/get-started/install/index.md
Labels: review.tech

#9334 Add DevTools 2.27.0 release notes.
  src/tools/devtools/release-notes/images-2.27.0/truncation.png
  src/tools/devtools/release-notes/index.md
  src/tools/devtools/release-notes/release-notes-2.27.0-src.md
  src/tools/devtools/release-notes/release-notes-2.27.0.md
Labels: st.blocked, review.copy
