Repository flutter/website, pull requests merged in 2023-12, with the labels that each got.

#9881 Adding info about SuperDash game
  src/_includes/banner.html
  src/resources/games-toolkit.md
Labels: fix.link

#9884 Update editor.md
  src/get-started/editor.md
Labels: cla: yes, st.RFM

#9740 Update misleading comment in code snippet in background-parsing.md
  examples/cookbook/networking/background_parsing/lib/main_step3.dart
  src/cookbook/networking/background-parsing.md
Labels: st.RFM

#9893 Update layout tutorial for current best practices
  examples/layout/base/lib/main.dart
  examples/layout/lakes/interactive/lib/main.dart
  examples/layout/lakes/step2/lib/main.dart
  examples/layout/lakes/step3/lib/main.dart
  examples/layout/lakes/step4/lib/main.dart
  examples/layout/lakes/step5/lib/main.dart
  examples/layout/lakes/step5/test/widget_test.dart
  examples/testing/integration_tests/how_to/android/local.properties
  src/_includes/docs/app-figure.md
  src/_sass/base/_base.scss
  src/assets/images/docs/ui/layout/layout-demo-app.png
  src/assets/images/docs/ui/layout/layout-sketch-add-text-block.svg
  src/assets/images/docs/ui/layout/layout-sketch-button-block-unlabeled.svg
  src/assets/images/docs/ui/layout/layout-sketch-button-block.svg
  src/assets/images/docs/ui/layout/layout-sketch-intro.svg
  src/assets/images/docs/ui/layout/layout-sketch-title-block-unlabeled.svg
  src/assets/images/docs/ui/layout/layout-sketch-title-block.svg
  src/assets/images/docs/ui/layout/layout-sketch.svg
  src/ui/interactivity/index.md
  src/ui/layout/index.md
  src/ui/layout/tutorial.md
Labels: review.copy

#9937 Restore "Update layout tutorial for current best practices" with updates
  examples/layout/base/lib/main.dart
  examples/layout/lakes/interactive/lib/main.dart
  examples/layout/lakes/step2/lib/main.dart
  examples/layout/lakes/step3/lib/main.dart
  examples/layout/lakes/step4/lib/main.dart
  examples/layout/lakes/step5/lib/main.dart
  examples/layout/lakes/step5/test/widget_test.dart
  examples/layout/lakes/step6/lib/main.dart
  examples/testing/integration_tests/how_to/android/local.properties
  firebase.json
  src/_includes/docs/app-figure.liquid
  src/_includes/docs/app-figure.md
  src/_sass/base/_base.scss
  src/assets/images/docs/ui/layout/layout-demo-app.png
  src/assets/images/docs/ui/layout/layout-sketch-add-text-block.svg
  src/assets/images/docs/ui/layout/layout-sketch-button-block-unlabeled.svg
  src/assets/images/docs/ui/layout/layout-sketch-button-block.svg
  src/assets/images/docs/ui/layout/layout-sketch-intro.svg
  src/assets/images/docs/ui/layout/layout-sketch-title-block-unlabeled.svg
  src/assets/images/docs/ui/layout/layout-sketch-title-block.svg
  src/assets/images/docs/ui/layout/layout-sketch.svg
  src/f/dart-devtools-survey-metadata.json
  src/ui/interactivity/index.md
  src/ui/layout/index.md
  src/ui/layout/tutorial.md
Labels: review.await-update

#9238 Windows Getting Started POC
  _config.yml
  src/_data/sidenav.yml
  src/_includes/docs/help-link.md
  src/_includes/docs/install/admonitions/install-paths.md
  src/_includes/docs/install/compiler/android.md
  src/_includes/docs/install/devices/android-emulator.md
  src/_includes/docs/install/devices/android-physical.md
  src/_includes/docs/install/flutter-doctor-success.md
  src/_includes/docs/install/flutter-doctor.md
  src/_includes/docs/install/flutter-sdk.md
  src/_includes/docs/install/flutter/download.md
  src/_includes/docs/install/flutter/vscode.md
  src/_includes/docs/install/reqs/windows/base.md
  src/_includes/docs/install/reqs/windows/software.md
  src/_includes/docs/install/reqs/windows/storage.md
  src/_sass/base/_base.scss
  src/_sass/components/_admonitions.scss
  src/_sass/site.scss
  src/assets/js/archive.js
  src/assets/js/main.js
  src/get-started/install/_android-setup.md
  src/get-started/install/index.md
  src/get-started/install/windows.md
  src/get-started/install/windows/desktop.md
  src/get-started/install/windows/index.md
  src/get-started/install/windows/mobile.md
  src/get-started/install/windows/web.md
  src/resources/games-toolkit.md
Labels: a.get-started, act.await-dev-pr, st.RFM.%

#9958 Remove hanging `<`
  src/cookbook/games/achievements-leaderboard.md
Labels: st.RFM

#9955 Update Video links on Firebase page
  src/data-and-backend/firebase.md
Labels: review.await-update

#9959 Added links to tracking video examples
  src/tools/devtools/performance.md
Labels: review.copy

#9960 Added note to horizontal list recipe
  src/cookbook/lists/horizontal-list.md
Labels: review.copy

#9968 Changed Flutter verify instructions
  src/get-started/editor.md
Labels: review.copy

#9969 Reduced Material widget descriptions to less than 25 words
  src/_data/catalog/widgets.json
Labels: review.copy

#9973 Added centralized repos in Gradle step
  src/add-to-app/android/project-setup.md
Labels: review.copy
