Repository flutter/website, pull requests merged in 2023-06, with the labels that each got.

#8797 fix broken link
  src/release/breaking-changes/form-field-autovalidation-api.md
Labels: RFM

#8817 Remove from the image the empty circle
  src/assets/images/docs/development/tools/android-studio-run-controls.png
Labels: RFM

#8810 Adjust tools in sidenav
  src/_data/sidenav.yml
  src/tools/android-studio.md
  src/tools/flutter-fix.md
  src/tools/formatting.md
Labels: design

#8807 Simplify 'Samples & tutorials' top-level category
  src/_data/sidenav.yml
Labels: RFM

#8806 Convert add-to-app docs to task orientated
  src/_data/sidenav.yml
  src/add-to-app/android/add-flutter-fragment.md
  src/add-to-app/android/add-flutter-screen.md
  src/add-to-app/android/add-flutter-view.md
  src/add-to-app/android/index.md
  src/add-to-app/android/plugin-setup.md
  src/add-to-app/debugging.md
  src/add-to-app/ios/add-flutter-screen.md
  src/add-to-app/ios/index.md
  src/add-to-app/multiple-flutters.md
Labels: RFM

#8813 Task-orientated platform integration titles
  src/_data/sidenav.yml
Labels: review:copy

#8771 Update React Native code style
  src/get-started/flutter-for/react-native-devs.md
Labels: cla: yes, a.dev-from-to, t.native-code

#8804 Add more details about Firebase hosting
  src/deployment/web.md
Labels: review.copy

#8710 Correct asset variant documentation
  examples/ui/assets_and_images/assets/background.png
  examples/ui/assets_and_images/assets/my_icon.png
  examples/ui/assets_and_images/lib/main.dart
  examples/ui/assets_and_images/pubspec.yaml
  src/ui/assets-and-images.md
Labels: review.tech

#8837 Adds explanation for .arb file
  src/accessibility-and-localization/internationalization.md
Labels: review.copy

#8860 Fix "Migrating from flutter_driver" content error
  src/release/breaking-changes/flutter-driver-migration.md
Labels: RFM, co.volunteer

#8846 Change RenderBinding to SemanticsBinding
  src/accessibility-and-localization/accessibility.md
Labels: review.tech

#8840 Add missing code in native iOS views of Flutter Platform Views
  src/platform-integration/ios/platform-views.md
Labels: RFM, target.ios, l.native-code

#8863 Add external drag and drop proposal
  firebase.json
Labels: RFM

#8715 Add a help page for installing Flutter
  src/assets/images/docs/get-started/install_android_tools.png
  src/get-started/install/help.md
Labels: a.install

#8852 Note that path_provider doesn't work on web apps
  src/cookbook/persistence/reading-writing-files.md
Labels: RFM%

#8868 Fix typos in packages-and-plugins/developing-packages.md
  src/packages-and-plugins/developing-packages.md
Labels: cla: yes

#8867 Update flutter_reactive_widget -> flutter_reactive_value
  src/data-and-backend/state-mgmt/options.md
Labels: RFM

#8866 Updated Happy Paths program pause notification
  src/packages-and-plugins/happy-paths/index.md
Labels: RFM

#8876 Indicate Android SDK 31 is supported
  src/reference/supported-platforms.md
Labels: RFM

#8833 Remove Android bits and add limitations on ios platform views
  src/platform-integration/ios/platform-views.md
Labels: review.await-update, target.ios

#8875 Correct MainActivity.kt with plugin-safe code
  src/platform-integration/android/platform-views.md
Labels: RFM

#8847 Fix RiverPod passage
  src/data-and-backend/state-mgmt/options.md
Labels: RFM%

#8845 Explaining multiple gesture detectors
  src/ui/advanced/gestures.md
Labels: RFM%

#8877 Clarify use of angle brackets
  src/deployment/android.md
Labels: review.copy

#8887 Reintroduce titles to code snippets without excerpts
  src/add-to-app/android/_initial-route-cached-engine.md
  src/add-to-app/android/add-flutter-fragment.md
  src/add-to-app/android/add-flutter-screen.md
  src/add-to-app/android/plugin-setup.md
  src/add-to-app/android/project-setup.md
  src/add-to-app/ios/add-flutter-screen.md
  src/add-to-app/ios/project-setup.md
  src/platform-integration/android/splash-screen.md
  src/platform-integration/platform-channels.md
  src/release/breaking-changes/plugin-api-migration.md
Labels: RFM

#8888 Change to launch screen for iOS
  firebase.json
  src/_data/sidenav.yml
  src/platform-integration/ios/launch-screen.md
Labels: RFM%

#8902 Update `video_player` warning for iOS simulators
  src/cookbook/plugins/play-video.md
Labels: review.copy

#8901 Removed duplicate test drive section
  src/get-started/install/_ios-setup.md
Labels: review.copy

#8925 Add Go link to Missing Features to Selection Controls document
  firebase.json
Labels: RFM

#8935 Fixes non-parallax example
  examples/cookbook/effects/parallax_scrolling/lib/excerpt2.dart
  src/cookbook/effects/parallax-scrolling.md
Labels: RFM

#8936 Fixed test drive iOS images
  src/assets/images/docs/get-started/ios/starter-app.png
  src/assets/images/docs/tools/vs-code/device_status_bar.png
Labels: review.copy

#8934 Add link to build mode post
  src/testing/build-modes.md
Labels: review.copy

#8930 Add link to Flutter a11y article
  src/accessibility-and-localization/accessibility.md
Labels: review.copy

#8932 Swap out Animated Widget in Catalog
  src/_data/catalog/widgets.json
Labels: review.copy

#8918 Replace the Impeller video with a newer video
  src/perf/impeller.md
Labels: RFM

#8939 Remove design docs page
  firebase.json
  src/assets/js/go_link_index.js
  src/resources/design-docs.md
Labels: review.tech

#8957 Noted x86_64 Android support via ARM emulation
  src/deployment/android.md
Labels: review.copy

#8916 Add EditableText scroll into view breaking change note
  src/release/breaking-changes/editable-text-scroll-into-view.md
  src/release/breaking-changes/index.md
Labels: review.copy

#8951 Clarifying the update your path instructions
  src/add-to-app/android/add-flutter-fragment.md
  src/add-to-app/android/plugin-setup.md
  src/add-to-app/android/project-setup.md
  src/add-to-app/debugging.md
  src/add-to-app/ios/add-flutter-screen.md
  src/add-to-app/ios/project-setup.md
  src/add-to-app/multiple-flutters.md
  src/adoptawidget/index.md
  src/community/china.md
  src/cookbook/navigation/set-up-app-links.md
  src/cookbook/persistence/reading-writing-files.md
  src/deployment/cd.md
  src/deployment/ios.md
  src/deployment/linux.md
  src/deployment/macos.md
  src/get-started/flutter-for/swiftui-devs.md
  src/get-started/install/_analytics.md
  src/get-started/install/_android-setup-chromeos.md
  src/get-started/install/_get-sdk-linux.md
  src/get-started/install/_get-sdk-mac.md
  src/get-started/install/_ios-setup.md
  src/get-started/install/_path-linux-chromeos.md
  src/get-started/install/_path-mac.md
  src/get-started/install/help.md
  src/packages-and-plugins/favorites.md
  src/perf/app-size.md
  src/perf/best-practices.md
  src/platform-integration/desktop.md
  src/platform-integration/linux/building.md
  src/platform-integration/web/initialization.md
  src/platform-integration/web/wasm.md
  src/platform-integration/web/web-images.md
  src/reference/crash-reporting.md
  src/release/upgrade.md
  src/release/whats-new.md
  src/ui/advanced/shaders.md
  src/ui/layout/adaptive-responsive.md
Labels: RFM

#8945 Add migration guide for expired v3.10 deprecations
  src/release/breaking-changes/3-10-deprecations.md
  src/release/breaking-changes/index.md
Labels: review.await-update

#8960 Drawer cookbook recipe with navigation
  examples/cookbook/design/drawer/lib/drawer.dart
  examples/cookbook/design/drawer/lib/main.dart
  src/cookbook/design/drawer.md
Labels: st.RFM.%

#8961 Add release notes for Devtools 2.25.0
  src/tools/devtools/release-notes/images-2.25.0/memory.png
  src/tools/devtools/release-notes/index.md
  src/tools/devtools/release-notes/release-notes-2.25.0-src.md
  src/tools/devtools/release-notes/release-notes-2.25.0.md
Labels: review.tech
