Repository flutter/website, pull requests merged in 2023-09, with the labels that each got.

#9183 Updated Theming Cookbook for M3
  examples/cookbook/design/themes/README.md
  examples/cookbook/design/themes/lib/main.dart
  examples/cookbook/design/themes/lib/theme.dart
  examples/cookbook/design/themes/pubspec.yaml
  src/assets/images/docs/cookbook/themes.png
  src/cookbook/design/themes.md
Labels: st.RFM.%

#9325 Cleanup and standardize DevTools release notes
  src/tools/devtools/release-notes/index.md
  src/tools/devtools/release-notes/release-notes-2.10.0-src.md
  src/tools/devtools/release-notes/release-notes-2.10.0.md
  src/tools/devtools/release-notes/release-notes-2.11.2-src.md
  src/tools/devtools/release-notes/release-notes-2.11.2.md
  src/tools/devtools/release-notes/release-notes-2.12.1-src.md
  src/tools/devtools/release-notes/release-notes-2.12.1.md
  src/tools/devtools/release-notes/release-notes-2.12.2-src.md
  src/tools/devtools/release-notes/release-notes-2.12.2.md
  src/tools/devtools/release-notes/release-notes-2.13.1-src.md
  src/tools/devtools/release-notes/release-notes-2.13.1.md
  src/tools/devtools/release-notes/release-notes-2.14.0-src.md
  src/tools/devtools/release-notes/release-notes-2.14.0.md
  src/tools/devtools/release-notes/release-notes-2.15.0-src.md
  src/tools/devtools/release-notes/release-notes-2.15.0.md
  src/tools/devtools/release-notes/release-notes-2.16.0-src.md
  src/tools/devtools/release-notes/release-notes-2.16.0.md
  src/tools/devtools/release-notes/release-notes-2.17.0-src.md
  src/tools/devtools/release-notes/release-notes-2.17.0.md
  src/tools/devtools/release-notes/release-notes-2.18.0-src.md
  src/tools/devtools/release-notes/release-notes-2.18.0.md
  src/tools/devtools/release-notes/release-notes-2.19.0-src.md
  src/tools/devtools/release-notes/release-notes-2.19.0.md
  src/tools/devtools/release-notes/release-notes-2.20.0-src.md
  src/tools/devtools/release-notes/release-notes-2.20.0.md
  src/tools/devtools/release-notes/release-notes-2.21.1-src.md
  src/tools/devtools/release-notes/release-notes-2.21.1.md
  src/tools/devtools/release-notes/release-notes-2.22.2-src.md
  src/tools/devtools/release-notes/release-notes-2.22.2.md
  src/tools/devtools/release-notes/release-notes-2.23.1-src.md
  src/tools/devtools/release-notes/release-notes-2.23.1.md
  src/tools/devtools/release-notes/release-notes-2.24.0-src.md
  src/tools/devtools/release-notes/release-notes-2.24.0.md
  src/tools/devtools/release-notes/release-notes-2.25.0-src.md
  src/tools/devtools/release-notes/release-notes-2.25.0.md
  src/tools/devtools/release-notes/release-notes-2.26.1-src.md
  src/tools/devtools/release-notes/release-notes-2.26.1.md
  src/tools/devtools/release-notes/release-notes-2.27.0-src.md
  src/tools/devtools/release-notes/release-notes-2.27.0.md
  src/tools/devtools/release-notes/release-notes-2.7.0-src.md
  src/tools/devtools/release-notes/release-notes-2.7.0.md
  src/tools/devtools/release-notes/release-notes-2.8.0-src.md
  src/tools/devtools/release-notes/release-notes-2.8.0.md
  src/tools/devtools/release-notes/release-notes-2.9.1-src.md
  src/tools/devtools/release-notes/release-notes-2.9.1.md
  src/tools/devtools/release-notes/release-notes-2.9.2-src.md
  src/tools/devtools/release-notes/release-notes-2.9.2.md
Labels: st.RFM.%

#9373 Document android multithreaded platform view constraints
  src/platform-integration/android/platform-views.md
Labels: st.RFM

#9282 update linux snapcraft instructions to use core22
  src/deployment/linux.md
Labels: review.copy

#9323 Add documentation for performance profiling web apps
  src/_data/sidenav.yml
  src/assets/images/docs/tools/devtools/chrome-devtools-performance-panel.png
  src/perf/web-performance.md
  src/tools/devtools/performance.md
Labels: review.await-update

#9342 Prevent mysterious xcode cloud failures
  examples/deployment/xcode_cloud/ci_post_clone.sh
  src/deployment/cd.md
Labels: st.RFM.%

#9397 Announce a breaking change of added `dispose()`.
  src/release/breaking-changes/dispose.md
  src/release/breaking-changes/index.md
Labels: st.RFM.%

#9394 Migration guide for deprecations removed after v3.13
  src/release/breaking-changes/3-13-deprecations.md
  src/release/breaking-changes/index.md
Labels: st.RFM

#9426 Updated IntelliJ versions on editor page
  src/get-started/editor.md
Labels: fix.copy, st.RFM

#9340 Document Windows app lifecycle breaking change
  src/platform-integration/windows/extern_win.md
  src/release/breaking-changes/index.md
  src/release/breaking-changes/win_lifecycle_process_function.md
Labels: review.await-update, st.RFM.%

#9331 Added <kbd> tags where appropriate
  src/_includes/docs/debug/debug-flow-android.md
  src/_includes/docs/debug/debug-flow-ios.md
  src/_includes/docs/debug/debug-flow-macos.md
  src/_includes/docs/debug/debug-flow-vscode-as-start.md
  src/_includes/docs/debug/debug-flow-windows.md
  src/cookbook/testing/unit/introduction.md
  src/get-started/editor.md
  src/get-started/install/_ios-setup.md
  src/platform-integration/platform-adaptations.md
  src/platform-integration/windows/building.md
  src/testing/native-debugging.md
  src/tools/devtools/android-studio.md
  src/tools/devtools/debugger.md
  src/tools/devtools/release-notes/release-notes-2.8.0-src.md
  src/tools/formatting.md
  src/tools/vs-code.md
  src/ui/interactivity/focus.md
Labels: st.RFM.%

#9419 Add new Flutter book
  src/_data/books.yml
  src/assets/images/docs/cover/flutter-architectures-ebook.jpeg
Labels: st.RFM

#9297 Refactor Add to App Android
  src/add-to-app/android/project-setup.md
  src/assets/js/main.js
Labels: fix.copy, st.RFM.%, target.Android

#9392 Account for iOS 17 in developer certificate explanation
  src/get-started/install/_ios-setup.md
Labels: st.RFM

#9446 fix: small typo in `vs-code.md`
  src/tools/vs-code.md
Labels: cla: yes, st.RFM, fix.typo

#9454 Fixed typo in universal links page
  src/cookbook/navigation/set-up-universal-links.md
Labels: review.await-update

#9461 Delete src/f/contextual-survey-metadata.json
  src/f/contextual-survey-metadata.json
Labels: st.RFM

#9462 Update dart-devtools-survey-metadata.json
  src/f/dart-devtools-survey-metadata.json
Labels: st.RFM

#9460 Delete src/f/flutter-survey-metadata.json
  src/f/flutter-survey-metadata.json
Labels: st.RFM

#9458 Fix: #9456 changes Firebase AdMob to Google Mobile Ads
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
Labels: st.RFM

#9463 DevTools Release Notes 2.28.1
  src/tools/devtools/release-notes/images-2.28.1/example_devtools_extension.png
  src/tools/devtools/release-notes/images-2.28.1/logger_copy.png
  src/tools/devtools/release-notes/index.md
  src/tools/devtools/release-notes/release-notes-2.28.1-src.md
  src/tools/devtools/release-notes/release-notes-2.28.1.md
Labels: st.RFM

#9452 Fixes routing example
  src/release/breaking-changes/route-navigator-refactoring.md
Labels: st.RFM

#9425 Add Android 14 nonlinear font scaling migration guide
  src/release/breaking-changes/android-14-nonlinear-text-scaling-migration.md
  src/release/breaking-changes/index.md
Labels: st.RFM.%
