Repository flutter/website, pull requests merged in 2023-05, with the labels that each got.

#8641 add go link for asset transformation design doc
  firebase.json
Labels: RFM

#8682 Update macos deployment instructions to bump minimum supported version to 10.14
  src/deployment/macos.md
Labels: RFM

#7692 Insert content text input client breaking change
  src/release/breaking-changes/index.md
  src/release/breaking-changes/insert-content-text-input-client.md
Labels: RFM%

#8703 Update CODEOWNERS to limit auto review requests
  CODEOWNERS
Labels: RFM

#8695 Update gems including rouge for Dart 3 syntax highlighting
  Gemfile.lock
Labels: RFM

#8637 Universal link `apple-app-site-association` misses `apps` property
  src/cookbook/navigation/set-up-universal-links.md
Labels: cla: yes, RFM

#8702 Remove links to 'Java to Dart' codelab
  src/get-started/learn-more.md
  src/resources/bootstrap-into-dart.md
Labels: RFM

#8711 Updates to Android Studio and IntelliJ opening and new Flutter project instructions
  src/tools/android-studio.md
Labels: RFM

#8692 More detailed descriptions of the channels
  src/release/upgrade.md
Labels: RFM

#8706 Update Material Design links and assets to Material 3
  _config.yml
  src/deployment/android.md
  src/get-started/codelab-web.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/react-native-devs.md
  src/get-started/flutter-for/uikit-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/get-started/test-drive/_vscode.md
  src/get-started/test-drive/index.md
  src/release/breaking-changes/fab-theme-data-accent-properties.md
  src/release/breaking-changes/material-chip-button-semantics.md
  src/release/breaking-changes/theme-data-accent-properties.md
  src/resources/architectural-overview.md
  src/testing/code-debugging.md
  src/ui/animations/hero-animations.md
  src/ui/animations/staggered-animations.md
  src/ui/interactive.md
  src/ui/layout/building-adaptive-apps.md
  src/ui/layout/index.md
Labels: review:tech

#8730 Update Wasm page with firefox update
  src/platform-integration/web/wasm.md
Labels: RFM%, tarp:web

#8734 Update google-apis.md
  src/data-and-backend/google-apis.md
Labels: cla: yes, review:copy

#8732 Update fade-in-starter-code.md
  src/_includes/docs/implicit-animations/fade-in-starter-code.md
Labels: cla: yes, review:tech

#8733 Update fade-in-complete.md
  src/_includes/docs/implicit-animations/fade-in-complete.md
Labels: cla: yes, review:tech

#8729 Use `flutter pub add` for dependencies in networking cookbooks
  src/cookbook/networking/background-parsing.md
  src/cookbook/networking/delete-data.md
  src/cookbook/networking/fetch-data.md
  src/cookbook/networking/send-data.md
  src/cookbook/networking/update-data.md
Labels: cookbook, review:copy, packages

#8700 Add `TabBar.tabAlignment` migration guide
  src/release/breaking-changes/tab-alignment.md
Labels: review:await-update

#8770 Fix wrong file name in developing-packages.md
  src/packages-and-plugins/developing-packages.md
Labels: RFM, a:native-code

#8666 Allow users recover which class it is given obfuscated class name
  src/deployment/obfuscate.md
Labels: review:await-update

#8795 Adjust 'Widget catalog' card name on homepage
  src/_data/docs_cards.yml
Labels: RFM
