Repository flutter/website, pull requests merged in 2023-11, with the labels that each got.

#9742 Replace primarySwatch with ColorScheme.fromSeed in the examples.
  examples/cookbook/gestures/dismissible/lib/main.dart
  examples/cookbook/gestures/dismissible/lib/step1.dart
  examples/cookbook/gestures/dismissible/lib/step2.dart
  examples/cookbook/networking/delete_data/lib/main.dart
  examples/cookbook/networking/fetch_data/lib/main.dart
  examples/cookbook/networking/send_data/lib/main.dart
  examples/cookbook/networking/update_data/lib/main.dart
  examples/cookbook/networking/update_data/lib/main_step5.dart
  examples/cookbook/testing/unit/mocking/lib/main.dart
  examples/get-started/flutter-for/android_devs/lib/animation.dart
  examples/get-started/flutter-for/android_devs/lib/async.dart
  examples/get-started/flutter-for/android_devs/lib/isolates.dart
  examples/get-started/flutter-for/android_devs/lib/layout.dart
  examples/get-started/flutter-for/android_devs/lib/list_item_tapped.dart
  examples/get-started/flutter-for/android_devs/lib/listview.dart
  examples/get-started/flutter-for/android_devs/lib/listview_builder.dart
  examples/get-started/flutter-for/android_devs/lib/listview_dynamic.dart
  examples/get-started/flutter-for/android_devs/lib/progress.dart
  examples/get-started/flutter-for/android_devs/lib/request_data.dart
  examples/get-started/flutter-for/android_devs/lib/text_widget.dart
  examples/get-started/flutter-for/android_devs/lib/theme.dart
  examples/get-started/flutter-for/android_devs/lib/validation_errors.dart
  examples/get-started/flutter-for/declarative/lib/main.dart
  examples/get-started/flutter-for/ios_devs/lib/request_data.dart
  examples/get-started/flutter-for/ios_devs/lib/theme.dart
  examples/get-started/flutter-for/react_native_devs/lib/examples.dart
  examples/get-started/flutter-for/xamarin_devs/lib/theme.dart
  examples/integration_test/lib/main.dart
  examples/integration_test_migration/lib/main.dart
  examples/testing/code_debugging/lib/performance_overlay.dart
  examples/ui/advanced/actions_and_shortcuts/lib/copyable_text.dart
  src/cookbook/gestures/dismissible.md
  src/cookbook/networking/delete-data.md
  src/cookbook/networking/fetch-data.md
  src/cookbook/networking/send-data.md
  src/cookbook/networking/update-data.md
  src/cookbook/testing/unit/mocking.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/react-native-devs.md
  src/get-started/flutter-for/uikit-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/release/breaking-changes/layout-builder-optimization.md
  src/release/breaking-changes/page-transition-replaced-by-ZoomPageTransitionBuilder.md
  src/testing/code-debugging.md
  src/ui/interactivity/actions-and-shortcuts.md
Labels: review.await-update

#9754 Add link to ffigen package installation docs
  src/packages-and-plugins/developing-packages.md
Labels: st.RFM

#9678 Add achievements and leaderboard cookbook
  firebase.json
  src/assets/images/docs/cookbook/app-store-add-app-button.png
  src/assets/images/docs/cookbook/google-play-create-app.png
  src/assets/images/docs/cookbook/play-console-play-games-services.png
  src/assets/images/docs/cookbook/types-of-gamer-motivations.png
  src/cookbook/games/achievements-leaderboard.md
  src/cookbook/games/index.md
  src/cookbook/index.md
Labels: a.cookbook, st.RFM, t.games

#9762 Remove unused 'toc' ID from table of contents
  src/_includes/inline-toc.html
  src/_includes/side-toc.html
Labels: review.tech

#9723 Update and cleanup shared_preferences cookbook recipe
  examples/cookbook/persistence/key_value/lib/main.dart
  examples/cookbook/persistence/key_value/lib/partial_excerpts.dart
  examples/cookbook/persistence/key_value/pubspec.yaml
  examples/cookbook/persistence/key_value/test/prefs_test.dart
  src/cookbook/persistence/key-value.md
Labels: review.copy

#9764 Increase contrast of secondary aside
  src/_sass/base/_variables.scss
  src/_sass/vendor/_bootstrap.scss
Labels: review.tech

#9763 Improve contrast of text and highlighting in code snippets
  src/_sass/base/_variables.scss
  src/_sass/components/_code.scss
Labels: review.tech

#9737 Add info on group test function
  examples/cookbook/testing/unit/counter_app/test/group.dart
  src/cookbook/testing/unit/introduction.md
Labels: review.copy

#9752 Refactor the cloudbuild template
  cloud_build/scripts/stage_site_and_comment_on_github.sh
  cloud_build/stage.yaml
  cloud_build/staging_container/Dockerfile
  cloud_build/staging_container/README.md
  cloud_build/staging_container/cloudbuild.yaml
  cloudbuild.yaml
  tool/check-links.sh
Labels: st.RFM.%

#9744 Introduce a new top-level sidenav category for toolkit content
  src/_data/sidenav.yml
Labels: infra.ia

#9730 Add mobile ads cookbook
  firebase.json
  src/_sass/base/_base.scss
  src/assets/images/docs/cookbook/ads-ad-unit-id.png
  src/assets/images/docs/cookbook/ads-ad-unit.png
  src/assets/images/docs/cookbook/ads-app-id.png
  src/assets/images/docs/cookbook/ads-device.jpg
  src/assets/images/docs/cookbook/ads-multidex.png
  src/cookbook/index.md
  src/cookbook/plugins/google-mobile-ads.md
Labels: a.cookbook, review.copy, t.games

#9794 Call out Dart 3 patterns codelab on JSON serialization page
  src/data-and-backend/serialization/json.md
Labels: review.copy

#9753 Update google-apis page
  src/data-and-backend/google-apis.md
Labels: st.RFM.%

#9338 Update using Flutter from China
  src/_data/mirrors.yml
  src/_includes/docs/china-notice-cn.md
  src/_includes/docs/china-notice.md
  src/assets/js/main.js
  src/community/china.md
  src/community/china/_download-urls.md
  src/community/china/_os-settings.md
  src/community/china/_pub-settings.md
  src/community/china/index.md
Labels: st.RFM

#9793 Add Cupertino example to layout
  examples/layout/base/lib/cupertino.dart
  src/ui/layout/index.md
Labels: review.await-update

#9698 Update iOS app extension document
  src/assets/images/docs/development/platform-integration/app-extensions/embed-framework.png
  src/assets/images/docs/development/platform-integration/app-extensions/extension-info.png
  src/assets/images/docs/development/platform-integration/app-extensions/imessage-extension.png
  src/assets/images/docs/development/platform-integration/app-extensions/share-extension-info.png
  src/assets/images/docs/development/platform-integration/app-extensions/share-extension.png
  src/platform-integration/ios/app-extensions.md
Labels: review.tech

#9810 What's new updates
  src/_includes/banner.html
  src/perf/impeller.md
  src/release/release-notes/index.md
  src/release/whats-new.md
  src/ui/design/material/index.md
Labels: st.RFM.%

#9795 Add shortcut key event migration guide
  src/release/breaking-changes/index.md
  src/release/breaking-changes/shortcut-key-event-migration.md
Labels: st.RFM

#9820 Update android-predictive-back.md
  src/release/breaking-changes/android-predictive-back.md
Labels: cla: yes

#9829 Update `fetch_data`
  examples/cookbook/networking/authenticated_requests/lib/main.dart
  examples/cookbook/networking/delete_data/lib/main.dart
  examples/cookbook/networking/fetch_data/lib/main.dart
  examples/cookbook/networking/send_data/lib/main.dart
  examples/cookbook/networking/update_data/lib/main.dart
  examples/cookbook/networking/update_data/lib/main_step5.dart
  examples/example_utils/lib/analysis.yaml
  examples/testing/errors/lib/excerpts.dart
  examples/testing/errors/lib/main.dart
  examples/testing/integration_tests/how_to/android/local.properties
  examples/testing/integration_tests/how_to/ios/Podfile
  examples/testing/integration_tests/how_to/ios/Runner/GeneratedPluginRegistrant.h
  examples/testing/integration_tests/how_to/ios/Runner/GeneratedPluginRegistrant.m
  examples/testing/integration_tests/how_to/macos/Podfile
  src/cookbook/networking/authenticated-requests.md
  src/cookbook/networking/delete-data.md
  src/cookbook/networking/fetch-data.md
  src/cookbook/networking/send-data.md
  src/cookbook/networking/update-data.md
  src/testing/errors.md
Labels: st.RFM

#9771 Adding `/go/games-revenue` link for games revenue
  firebase.json
Labels: st.blocked

#9703 Adding info about drag and drop
  src/_data/sidenav.yml
  src/ui/interactivity/gestures/drag-outside.md
Labels: review.await-update

#9860 Fixes typo and link on MaxLengthEnforcement BC page
  src/release/breaking-changes/use-maxLengthEnforcement-instead-of-maxLengthEnforced.md
Labels: st.RFM

#9861 Fix link to FontStyle enum
  src/ui/design/text/typography.md
Labels: review.copy

#9853 Inspector settings docs
  src/assets/images/docs/tools/devtools/flutter_inspector_settings.png
  src/tools/devtools/inspector.md
Labels: review.await-update, st.RFM.%
