Repository flutter/website, pull requests merged in 2023-04, with the labels that each got.

#8566 [Docs] [Dart Doc Tool] rename `dartdoc` executable to `dart doc`
  src/development/packages-and-plugins/developing-packages.md
Labels: review:copy

#8475 Document the new `canvasKitVariant` runtime configuration
  src/development/platform-integration/web/initialization.md
Labels: land on stable release, RFM%

#8509 Adaptation information for inputs and app bars
  src/assets/images/docs/platform-adaptations/hig-appbar.png
  src/assets/images/docs/platform-adaptations/hig-checkbox.png
  src/assets/images/docs/platform-adaptations/hig-progress.png
  src/assets/images/docs/platform-adaptations/hig-radio.png
  src/assets/images/docs/platform-adaptations/hig-slider.png
  src/assets/images/docs/platform-adaptations/hig-switch.png
  src/assets/images/docs/platform-adaptations/m3-checkbox.png
  src/assets/images/docs/platform-adaptations/m3-progress.png
  src/assets/images/docs/platform-adaptations/m3-radio.png
  src/assets/images/docs/platform-adaptations/m3-slider.png
  src/assets/images/docs/platform-adaptations/m3-switch.png
  src/assets/images/docs/platform-adaptations/mat-appbar.png
  src/resources/platform-adaptations.md
Labels: land on stable release, RFM%

#8567 Minor cleanup to `tabs.js`
  src/assets/js/tabs.js
Labels: review:tech

#8577 fix provenance link on linux
  src/assets/js/archive.js
Labels: RFM

#8543 Adds migration guide for material localized Strings
  src/release/breaking-changes/index.md
  src/release/breaking-changes/material-localized-strings.md
Labels: review:copy

#8607 Updated Impeller details
  src/perf/impeller.md
Labels: review:tech, RFM

#8424 Adding state restoration pages
  src/_data/sidenav.yml
  src/development/platform-integration/android/restore-state-android.md
  src/development/platform-integration/ios/restore-state-ios.md
Labels: review:tech

#8573 Fix typo "priori" -> "prior"
  src/resources/inside-flutter.md
Labels: cla: yes
