Repository flutter/website, pull requests merged in 2023-07, with the labels that each got.

#8970 Fix multiple minor typos
  src/_sass/pages/_clock.scss
  src/cookbook/maintenance/error-reporting.md
  src/data-and-backend/google-apis.md
  src/get-started/install/_get-sdk-linux.md
  src/get-started/install/_get-sdk-mac.md
  src/ui/advanced/typography.md
  src/ui/animations/hero-animations.md
Labels: st.RFM

#8972 Add some security headers
  firebase.json
Labels: st.RFM

#8977 Fix missing DevTools release notes
  src/tools/devtools/release-notes/release-notes-2.12.2-src.md
  src/tools/devtools/release-notes/release-notes-2.12.2.md
Labels: bot.autosubmit

#8973 Extend local caching to more file types
  firebase.json
Labels: st.RFM

#8969 Remove `flutter format` mention now that it is no longer functional
  src/reference/flutter-cli.md
Labels: st.RFM

#8992 Remove unused mini-toc layout
  src/_layouts/mini-toc.md
Labels: st.RFM

#8816 Add categorical headers to Resources in sidenav
  src/_data/sidenav.yml
  src/_includes/mini-toc.md
  src/_includes/sidenav-level-2.html
  src/_sass/components/_sidebar.scss
Labels: infra.design, st.RFM.%

#9004 Fix footer being above opened sidenav menu
  src/_sass/base/_variables.scss
  src/_sass/components/_banner.scss
  src/_sass/components/_header.scss
  src/_sass/components/_snackbar.scss
Labels: st.RFM

#8995 Remove most uses of font awesome
  _config.yml
  src/_data/sidenav.yml
  src/_includes/header.html
  src/_includes/mini-toc.md
  src/_sass/base/_bootstrap_adjust.scss
  src/_sass/components/_header.scss
  src/_sass/pages/_clock.scss
  src/assets/images/social/github.svg
  src/assets/images/social/medium.svg
  src/assets/images/social/twitter.svg
  src/assets/images/social/youtube.svg
  src/clock/index.html
  src/create/index.html
Labels: st.RFM

#9019 Removes phrase that says Impeller is Android native
  src/resources/architectural-overview.md
Labels: review.copy

#9035 Bump supported Android version to 33
  src/reference/supported-platforms.md
Labels: review.await-update

#9021 Added China notice to all download related pages
  src/_includes/docs/china-notice.md
  src/get-started/install/_get-sdk-chromeos.md
  src/get-started/install/_get-sdk-linux.md
  src/get-started/install/_get-sdk-mac.md
  src/get-started/install/_get-sdk-win.md
  src/get-started/install/index.md
  src/release/archive.md
Labels: review.copy

#9022 Begin migrating `archive.js` to vanilla JavaScript
  src/assets/js/archive.js
Labels: st.RFM

#9056 Fix import in android platform views
  src/platform-integration/android/platform-views.md
Labels: st.RFM

#9058 Migrate styles to SASS modules
  src/_sass/base/_base.scss
  src/_sass/base/_bootstrap_adjust.scss
  src/_sass/base/_bootstrap_config.scss
  src/_sass/base/_material-colors.scss
  src/_sass/base/_print-overrides.scss
  src/_sass/base/_site_overrides.scss
  src/_sass/base/_variables.scss
  src/_sass/components/_banner.scss
  src/_sass/components/_books.scss
  src/_sass/components/_code.scss
  src/_sass/components/_content.scss
  src/_sass/components/_cookie-notice.scss
  src/_sass/components/_d2h.scss
  src/_sass/components/_footer.scss
  src/_sass/components/_header.scss
  src/_sass/components/_juicy-button.scss
  src/_sass/components/_next-prev-nav.scss
  src/_sass/components/_sidebar.scss
  src/_sass/components/_snackbar.scss
  src/_sass/components/_toc.scss
  src/_sass/pages/_clock.scss
  src/_sass/pages/_create.scss
  src/_sass/pages/_landing-page.scss
  src/_sass/pages/_not-found.scss
  src/_sass/pages/_subscribe.scss
  src/_sass/site.scss
  src/_sass/vendor/_bootstrap.scss
  src/assets/css/main.scss
Labels: st.RFM

#9071 Insert missed word
  src/ui/layout/constraints.md
Labels: st.RFM, d.typo

#9069 Fixed the tab name Signing & Capabilities
  src/cookbook/navigation/set-up-universal-links.md
Labels: review.await-update

#9102 Remove 'Tutorials' page and links
  firebase.json
  src/_data/sidenav.yml
  src/_includes/header.html
Labels: review.copy

#9104 Reorganize 'Packages & plugins' section
  firebase.json
  src/_data/sidenav.yml
  src/packages-and-plugins/developing-packages.md
  src/packages-and-plugins/happy-paths/index.md
  src/packages-and-plugins/happy-paths/recommended.md
  src/testing/index.md
  src/testing/plugins-in-tests.md
  src/testing/testing-plugins.md
Labels: review.copy

#9111 "dismissForMinutes" instead of Days
  src/f/contextual-survey-metadata.json
Labels: st.RFM

#9112 Adding a preliminary index for /ui
  firebase.json
  src/_data/sidenav.yml
  src/get-started/learn-more.md
  src/index.md
  src/resources/architectural-overview.md
  src/tools/devtools/inspector.md
  src/ui/index.md
  src/ui/interactive.md
  src/ui/widgets-intro.md
Labels: review.copy, st.RFM.%

#9088 Change the example code to match the code description
  examples/layout/lakes/step4/lib/main.dart
  examples/layout/lakes/step5/lib/main.dart
  examples/layout/lakes/step6/lib/main.dart
  src/ui/layout/tutorial.md
Labels: review.await-update

#9061 Incorporate networking cookbooks in sidenav with new tooling
  src/_data/sidenav.yml
  src/_includes/sidenav-level-1.html
  src/_plugins/active_nav_for_page.rb
  src/_plugins/active_nav_generator.rb
  src/_plugins/sidenav-active-entry-filter.rb
  src/cookbook/index.md
  src/cookbook/networking/web-sockets.md
Labels: review.copy, review.tech

#9135 Remove space in gen_l10n_inputs_ and_outputs.json
  src/accessibility-and-localization/internationalization.md
Labels: st.RFM

#9121 Enable new text wrap balance for page headers
  src/_sass/components/_content.scss
Labels: infra.design, st.RFM

#9125 Reorganize testing and debugging sidenav category
  src/_data/sidenav.yml
  src/data-and-backend/state-mgmt/simple.md
  src/packages-and-plugins/developing-packages.md
  src/perf/ui-performance.md
  src/platform-integration/web/faq.md
  src/release/breaking-changes/flutter-driver-migration.md
  src/resources/faq.md
  src/testing/index.md
  src/testing/integration-tests/index.md
  src/testing/overview.md
  src/testing/testing-plugins.md
Labels: infra.ia

#9122 Remove broken and unused subscription preferences page
  firebase.json
  src/_sass/pages/_subscribe.scss
  src/_sass/site.scss
  src/assets/js/subscribe_prefs.js
  src/subscribe/preferences.html
Labels: review.tech

#9154 Propose another default install path for Windows
  src/get-started/install/_get-sdk-win.md
Labels: st.RFM

#9054 Update macOS install for security settings change
  src/assets/js/main.js
  src/get-started/install/_ios-setup.md
Labels: review.tech

#9153 Introduce a new 'Design & theming' category in the sidenav
  firebase.json
  src/_data/sidenav.yml
  src/release/whats-new.md
  src/ui/advanced/index.md
  src/ui/design/graphics/fragment-shaders.md
  src/ui/design/graphics/index.md
  src/ui/design/index.md
  src/ui/design/material/index.md
  src/ui/design/text/index.md
  src/ui/design/text/typography.md
Labels: st.RFM

#9161 Add top-level headers to sidenav
  src/_data/sidenav.yml
  src/_includes/sidenav-level-1.html
  src/_sass/components/_sidebar.scss
Labels: st.RFM

#9114 Adding macOS impeller info
  src/perf/impeller.md
Labels: act.merge-to-next
