Repository flutter/website, pull requests merged in 2024-06, with the labels that each got.

#10692 Fixes. slash issue in uninstall page
  src/content/get-started/uninstall/index.md
Labels: a.get-started, st.RFM

#10706 Fixes PATH variance, filename replacement script
  src/_data/shells.yml
  src/_includes/docs/install/flutter/download.md
  src/content/assets/js/archive.js
Labels: review.tech

#10701 Update video_player compatibility
  src/content/cookbook/plugins/play-video.md
Labels: review.copy

#10735 Fix link to GitLab CI
  AUTHORS
  src/content/deployment/cd.md
Labels: st.RFM

#10756 Remove Q2 survey from the banner
  src/_includes/banner.html
Labels: st.RFM

#10758 Add pub.dev filter to Wasm page
  src/content/platform-integration/web/wasm.md
Labels: st.RFM.%

#10757 Update cookie banner text
  src/_includes/cookie-notice.html
Labels: st.RFM

#10764 Add scroll-margin-top to headers
  src/_sass/components/_content.scss
Labels: review.tech

#10779 Fixed Swift nil ref
  src/content/platform-integration/platform-channels.md
Labels: review.copy

#10770 Add explanation for what deep links are
  src/content/ui/navigation/deep-linking.md
Labels: st.RFM.%

#10788 Fix typo on "Integration testing concepts" page
  src/content/cookbook/testing/integration/introduction.md
Labels: st.RFM

#10784 Tiny update architectural-overview.md
  src/content/resources/architectural-overview.md
Labels: st.RFM

#10797 Fix incorrect keytool command for PowerShell in Android deployment documentation
  src/content/deployment/android.md
Labels: st.RFM

#10799 Add titles to all DartPads
  src/_includes/docs/implicit-animations/fade-in-complete.md
  src/_includes/docs/implicit-animations/fade-in-starter-code.md
  src/_includes/docs/implicit-animations/shape-shifting-complete.md
  src/_includes/docs/implicit-animations/shape-shifting-starter-code.md
  src/content/cookbook/animation/animated-container.md
  src/content/cookbook/animation/opacity-animation.md
  src/content/cookbook/animation/page-route-animation.md
  src/content/cookbook/animation/physics-simulation.md
  src/content/cookbook/design/drawer.md
  src/content/cookbook/design/orientation.md
  src/content/cookbook/design/snackbars.md
  src/content/cookbook/design/tabs.md
  src/content/cookbook/design/themes.md
  src/content/cookbook/effects/download-button.md
  src/content/cookbook/effects/drag-a-widget.md
  src/content/cookbook/effects/expandable-fab.md
  src/content/cookbook/effects/gradient-bubbles.md
  src/content/cookbook/effects/nested-nav.md
  src/content/cookbook/effects/parallax-scrolling.md
  src/content/cookbook/effects/photo-filter-carousel.md
  src/content/cookbook/effects/shimmer-loading.md
  src/content/cookbook/effects/staggered-menu-animation.md
  src/content/cookbook/effects/typing-indicator.md
  src/content/cookbook/forms/focus.md
  src/content/cookbook/forms/retrieve-input.md
  src/content/cookbook/forms/text-field-changes.md
  src/content/cookbook/forms/text-input.md
  src/content/cookbook/forms/validation.md
  src/content/cookbook/gestures/dismissible.md
  src/content/cookbook/gestures/handling-taps.md
  src/content/cookbook/gestures/ripples.md
  src/content/cookbook/images/network-image.md
  src/content/cookbook/lists/basic-list.md
  src/content/cookbook/lists/floating-app-bar.md
  src/content/cookbook/lists/grid-lists.md
  src/content/cookbook/lists/horizontal-list.md
  src/content/cookbook/lists/long-lists.md
  src/content/cookbook/lists/mixed-list.md
  src/content/cookbook/lists/spaced-items.md
  src/content/cookbook/navigation/hero-animations.md
  src/content/cookbook/navigation/named-routes.md
  src/content/cookbook/navigation/navigate-with-arguments.md
  src/content/cookbook/navigation/navigation-basics.md
  src/content/cookbook/navigation/passing-data.md
  src/content/cookbook/navigation/returning-data.md
  src/content/cookbook/navigation/set-up-app-links.md
  src/content/cookbook/navigation/set-up-universal-links.md
  src/content/cookbook/plugins/play-video.md
  src/content/get-started/codelab-web.md
  src/content/ui/index.md
  src/content/ui/interactivity/actions-and-shortcuts.md
  src/content/ui/layout/constraints.md
Labels: t.a11y, review.copy

#10793 Implement and migrate to a shortcode-controlled, tabbed interface
  eleventy.config.js
  src/_11ty/shortcodes.js
  src/_includes/docs/add-to-app/android-initial-route-cached-engine.md
  src/_includes/docs/community/china/download-urls.md
  src/_includes/docs/community/china/os-settings.md
  src/_includes/docs/community/china/pub-settings.md
  src/_includes/docs/debug/debug-flow-android.md
  src/_includes/docs/debug/debug-flow-ios.md
  src/_includes/docs/debug/debug-flow-macos.md
  src/_includes/docs/debug/debug-flow-windows.md
  src/_includes/docs/install/compiler/android.md
  src/_includes/docs/install/compiler/xcode.md
  src/_includes/docs/install/deprecated/ios-setup.md
  src/_includes/docs/install/devices/ios-physical.md
  src/_includes/docs/install/flutter-sdk.md
  src/_includes/docs/release/archive-release_os.md
  src/content/add-to-app/android/_initial-route-cached-engine.md
  src/content/add-to-app/android/add-flutter-fragment.md
  src/content/add-to-app/android/add-flutter-screen.md
  src/content/add-to-app/android/project-setup.md
  src/content/add-to-app/ios/add-flutter-screen.md
  src/content/add-to-app/ios/project-setup.md
  src/content/assets/js/archive.js
  src/content/assets/js/main.js
  src/content/assets/js/tabs.js
  src/content/community/china/index.md
  src/content/cookbook/navigation/set-up-universal-links.md
  src/content/get-started/editor.md
  src/content/get-started/test-drive/index.md
  src/content/get-started/uninstall/index.md
  src/content/platform-integration/android/platform-views.md
  src/content/platform-integration/android/splash-screen.md
  src/content/platform-integration/ios/platform-views.md
  src/content/platform-integration/platform-channels.md
  src/content/release/archive.md
  src/content/testing/integration-tests/index.md
  src/content/tools/vs-code.md
  src/content/ui/accessibility-and-internationalization/accessibility.md
Labels: review.copy

#10800 Add skip to main content link
  src/_layouts/base.html
  src/_layouts/default.html
  src/_sass/base/_base.scss
Labels: review.tech

#10819 Update other references to web initialization customization
  src/content/deployment/web.md
  src/content/platform-integration/web/initialization.md
  src/content/platform-integration/web/renderers.md
Labels: review.copy

#10818 Corrected 2nd example in Step 3
  src/content/ui/interactivity/index.md
Labels: review.copy
