Repository flutter/website, pull requests merged in 2024-12, with the labels that each got.

#11467 fix typo to dart-swift-concurrency.md
  src/content/get-started/flutter-for/dart-swift-concurrency.md
Labels: cla: yes

#11480 Migration guide for M3 token update
  src/content/release/breaking-changes/index.md
  src/content/release/breaking-changes/material-design-3-token-update.md
Labels: review.await-update

#10891 docs: Support for overriding endorsed plugin implementations
  src/content/packages-and-plugins/developing-packages.md
Labels: st.RFM, act.merge-to-next

#11182 [Next stable] Update documentation for new location of linux source
  src/content/platform-integration/platform-channels.md
Labels: st.RFM, act.merge-to-next

#11481 Migration guide for `ThemeData.indicatorColor` deprecation
  src/content/release/breaking-changes/deprecate-themedata-indicatorcolor.md
  src/content/release/breaking-changes/index.md
Labels: st.RFM

#11478 Update Navigation concepts code snippets so that they can be tested.
  examples/ui/navigation/README
  examples/ui/navigation/analysis_options.yaml
  examples/ui/navigation/lib/navigator_basic.dart
  examples/ui/navigation/lib/navigator_named_routes.dart
  examples/ui/navigation/lib/navigator_router.dart
  examples/ui/navigation/pubspec.yaml
  src/content/ui/navigation/index.md
Labels: review.await-update

#11493 Add a breaking change doc about deep links flag change to the flutter website
  src/content/release/breaking-changes/deep-links-flag-change.md
  src/content/release/breaking-changes/index.md
Labels: review.await-update

#11520 Update shader compilation jank guide
  firebase.json
  src/_data/sidenav.yml
  src/content/perf/rendering-performance.md
  src/content/perf/shader.md
  src/content/release/archive-whats-new.md
  src/content/tools/devtools/performance.md
  src/content/ui/design/graphics/fragment-shaders.md
Labels: review.await-update
