Repository flutter/website, pull requests merged in 2024-07, with the labels that each got.

#10831 Fix typo
  src/content/ui/adaptive-responsive/large-screens.md
Labels: st.RFM

#10833 Fix iOS platform views AppDelegate code excerpt
  src/content/platform-integration/ios/platform-views.md
Labels: review.await-update

#10871 Fix incorrect usage of 'Setup'
  src/_data/sidenav.yml
Labels: review.copy

#10908 Update platforms.yml to reflect 3.22 android api support updates
  src/_data/platforms.yml
Labels: st.RFM

#10914 Introducing a red or grey screen of death
  src/content/testing/common-errors.md
Labels: st.blocked

#10917 Draft: Adding info for customizing control center in iOS 18
  src/content/platform-integration/ios/app-extensions.md
Labels: review.tech
