Repository flutter/website, pull requests merged in 2024-05, with the labels that each got.

#10433 Clarified integration test intro
  examples/cookbook/testing/integration/introduction/integration_test/app_test.dart
  examples/cookbook/testing/integration/introduction/lib/main.dart
  src/content/cookbook/testing/integration/introduction.md
  src/content/testing/testing-plugins.md
Labels: review.tech

#10502 Update banner for I/O 2024
  src/_includes/banner.html
Labels: review.copy

#10516 Adding links to the new wasm article on Medium
  src/content/perf/web-performance.md
  src/content/platform-integration/web/wasm.md
  src/content/platform-integration/web/web-images.md
Labels: review.await-update

#10517 Update firebase.json
  firebase.json
Labels: review.copy

#10509 Devtools deep linking support
  src/_data/sidenav.yml
  src/content/assets/images/docs/tools/devtools/deep-link-validator.png
  src/content/tools/devtools/deep-links.md
  src/content/tools/devtools/overview.md
Labels: review.await-update

#10524 Prevent a few icons from being mistakenly read by screen readers
  src/_includes/inline-toc.html
  src/_sass/components/_header.scss
  src/_sass/components/_sidebar.scss
Labels: review.tech

#10560 Fix drag a widget image link
  eleventy.config.js
  examples/cookbook/effects/drag_a_widget/lib/main.dart
  src/content/cookbook/effects/drag-a-widget.md
Labels: review.tech

#10500 Update supported platforms for 3.22
  src/_data/platforms.yml
  src/_data/site.yml
  src/_includes/docs/install/deprecated/android-setup.md
  src/content/add-to-app/android/project-setup.md
  src/content/deployment/android.md
  src/content/deployment/macos.md
  src/content/platform-integration/macos/building.md
  src/content/reference/supported-platforms.md
  src/content/resources/faq.md
Labels: st.RFM

#10610 fix: adding proper command for extracting archives
  src/_includes/docs/install/flutter/download.md
Labels: cla: yes, review.tech

#10563 Refactor integration test pages
  examples/testing/integration_tests/how_to/integration_test/counter_test.dart
  src/_includes/docs/test/integration/linux-example.md
  src/_includes/docs/test/integration/macos-example.md
  src/_includes/docs/test/integration/windows-example.md
  src/content/cookbook/testing/integration/introduction.md
  src/content/cookbook/testing/integration/profiling.md
  src/content/platform-integration/web/faq.md
  src/content/testing/integration-tests/index.md
  src/content/testing/testing-plugins.md
Labels: review.tech

#10625 Update launch-screen.md
  src/content/platform-integration/ios/launch-screen.md
Labels: cla: yes

#10639 Switch platform adaptation image from object to img
  src/content/platform-integration/platform-adaptations.md
Labels: review.tech

#10644 Update npm deps and resolve security alert
  package.json
  pnpm-lock.yaml
Labels: review.tech

#10645 Fix some typos and formatting issues in fwe docs
  src/content/get-started/fwe/layout.md
  src/content/get-started/fwe/local-caching.md
  src/content/get-started/fwe/networking.md
  src/content/get-started/fwe/state-management.md
  src/content/get-started/fwe/user-input.md
Labels: review.copy

#10637 Replace terminal marker with CSS-based marker
  src/_11ty/plugins/highlight.js
  src/_sass/components/_code.scss
Labels: review.tech

#10649 Fix Xcode install
  src/_includes/docs/install/compiler/xcode.md
  src/_includes/docs/install/flutter-doctor-success.md
  src/_includes/docs/install/flutter-doctor.md
  src/_includes/docs/install/next-steps.md
  src/content/add-to-app/ios/project-setup.md
  src/content/release/archive-whats-new.md
Labels: review.copy

#10652 Add /predicitive-back short link
  firebase.json
Labels: st.RFM

#10653 Add design doc for Cupertino modal bottom sheet routes
  firebase.json
Labels: st.RFM

#10660 Remove no longer used JS code
  src/_includes/snackbar.html
  src/content/assets/js/main.js
Labels: review.tech

#10659 Include more accessible labels for widget catalog cards
  src/content/ui/widgets/index.md
Labels: review.copy

#10663 Flutter Gradle Plugin Apply Doc - Enhance copy code
  src/content/release/breaking-changes/flutter-gradle-plugin-apply.md
Labels: d.enhancement

#10668 Fixes Broken image link in "Who is Dash" page
  src/content/dash/index.md
Labels: st.RFM

#10670 Add link to web perf article
  src/content/perf/best-practices.md
Labels: review.copy

#10669 Clean up build linux apps page
  src/content/platform-integration/linux/building.md
Labels: st.RFM.%
