Repository flutter/website, pull requests merged in 2024-01, with the labels that each got.

#10013 Add Tiled to the Games Toolkit resources page
  src/resources/games-toolkit.md
Labels: review.copy

#10042 Fix a variety of broken or outdated link fragments
  src/add-to-app/debugging.md
  src/add-to-app/ios/project-setup.md
  src/perf/ui-performance.md
  src/release/release-notes/release-notes-1.2.1.md
  src/release/whats-new.md
  src/tools/devtools/logging.md
  src/ui/animations/hero-animations.md
  src/ui/interactivity/index.md
Labels: review.copy

#10050 Fix video embed on 'Common errors' page and nearby cleanup
  examples/testing/common_errors/lib/renderflex_overflow.dart
  src/testing/common-errors.md
Labels: st.RFM

#10061 Add documentation for DevTools extensions
  src/_data/sidenav.yml
  src/assets/images/docs/tools/devtools/extension_enable_prompt.png
  src/tools/devtools/extensions.md
Labels: review.await-update

#10056 Adds appBar widget to drawer recipe
  examples/cookbook/design/drawer/lib/drawer.dart
  src/cookbook/design/drawer.md
Labels: review.await-update

#10075 Fix typo in Impeller page
  src/perf/impeller.md
Labels: cla: yes

#9989 document flavors support for macos
  src/deployment/flavors.md
Labels: st.RFM

#10072 Remove external icons
  src/_includes/sidenav-level-1.html
  src/_includes/sidenav-level-2.html
  src/_includes/sidenav-level-3.html
  src/_includes/sidenav-level-4.html
  src/_sass/base/_base.scss
  src/_sass/base/_print-overrides.scss
  src/_sass/components/_sidebar.scss
  src/resources/books.md
Labels: st.RFM

#10038 Adds uninstall page
  src/_includes/docs/install/next-steps.md
  src/_includes/docs/install/reqs/macos/base.md
  src/_includes/docs/install/reqs/macos/unset-path.md
  src/_includes/docs/install/reqs/windows/unset-path.md
  src/_sass/components/_code.scss
  src/assets/js/main.js
  src/get-started/install/macos/desktop.md
  src/get-started/install/macos/mobile-android.md
  src/get-started/install/macos/mobile-ios.md
  src/get-started/install/macos/web.md
  src/get-started/install/windows/desktop.md
  src/get-started/install/windows/mobile.md
  src/get-started/install/windows/web.md
  src/get-started/uninstall/index.md
  src/index.md
Labels: st.RFM

#10067 Add two developer tool design doc go links
  firebase.json
Labels: review.await-update

#10031 Adds PATH for macOS
  _config.yml
  src/_includes/docs/install/compiler/xcode.md
  src/_includes/docs/install/devices/ios-simulator.md
  src/_includes/docs/install/flutter-sdk.md
  src/_includes/docs/install/flutter/download.md
  src/_includes/docs/install/flutter/vscode.md
  src/_includes/docs/install/reqs/flutter-sdk/flutter-doctor-precedence.md
  src/_includes/docs/install/reqs/macos/apple-silicon.md
  src/_includes/docs/install/reqs/macos/base.md
  src/_includes/docs/install/reqs/macos/set-path.md
  src/_includes/docs/install/reqs/macos/software.md
  src/_includes/docs/install/reqs/macos/zsh-config.md
  src/_includes/docs/install/reqs/windows/base.md
Labels: review.copy

#10080 Fix install, uninstall path issues
  src/_includes/docs/install/admonitions/install-paths.md
  src/_includes/docs/install/flutter-doctor.md
  src/_includes/docs/install/flutter/download.md
  src/_includes/docs/install/reqs/macos/unset-path.md
  src/_includes/docs/install/reqs/windows/open-envvars.md
  src/_includes/docs/install/reqs/windows/set-path.md
  src/_includes/docs/install/reqs/windows/unset-path.md
  src/_sass/components/_code.scss
  src/get-started/uninstall/index.md
Labels: st.WIP

#10083 Update deferred loading language
  src/perf/deferred-components.md
Labels: review.tech

#10076 Add migration guide for Material 3
  firebase.json
  src/_data/catalog/index.json
  src/_data/sidenav.yml
  src/release/breaking-changes/index.md
  src/release/breaking-changes/material-3-migration.md
Labels: review.copy, review.await-update

#10094 Clarify GlobalKeys in Forms
  src/cookbook/forms/validation.md
Labels: review.tech

#10093 Update heading margins
  src/_sass/components/_content.scss
Labels: review.tech

#10095 Updated ChromeDriver link
  src/cookbook/testing/integration/introduction.md
  src/testing/integration-tests/index.md
Labels: st.RFM

#10103 Updated initState line order
  examples/perf/deferred_components/lib/use_deferred_box.dart
  src/perf/deferred-components.md
Labels: st.RFM

#10071 Null safety for Shimmer effect
  examples/cookbook/effects/shimmer_loading/lib/original_example.dart
  src/cookbook/effects/shimmer-loading.md
Labels: review.await-update

#10099 Generate an index file for DevTools to fetch release notes from
  src/_data/devtools_releases.yml
  src/tools/devtools/release-notes/index.md
  src/tools/devtools/release-notes/releases.liquid
Labels: review.tech
