Repository flutter/website, pull requests merged in 2024-02, with the labels that each got.

#10134 Fix a variety of minor spelling and grammar issues
  src/_includes/docs/install/devices/android-emulator.md
  src/_includes/docs/install/flutter-doctor.md
  src/_includes/docs/install/reqs/macos/base.md
  src/_includes/docs/install/reqs/windows/base.md
  src/add-to-app/android/_initial-route-cached-engine.md
  src/add-to-app/android/add-flutter-view.md
  src/add-to-app/android/project-setup.md
  src/add-to-app/ios/add-flutter-screen.md
  src/add-to-app/ios/project-setup.md
  src/community/china/_os-settings.md
  src/cookbook/design/fonts.md
  src/cookbook/lists/spaced-items.md
  src/cookbook/testing/integration/introduction.md
  src/deployment/cd.md
  src/deployment/linux.md
  src/deployment/windows.md
  src/get-started/codelab-web.md
  src/get-started/flutter-for/android-devs.md
  src/get-started/flutter-for/uikit-devs.md
  src/get-started/flutter-for/xamarin-forms-devs.md
  src/get-started/install/_get-sdk-mac.md
  src/get-started/install/macos/index.md
  src/get-started/install/windows/index.md
  src/get-started/test-drive/index.md
  src/packages-and-plugins/using-packages.md
  src/perf/app-size.md
  src/perf/deferred-components.md
  src/perf/impeller.md
  src/perf/isolates.md
  src/perf/rendering-performance.md
  src/platform-integration/ios/app-extensions.md
  src/platform-integration/ios/ios-app-clip.md
  src/platform-integration/windows/building.md
  src/reference/user-surveys.md
  src/release/breaking-changes/2-2-deprecations.md
  src/release/breaking-changes/dispose.md
  src/release/breaking-changes/editable-text-scroll-into-view.md
  src/release/breaking-changes/material-3-migration.md
  src/release/breaking-changes/scaffold-messenger.md
  src/release/breaking-changes/theme-data-accent-properties.md
  src/resources/architectural-overview.md
  src/resources/games-toolkit.md
  src/resources/news-toolkit.md
  src/testing/build-modes.md
  src/testing/code-debugging.md
  src/testing/native-debugging.md
  src/tools/devtools/android-studio.md
  src/tools/devtools/memory.md
  src/tools/devtools/release-notes/release-notes-2.8.0-src.md
  src/ui/accessibility-and-internationalization/accessibility.md
  src/ui/interactivity/gestures/drag-outside.md
  src/ui/layout/index.md
  src/ui/layout/responsive/adaptive-responsive.md
  src/ui/layout/tutorial.md
  src/ui/navigation/deep-linking.md
  src/ui/widgets/index.md
Labels: review.copy

#10132 Update, replace, or remove Flutter Gallery references
  _config.yml
  examples/layout/gallery/README.md
  examples/layout/gallery/analysis_options.yaml
  examples/layout/gallery/assets/demos/bottom_navigation_background.png
  examples/layout/gallery/assets/places/india_chennai_flower_market.png
  examples/layout/gallery/assets/places/india_chennai_highway.png
  examples/layout/gallery/assets/places/india_chettinad_produce.png
  examples/layout/gallery/assets/places/india_chettinad_silk_maker.png
  examples/layout/gallery/assets/places/india_pondicherry_beach.png
  examples/layout/gallery/assets/places/india_pondicherry_fisherman.png
  examples/layout/gallery/assets/places/india_pondicherry_salt_farm.png
  examples/layout/gallery/assets/places/india_tanjore_bronze_works.png
  examples/layout/gallery/assets/places/india_tanjore_market_merchant.png
  examples/layout/gallery/assets/places/india_tanjore_market_technology.png
  examples/layout/gallery/assets/places/india_tanjore_thanjavur_temple.png
  examples/layout/gallery/assets/places/india_tanjore_thanjavur_temple_carvings.png
  examples/layout/gallery/assets/places/india_thanjavur_market.png
  examples/layout/gallery/lib/bottom_navigation_demo.dart
  examples/layout/gallery/lib/cards_demo.dart
  examples/layout/gallery/lib/colors_demo.dart
  examples/layout/gallery/lib/grid_list_demo.dart
  examples/layout/gallery/lib/list_demo.dart
  examples/layout/gallery/pubspec.yaml
  src/_data/sidenav.yml
  src/assets/images/docs/ui/layout/card-flutter-gallery.png
  src/assets/images/docs/ui/layout/gridview-count-flutter-gallery.png
  src/assets/images/docs/ui/layout/listtile-flutter-gallery.png
  src/assets/images/docs/ui/layout/listview-color-gallery.png
  src/assets/images/docs/ui/layout/listview-flutter-gallery.png
  src/assets/images/docs/ui/layout/stack-flutter-gallery.png
  src/deployment/cd.md
  src/deployment/windows.md
  src/perf/best-practices.md
  src/perf/deferred-components.md
  src/platform-integration/desktop.md
  src/platform-integration/web/index.md
  src/platform-integration/web/initialization.md
  src/release/breaking-changes/windows-dark-mode.md
  src/release/breaking-changes/windows-show-window-migration.md
  src/release/breaking-changes/windows-version-information.md
  src/release/whats-new.md
  src/ui/accessibility-and-internationalization/accessibility.md
  src/ui/animations/index.md
  src/ui/interactivity/index.md
  src/ui/layout/index.md
  src/ui/layout/responsive/adaptive-responsive.md
  src/ui/layout/tutorial.md
Labels: review.copy

#10131 Breaking changes prep for 3.19
  src/release/breaking-changes/3-16-deprecations.md
  src/release/breaking-changes/flutter-gradle-plugin-apply.md
  src/release/breaking-changes/flutter-memory-allocations.md
  src/release/breaking-changes/index.md
  src/release/breaking-changes/key-event-migration.md
  src/release/breaking-changes/multi-touch-scrolling.md
  src/release/breaking-changes/pageview-controller.md
  src/release/breaking-changes/shortcut-key-event-migration.md
  src/release/breaking-changes/tooltip-semantics-order.md
  src/release/release-notes/index.md
Labels: act.merge-to-next

#10154 Remove Set up Editor link from Install page
  src/get-started/install/index.md
Labels: review.copy

#10155 Fixed macOS unzip command
  src/_includes/docs/install/flutter/download.md
Labels: review.copy

#10170 Clean up yt_shims before migration
  _config.yml
  src/_includes/docs/resource-links/ffi-video-resources.md
  src/_includes/docs/yt_shims.liquid
  src/apprentice-giveaway/index.md
  src/codelabs/index.md
  src/cookbook/design/fonts.md
  src/cookbook/design/snackbars.md
  src/cookbook/design/themes.md
  src/cookbook/effects/download-button.md
  src/cookbook/effects/parallax-scrolling.md
  src/cookbook/games/firestore-multiplayer.md
  src/cookbook/gestures/handling-taps.md
  src/cookbook/persistence/key-value.md
  src/cookbook/persistence/reading-writing-files.md
  src/dash/index.md
  src/data-and-backend/firebase.md
  src/data-and-backend/state-mgmt/options.md
  src/deployment/ios.md
  src/get-started/codelab.md
  src/get-started/flutter-for/swiftui-devs.md
  src/get-started/flutter-for/uikit-devs.md
  src/index.md
  src/packages-and-plugins/using-packages.md
  src/perf/best-practices.md
  src/perf/impeller.md
  src/perf/index.md
  src/perf/isolates.md
  src/perf/ui-performance.md
  src/platform-integration/web/index.md
  src/reference/widgets.md
  src/release/archive-whats-new.md
  src/release/whats-new.md
  src/resources/architectural-overview.md
  src/resources/courses.md
  src/resources/news-toolkit.md
  src/resources/videos.md
  src/testing/common-errors.md
  src/tools/devtools/inspector.md
  src/tools/devtools/memory.md
  src/tools/devtools/overview.md
  src/tools/devtools/performance.md
  src/tools/flutter-fix.md
  src/ui/accessibility-and-internationalization/accessibility.md
  src/ui/animations/hero-animations.md
  src/ui/animations/implicit-animations.md
  src/ui/animations/index.md
  src/ui/animations/staggered-animations.md
  src/ui/design/material/index.md
  src/ui/design/text/typography.md
  src/ui/interactivity/focus.md
  src/ui/interactivity/gestures/index.md
  src/ui/interactivity/index.md
  src/ui/layout/constraints.md
  src/ui/layout/index.md
  src/ui/layout/responsive/adaptive-responsive.md
  src/ui/layout/responsive/building-adaptive-apps.md
  src/ui/layout/scrolling/index.md
  src/ui/layout/scrolling/slivers.md
  src/ui/navigation/deep-linking.md
  src/ui/widgets/index.md
Labels: st.RFM

#10173 Revises macOS install page copy
  src/_sass/vendor/_bootstrap.scss
  src/get-started/install/macos/index.md
  src/get-started/install/windows/index.md
Labels: review.copy

#9369 Update for Android Kotlin DSL based projects
  src/add-to-app/android/project-setup.md
Labels: review.await-update, act.wait-for-customer

#10157 Added CSP test policy
  firebase.json
Labels: st.RFM

#10180 Removes unnecessary brackets from parallax code
  src/cookbook/effects/parallax-scrolling.md
Labels: review.tech

#10174 Added chipsets to supported platforms
  src/_data/chipsets.yml
  src/_data/platforms.yml
  src/reference/supported-platforms.md
Labels: review.await-update

#10216 Remove most Docker usage
  .devcontainer/devcontainer.json
  .dockerignore
  .github/workflows/test.yml
  Dockerfile
  Makefile
  README.md
  _config_dev.yml
  docker-compose.yml
Labels: review.copy, review.tech
